// <copyright file="IOauthBearerTokenCredentials.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>

namespace SwiftBankingAPIPortal.Standard.Authentication
{
    /// <summary>
    /// Authentication configuration interface for OauthBearerToken.
    /// </summary>
    public interface IOauthBearerTokenCredentials
    {
        /// <summary>
        /// Gets string value for accessToken.
        /// </summary>
        string AccessToken { get; }

        /// <summary>
        ///  Returns true if credentials matched.
        /// </summary>
        /// <param name="accessToken"> The string value for credentials.</param>
        /// <returns>True if credentials matched.</returns>
        bool Equals(string accessToken);
    }
}