// <copyright file="OauthBearerTokenManager.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using APIMatic.Core.Authentication;

namespace SwiftBankingAPIPortal.Standard.Authentication
{
    /// <summary>
    /// OauthBearerTokenManager.
    /// </summary>
    internal class OauthBearerTokenManager : AuthManager, IOauthBearerTokenCredentials
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OauthBearerTokenManager"/> class.
        /// </summary>
        /// <param name="oauthBearerTokenModel">OauthBearerTokenModel.</param>
        public OauthBearerTokenManager(OauthBearerTokenModel oauthBearerTokenModel)
        {
            this.AccessToken = oauthBearerTokenModel?.AccessToken;
            Parameters(paramBuilder => paramBuilder
                .Header(header => header.Setup("Authorization",
                    this.AccessToken == null ? null : $"Bearer {this.AccessToken}"
                ).Required()));
        }

        /// <summary>
        /// Gets string value for accessToken.
        /// </summary>
        public string AccessToken { get; }

        /// <summary>
        /// Check if credentials match.
        /// </summary>
        /// <param name="accessToken"> The string value for credentials.</param>
        /// <returns> True if credentials matched.</returns>
        public bool Equals(string accessToken)
        {
            return accessToken.Equals(this.AccessToken);
        }

    }

    public sealed class OauthBearerTokenModel
    {
        internal OauthBearerTokenModel()
        {
        }

        internal string AccessToken { get; set; }

        /// <summary>
        /// Creates an object of the OauthBearerTokenModel using the values provided for the builder.
        /// </summary>
        /// <returns>Builder.</returns>
        public Builder ToBuilder()
        {
            return new Builder(AccessToken);
        }

        /// <summary>
        /// Builder class for OauthBearerTokenModel.
        /// </summary>
        public class Builder
        {
            private string accessToken;

            public Builder(string accessToken)
            {
                this.accessToken = accessToken ?? throw new ArgumentNullException(nameof(accessToken));
            }

            /// <summary>
            /// Sets AccessToken.
            /// </summary>
            /// <param name="accessToken">AccessToken.</param>
            /// <returns>Builder.</returns>
            public Builder AccessToken(string accessToken)
            {
                this.accessToken = accessToken ?? throw new ArgumentNullException(nameof(accessToken));
                return this;
            }

            /// <summary>
            /// Creates an object of the OauthBearerTokenModel using the values provided for the builder.
            /// </summary>
            /// <returns>OauthBearerTokenModel.</returns>
            public OauthBearerTokenModel Build()
            {
                return new OauthBearerTokenModel()
                {
                    AccessToken = this.accessToken
                };
            }
        }

        internal static OauthBearerTokenModel FromOptions(OauthBearerTokenModelOptions options)
        {
            var builder = new Builder(options.AccessToken);
            return builder.Build();
        }
    }

    public class OauthBearerTokenModelOptions
    {
        public string AccessToken { get; set; }
    }
}