// <copyright file="AccountIdentificationIBAN.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// AccountIdentificationIBAN.
    /// </summary>
    public class AccountIdentificationIBAN
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountIdentificationIBAN"/> class.
        /// </summary>
        public AccountIdentificationIBAN()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountIdentificationIBAN"/> class.
        /// </summary>
        /// <param name="iban">iban.</param>
        public AccountIdentificationIBAN(
            string iban)
        {
            this.Iban = iban;
        }

        /// <summary>
        /// An identifier used internationally by financial institutions to uniquely identify the account of a customer at a financial institution, as described in the latest edition of the international standard ISO 13616: 2007 - "Banking and related financial services - International Bank Account Number (IBAN)".
        /// </summary>
        [JsonProperty("iban")]
        public string Iban { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"AccountIdentificationIBAN : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is AccountIdentificationIBAN other &&
                (this.Iban == null && other.Iban == null ||
                 this.Iban?.Equals(other.Iban) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Iban = {this.Iban ?? "null"}");
        }
    }
}