// <copyright file="AccountsResponse.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// AccountsResponse.
    /// </summary>
    public class AccountsResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountsResponse"/> class.
        /// </summary>
        public AccountsResponse()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountsResponse"/> class.
        /// </summary>
        /// <param name="cashAccount">cash_account.</param>
        /// <param name="links">links.</param>
        public AccountsResponse(
            List<Models.CashAccount41> cashAccount,
            List<Models.Link> links = null)
        {
            this.CashAccount = cashAccount;
            this.Links = links;
        }

        /// <summary>
        /// Gets or sets CashAccount.
        /// </summary>
        [JsonProperty("cash_account")]
        public List<Models.CashAccount41> CashAccount { get; set; }

        /// <summary>
        /// Gets or sets Links.
        /// </summary>
        [JsonProperty("links", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.Link> Links { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"AccountsResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is AccountsResponse other &&
                (this.CashAccount == null && other.CashAccount == null ||
                 this.CashAccount?.Equals(other.CashAccount) == true) &&
                (this.Links == null && other.Links == null ||
                 this.Links?.Equals(other.Links) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"CashAccount = {(this.CashAccount == null ? "null" : $"[{string.Join(", ", this.CashAccount)} ]")}");
            toStringOutput.Add($"Links = {(this.Links == null ? "null" : $"[{string.Join(", ", this.Links)} ]")}");
        }
    }
}