// <copyright file="AccountInterest.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// AccountInterest.
    /// </summary>
    public class AccountInterest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountInterest"/> class.
        /// </summary>
        public AccountInterest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountInterest"/> class.
        /// </summary>
        /// <param name="type">type.</param>
        /// <param name="rate">rate.</param>
        /// <param name="fromToDate">from_to_date.</param>
        /// <param name="reason">reason.</param>
        /// <param name="tax">tax.</param>
        public AccountInterest(
            object type = null,
            List<Models.Rate> rate = null,
            Models.FromToDate fromToDate = null,
            string reason = null,
            Models.Tax tax = null)
        {
            this.Type = type;
            this.Rate = rate;
            this.FromToDate = fromToDate;
            this.Reason = reason;
            this.Tax = tax;
        }

        /// <summary>
        /// Gets or sets Type.
        /// </summary>
        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public object Type { get; set; }

        /// <summary>
        /// Set of elements used to qualify the interest rate.
        /// </summary>
        [JsonProperty("rate", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.Rate> Rate { get; set; }

        /// <summary>
        /// Gets or sets FromToDate.
        /// </summary>
        [JsonProperty("from_to_date", NullValueHandling = NullValueHandling.Ignore)]
        public Models.FromToDate FromToDate { get; set; }

        /// <summary>
        /// Specifies the reason for the interest.
        /// </summary>
        [JsonProperty("reason", NullValueHandling = NullValueHandling.Ignore)]
        public string Reason { get; set; }

        /// <summary>
        /// Gets or sets Tax.
        /// </summary>
        [JsonProperty("tax", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Tax Tax { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"AccountInterest : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is AccountInterest other &&
                (this.Type == null && other.Type == null ||
                 this.Type?.Equals(other.Type) == true) &&
                (this.Rate == null && other.Rate == null ||
                 this.Rate?.Equals(other.Rate) == true) &&
                (this.FromToDate == null && other.FromToDate == null ||
                 this.FromToDate?.Equals(other.FromToDate) == true) &&
                (this.Reason == null && other.Reason == null ||
                 this.Reason?.Equals(other.Reason) == true) &&
                (this.Tax == null && other.Tax == null ||
                 this.Tax?.Equals(other.Tax) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Type = {(this.Type == null ? "null" : this.Type.ToString())}");
            toStringOutput.Add($"Rate = {(this.Rate == null ? "null" : $"[{string.Join(", ", this.Rate)} ]")}");
            toStringOutput.Add($"FromToDate = {(this.FromToDate == null ? "null" : this.FromToDate.ToString())}");
            toStringOutput.Add($"Reason = {this.Reason ?? "null"}");
            toStringOutput.Add($"Tax = {(this.Tax == null ? "null" : this.Tax.ToString())}");
        }
    }
}