// <copyright file="AccountsTransactionSummaryResponse.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// AccountsTransactionSummaryResponse.
    /// </summary>
    public class AccountsTransactionSummaryResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountsTransactionSummaryResponse"/> class.
        /// </summary>
        public AccountsTransactionSummaryResponse()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountsTransactionSummaryResponse"/> class.
        /// </summary>
        /// <param name="accountIdentification">account_identification.</param>
        /// <param name="fromDateTime">from_date_time.</param>
        /// <param name="toDateTime">to_date_time.</param>
        /// <param name="totalEntries">total_entries.</param>
        /// <param name="totalCreditEntries">total_credit_entries.</param>
        /// <param name="totalDebitEntries">total_debit_entries.</param>
        public AccountsTransactionSummaryResponse(
            string accountIdentification,
            string fromDateTime,
            string toDateTime,
            Models.TotalEntries totalEntries = null,
            Models.TotalCreditEntries totalCreditEntries = null,
            Models.TotalDebitEntries totalDebitEntries = null)
        {
            this.AccountIdentification = accountIdentification;
            this.FromDateTime = fromDateTime;
            this.ToDateTime = toDateTime;
            this.TotalEntries = totalEntries;
            this.TotalCreditEntries = totalCreditEntries;
            this.TotalDebitEntries = totalDebitEntries;
        }

        /// <summary>
        /// Specifies a character string with a maximum length of 34 characters.
        /// </summary>
        [JsonProperty("account_identification")]
        public string AccountIdentification { get; set; }

        /// <summary>
        /// A particular point in the progression of time defined by a mandatory date and a mandatory time component, expressed in either UTC time format (YYYY-MM-DDThh:mm:ss.sssZ), local time with UTC offset format (YYYY-MM-DDThh:mm:ss.sss+/-hh:mm), or local time format (YYYY-MM-DDThh:mm:ss.sss). These representations are defined in "XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004" which is aligned with ISO 8601.
        /// Note on the time format:
        /// 1) beginning / end of calendar day
        /// 00:00:00 = the beginning of a calendar day
        /// 24:00:00 = the end of a calendar day
        /// 2) fractions of second in time format
        /// Decimal fractions of seconds may be included. In this case, the involved parties shall agree on the maximum number of digits that are allowed.
        /// </summary>
        [JsonProperty("from_date_time")]
        public string FromDateTime { get; set; }

        /// <summary>
        /// A particular point in the progression of time defined by a mandatory date and a mandatory time component, expressed in either UTC time format (YYYY-MM-DDThh:mm:ss.sssZ), local time with UTC offset format (YYYY-MM-DDThh:mm:ss.sss+/-hh:mm), or local time format (YYYY-MM-DDThh:mm:ss.sss). These representations are defined in "XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004" which is aligned with ISO 8601.
        /// Note on the time format:
        /// 1) beginning / end of calendar day
        /// 00:00:00 = the beginning of a calendar day
        /// 24:00:00 = the end of a calendar day
        /// 2) fractions of second in time format
        /// Decimal fractions of seconds may be included. In this case, the involved parties shall agree on the maximum number of digits that are allowed.
        /// </summary>
        [JsonProperty("to_date_time")]
        public string ToDateTime { get; set; }

        /// <summary>
        /// Gets or sets TotalEntries.
        /// </summary>
        [JsonProperty("total_entries", NullValueHandling = NullValueHandling.Ignore)]
        public Models.TotalEntries TotalEntries { get; set; }

        /// <summary>
        /// Gets or sets TotalCreditEntries.
        /// </summary>
        [JsonProperty("total_credit_entries", NullValueHandling = NullValueHandling.Ignore)]
        public Models.TotalCreditEntries TotalCreditEntries { get; set; }

        /// <summary>
        /// Gets or sets TotalDebitEntries.
        /// </summary>
        [JsonProperty("total_debit_entries", NullValueHandling = NullValueHandling.Ignore)]
        public Models.TotalDebitEntries TotalDebitEntries { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"AccountsTransactionSummaryResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is AccountsTransactionSummaryResponse other &&
                (this.AccountIdentification == null && other.AccountIdentification == null ||
                 this.AccountIdentification?.Equals(other.AccountIdentification) == true) &&
                (this.FromDateTime == null && other.FromDateTime == null ||
                 this.FromDateTime?.Equals(other.FromDateTime) == true) &&
                (this.ToDateTime == null && other.ToDateTime == null ||
                 this.ToDateTime?.Equals(other.ToDateTime) == true) &&
                (this.TotalEntries == null && other.TotalEntries == null ||
                 this.TotalEntries?.Equals(other.TotalEntries) == true) &&
                (this.TotalCreditEntries == null && other.TotalCreditEntries == null ||
                 this.TotalCreditEntries?.Equals(other.TotalCreditEntries) == true) &&
                (this.TotalDebitEntries == null && other.TotalDebitEntries == null ||
                 this.TotalDebitEntries?.Equals(other.TotalDebitEntries) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AccountIdentification = {this.AccountIdentification ?? "null"}");
            toStringOutput.Add($"FromDateTime = {this.FromDateTime ?? "null"}");
            toStringOutput.Add($"ToDateTime = {this.ToDateTime ?? "null"}");
            toStringOutput.Add($"TotalEntries = {(this.TotalEntries == null ? "null" : this.TotalEntries.ToString())}");
            toStringOutput.Add($"TotalCreditEntries = {(this.TotalCreditEntries == null ? "null" : this.TotalCreditEntries.ToString())}");
            toStringOutput.Add($"TotalDebitEntries = {(this.TotalDebitEntries == null ? "null" : this.TotalDebitEntries.ToString())}");
        }
    }
}