// <copyright file="ActiveOrHistoricCurrencyAndAmountRange.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// ActiveOrHistoricCurrencyAndAmountRange.
    /// </summary>
    public class ActiveOrHistoricCurrencyAndAmountRange
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ActiveOrHistoricCurrencyAndAmountRange"/> class.
        /// </summary>
        public ActiveOrHistoricCurrencyAndAmountRange()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ActiveOrHistoricCurrencyAndAmountRange"/> class.
        /// </summary>
        /// <param name="amount">amount.</param>
        /// <param name="currency">currency.</param>
        /// <param name="creditDebitIndicator">credit_debit_indicator.</param>
        public ActiveOrHistoricCurrencyAndAmountRange(
            object amount,
            string currency,
            Models.CreditDebitCodeEnum? creditDebitIndicator = null)
        {
            this.Amount = amount;
            this.CreditDebitIndicator = creditDebitIndicator;
            this.Currency = currency;
        }

        /// <summary>
        /// Gets or sets Amount.
        /// </summary>
        [JsonProperty("amount")]
        public object Amount { get; set; }

        /// <summary>
        /// Gets or sets CreditDebitIndicator.
        /// </summary>
        [JsonProperty("credit_debit_indicator", NullValueHandling = NullValueHandling.Ignore)]
        public Models.CreditDebitCodeEnum? CreditDebitIndicator { get; set; }

        /// <summary>
        /// A code allocated to a currency by a Maintenance Agency under an international identification scheme, as described in the latest edition of the international standard ISO 4217 "Codes for the representation of currencies and funds".
        /// </summary>
        [JsonProperty("currency")]
        public string Currency { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ActiveOrHistoricCurrencyAndAmountRange : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ActiveOrHistoricCurrencyAndAmountRange other &&
                (this.Amount == null && other.Amount == null ||
                 this.Amount?.Equals(other.Amount) == true) &&
                (this.CreditDebitIndicator == null && other.CreditDebitIndicator == null ||
                 this.CreditDebitIndicator?.Equals(other.CreditDebitIndicator) == true) &&
                (this.Currency == null && other.Currency == null ||
                 this.Currency?.Equals(other.Currency) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Amount = {(this.Amount == null ? "null" : this.Amount.ToString())}");
            toStringOutput.Add($"CreditDebitIndicator = {(this.CreditDebitIndicator == null ? "null" : this.CreditDebitIndicator.ToString())}");
            toStringOutput.Add($"Currency = {this.Currency ?? "null"}");
        }
    }
}