// <copyright file="AlternateIdentification.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// AlternateIdentification.
    /// </summary>
    public class AlternateIdentification
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AlternateIdentification"/> class.
        /// </summary>
        public AlternateIdentification()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AlternateIdentification"/> class.
        /// </summary>
        /// <param name="identification">identification.</param>
        /// <param name="schemeName">scheme_name.</param>
        /// <param name="issuer">issuer.</param>
        public AlternateIdentification(
            string identification,
            string schemeName = null,
            string issuer = null)
        {
            this.Identification = identification;
            this.SchemeName = schemeName;
            this.Issuer = issuer;
        }

        /// <summary>
        /// Proprietary information, often a code, issued by the data source scheme issuer.
        /// </summary>
        [JsonProperty("identification")]
        public string Identification { get; set; }

        /// <summary>
        /// Short textual description of the scheme.
        /// </summary>
        [JsonProperty("scheme_name", NullValueHandling = NullValueHandling.Ignore)]
        public string SchemeName { get; set; }

        /// <summary>
        /// Entity that assigns the identification.
        /// </summary>
        [JsonProperty("issuer", NullValueHandling = NullValueHandling.Ignore)]
        public string Issuer { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"AlternateIdentification : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is AlternateIdentification other &&
                (this.Identification == null && other.Identification == null ||
                 this.Identification?.Equals(other.Identification) == true) &&
                (this.SchemeName == null && other.SchemeName == null ||
                 this.SchemeName?.Equals(other.SchemeName) == true) &&
                (this.Issuer == null && other.Issuer == null ||
                 this.Issuer?.Equals(other.Issuer) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Identification = {this.Identification ?? "null"}");
            toStringOutput.Add($"SchemeName = {this.SchemeName ?? "null"}");
            toStringOutput.Add($"Issuer = {this.Issuer ?? "null"}");
        }
    }
}