// <copyright file="AmountAndCurrencyExchange.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// AmountAndCurrencyExchange.
    /// </summary>
    public class AmountAndCurrencyExchange
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AmountAndCurrencyExchange"/> class.
        /// </summary>
        public AmountAndCurrencyExchange()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AmountAndCurrencyExchange"/> class.
        /// </summary>
        /// <param name="instructedAmount">instructed_amount.</param>
        /// <param name="transactionAmount">transaction_amount.</param>
        /// <param name="counterValueAmount">counter_value_amount.</param>
        /// <param name="announcedPostingAmount">announced_posting_amount.</param>
        /// <param name="proprietaryAmount">proprietary_amount.</param>
        public AmountAndCurrencyExchange(
            Models.InstructedAmount instructedAmount = null,
            Models.TransactionAmount transactionAmount = null,
            Models.CounterValueAmount counterValueAmount = null,
            Models.AnnouncedPostingAmount announcedPostingAmount = null,
            List<Models.AmountAndCurrencyExchangeDetails> proprietaryAmount = null)
        {
            this.InstructedAmount = instructedAmount;
            this.TransactionAmount = transactionAmount;
            this.CounterValueAmount = counterValueAmount;
            this.AnnouncedPostingAmount = announcedPostingAmount;
            this.ProprietaryAmount = proprietaryAmount;
        }

        /// <summary>
        /// Gets or sets InstructedAmount.
        /// </summary>
        [JsonProperty("instructed_amount", NullValueHandling = NullValueHandling.Ignore)]
        public Models.InstructedAmount InstructedAmount { get; set; }

        /// <summary>
        /// Gets or sets TransactionAmount.
        /// </summary>
        [JsonProperty("transaction_amount", NullValueHandling = NullValueHandling.Ignore)]
        public Models.TransactionAmount TransactionAmount { get; set; }

        /// <summary>
        /// Gets or sets CounterValueAmount.
        /// </summary>
        [JsonProperty("counter_value_amount", NullValueHandling = NullValueHandling.Ignore)]
        public Models.CounterValueAmount CounterValueAmount { get; set; }

        /// <summary>
        /// Gets or sets AnnouncedPostingAmount.
        /// </summary>
        [JsonProperty("announced_posting_amount", NullValueHandling = NullValueHandling.Ignore)]
        public Models.AnnouncedPostingAmount AnnouncedPostingAmount { get; set; }

        /// <summary>
        /// Set of elements used to provide information on the original amount and currency exchange.
        /// </summary>
        [JsonProperty("proprietary_amount", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.AmountAndCurrencyExchangeDetails> ProprietaryAmount { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"AmountAndCurrencyExchange : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is AmountAndCurrencyExchange other &&
                (this.InstructedAmount == null && other.InstructedAmount == null ||
                 this.InstructedAmount?.Equals(other.InstructedAmount) == true) &&
                (this.TransactionAmount == null && other.TransactionAmount == null ||
                 this.TransactionAmount?.Equals(other.TransactionAmount) == true) &&
                (this.CounterValueAmount == null && other.CounterValueAmount == null ||
                 this.CounterValueAmount?.Equals(other.CounterValueAmount) == true) &&
                (this.AnnouncedPostingAmount == null && other.AnnouncedPostingAmount == null ||
                 this.AnnouncedPostingAmount?.Equals(other.AnnouncedPostingAmount) == true) &&
                (this.ProprietaryAmount == null && other.ProprietaryAmount == null ||
                 this.ProprietaryAmount?.Equals(other.ProprietaryAmount) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"InstructedAmount = {(this.InstructedAmount == null ? "null" : this.InstructedAmount.ToString())}");
            toStringOutput.Add($"TransactionAmount = {(this.TransactionAmount == null ? "null" : this.TransactionAmount.ToString())}");
            toStringOutput.Add($"CounterValueAmount = {(this.CounterValueAmount == null ? "null" : this.CounterValueAmount.ToString())}");
            toStringOutput.Add($"AnnouncedPostingAmount = {(this.AnnouncedPostingAmount == null ? "null" : this.AnnouncedPostingAmount.ToString())}");
            toStringOutput.Add($"ProprietaryAmount = {(this.ProprietaryAmount == null ? "null" : $"[{string.Join(", ", this.ProprietaryAmount)} ]")}");
        }
    }
}