// <copyright file="BalanceAmount.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// BalanceAmount.
    /// </summary>
    public class BalanceAmount
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BalanceAmount"/> class.
        /// </summary>
        public BalanceAmount()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BalanceAmount"/> class.
        /// </summary>
        /// <param name="amount">amount.</param>
        /// <param name="creditDebitIndicator">credit_debit_indicator.</param>
        public BalanceAmount(
            Models.Amount12 amount,
            Models.CreditDebitCodeEnum creditDebitIndicator)
        {
            this.Amount = amount;
            this.CreditDebitIndicator = creditDebitIndicator;
        }

        /// <summary>
        /// Gets or sets Amount.
        /// </summary>
        [JsonProperty("amount")]
        public Models.Amount12 Amount { get; set; }

        /// <summary>
        /// Gets or sets CreditDebitIndicator.
        /// </summary>
        [JsonProperty("credit_debit_indicator")]
        public Models.CreditDebitCodeEnum CreditDebitIndicator { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"BalanceAmount : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is BalanceAmount other &&
                (this.Amount == null && other.Amount == null ||
                 this.Amount?.Equals(other.Amount) == true) &&
                (this.CreditDebitIndicator.Equals(other.CreditDebitIndicator));
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Amount = {(this.Amount == null ? "null" : this.Amount.ToString())}");
            toStringOutput.Add($"CreditDebitIndicator = {this.CreditDebitIndicator}");
        }
    }
}