// <copyright file="BalancesList3.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// BalancesList3.
    /// </summary>
    public class BalancesList3
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BalancesList3"/> class.
        /// </summary>
        public BalancesList3()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BalancesList3"/> class.
        /// </summary>
        /// <param name="currentBalance">current_balance.</param>
        /// <param name="availableBalance">available_balance.</param>
        /// <param name="forwardAvailableBalance">forward_available_balance.</param>
        public BalancesList3(
            Models.CurrentBalance currentBalance,
            Models.AvailableBalance availableBalance = null,
            List<Models.CashForwardAvailableBalance1> forwardAvailableBalance = null)
        {
            this.CurrentBalance = currentBalance;
            this.AvailableBalance = availableBalance;
            this.ForwardAvailableBalance = forwardAvailableBalance;
        }

        /// <summary>
        /// Gets or sets CurrentBalance.
        /// </summary>
        [JsonProperty("current_balance")]
        public Models.CurrentBalance CurrentBalance { get; set; }

        /// <summary>
        /// Gets or sets AvailableBalance.
        /// </summary>
        [JsonProperty("available_balance", NullValueHandling = NullValueHandling.Ignore)]
        public Models.AvailableBalance AvailableBalance { get; set; }

        /// <summary>
        /// Provides detailed information of the forward available balance of a specific cash account. Subject to the service provided by the Account Servicer, forward available balance can be presented with multiple times for multiple reference dates.
        /// </summary>
        [JsonProperty("forward_available_balance", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.CashForwardAvailableBalance1> ForwardAvailableBalance { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"BalancesList3 : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is BalancesList3 other &&
                (this.CurrentBalance == null && other.CurrentBalance == null ||
                 this.CurrentBalance?.Equals(other.CurrentBalance) == true) &&
                (this.AvailableBalance == null && other.AvailableBalance == null ||
                 this.AvailableBalance?.Equals(other.AvailableBalance) == true) &&
                (this.ForwardAvailableBalance == null && other.ForwardAvailableBalance == null ||
                 this.ForwardAvailableBalance?.Equals(other.ForwardAvailableBalance) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"CurrentBalance = {(this.CurrentBalance == null ? "null" : this.CurrentBalance.ToString())}");
            toStringOutput.Add($"AvailableBalance = {(this.AvailableBalance == null ? "null" : this.AvailableBalance.ToString())}");
            toStringOutput.Add($"ForwardAvailableBalance = {(this.ForwardAvailableBalance == null ? "null" : $"[{string.Join(", ", this.ForwardAvailableBalance)} ]")}");
        }
    }
}