// <copyright file="BalanceTypeCodeEnum.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// BalanceTypeCodeEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum BalanceTypeCodeEnum
    {
        /// <summary>
        /// CLAV.
        /// </summary>
        [EnumMember(Value = "CLAV")]
        CLAV,

        /// <summary>
        /// CLBD.
        /// </summary>
        [EnumMember(Value = "CLBD")]
        CLBD,

        /// <summary>
        /// FWAV.
        /// </summary>
        [EnumMember(Value = "FWAV")]
        FWAV,

        /// <summary>
        /// ITAV.
        /// </summary>
        [EnumMember(Value = "ITAV")]
        ITAV,

        /// <summary>
        /// OPAV.
        /// </summary>
        [EnumMember(Value = "OPAV")]
        OPAV,

        /// <summary>
        /// OPBD.
        /// </summary>
        [EnumMember(Value = "OPBD")]
        OPBD,

        /// <summary>
        /// PRCD.
        /// </summary>
        [EnumMember(Value = "PRCD")]
        PRCD
    }
}