// <copyright file="Batch.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// Batch.
    /// </summary>
    public class Batch
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Batch"/> class.
        /// </summary>
        public Batch()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Batch"/> class.
        /// </summary>
        /// <param name="messageIdentification">message_identification.</param>
        /// <param name="paymentInformationIdentification">payment_information_identification.</param>
        /// <param name="numberOfTransactions">number_of_transactions.</param>
        /// <param name="totalAmount">total_amount.</param>
        /// <param name="creditDebitIndicator">credit_debit_indicator.</param>
        public Batch(
            string messageIdentification = null,
            string paymentInformationIdentification = null,
            int? numberOfTransactions = null,
            Models.TotalAmount totalAmount = null,
            Models.CreditDebitCodeEnum? creditDebitIndicator = null)
        {
            this.MessageIdentification = messageIdentification;
            this.PaymentInformationIdentification = paymentInformationIdentification;
            this.NumberOfTransactions = numberOfTransactions;
            this.TotalAmount = totalAmount;
            this.CreditDebitIndicator = creditDebitIndicator;
        }

        /// <summary>
        /// Point to point reference, as assigned by the sending party, to unambiguously identify the batch of transactions.
        /// </summary>
        [JsonProperty("message_identification", NullValueHandling = NullValueHandling.Ignore)]
        public string MessageIdentification { get; set; }

        /// <summary>
        /// Unique identification, as assigned by a sending party, to unambiguously identify the payment information group within the message.
        /// </summary>
        [JsonProperty("payment_information_identification", NullValueHandling = NullValueHandling.Ignore)]
        public string PaymentInformationIdentification { get; set; }

        /// <summary>
        /// Gets or sets NumberOfTransactions.
        /// </summary>
        [JsonProperty("number_of_transactions", NullValueHandling = NullValueHandling.Ignore)]
        public int? NumberOfTransactions { get; set; }

        /// <summary>
        /// Gets or sets TotalAmount.
        /// </summary>
        [JsonProperty("total_amount", NullValueHandling = NullValueHandling.Ignore)]
        public Models.TotalAmount TotalAmount { get; set; }

        /// <summary>
        /// Gets or sets CreditDebitIndicator.
        /// </summary>
        [JsonProperty("credit_debit_indicator", NullValueHandling = NullValueHandling.Ignore)]
        public Models.CreditDebitCodeEnum? CreditDebitIndicator { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Batch : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is Batch other &&
                (this.MessageIdentification == null && other.MessageIdentification == null ||
                 this.MessageIdentification?.Equals(other.MessageIdentification) == true) &&
                (this.PaymentInformationIdentification == null && other.PaymentInformationIdentification == null ||
                 this.PaymentInformationIdentification?.Equals(other.PaymentInformationIdentification) == true) &&
                (this.NumberOfTransactions == null && other.NumberOfTransactions == null ||
                 this.NumberOfTransactions?.Equals(other.NumberOfTransactions) == true) &&
                (this.TotalAmount == null && other.TotalAmount == null ||
                 this.TotalAmount?.Equals(other.TotalAmount) == true) &&
                (this.CreditDebitIndicator == null && other.CreditDebitIndicator == null ||
                 this.CreditDebitIndicator?.Equals(other.CreditDebitIndicator) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"MessageIdentification = {this.MessageIdentification ?? "null"}");
            toStringOutput.Add($"PaymentInformationIdentification = {this.PaymentInformationIdentification ?? "null"}");
            toStringOutput.Add($"NumberOfTransactions = {(this.NumberOfTransactions == null ? "null" : this.NumberOfTransactions.ToString())}");
            toStringOutput.Add($"TotalAmount = {(this.TotalAmount == null ? "null" : this.TotalAmount.ToString())}");
            toStringOutput.Add($"CreditDebitIndicator = {(this.CreditDebitIndicator == null ? "null" : this.CreditDebitIndicator.ToString())}");
        }
    }
}