// <copyright file="BranchIdentification2.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using SwiftBankingAPIPortal.Standard.Models.Containers;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// BranchIdentification2.
    /// </summary>
    public class BranchIdentification2
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BranchIdentification2"/> class.
        /// </summary>
        public BranchIdentification2()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BranchIdentification2"/> class.
        /// </summary>
        /// <param name="identification">identification.</param>
        /// <param name="lei">lei.</param>
        /// <param name="name">name.</param>
        /// <param name="postalAddress">postal_address.</param>
        public BranchIdentification2(
            string identification = null,
            string lei = null,
            string name = null,
            BranchIdentification2PostalAddress postalAddress = null)
        {
            this.Identification = identification;
            this.Lei = lei;
            this.Name = name;
            this.PostalAddress = postalAddress;
        }

        /// <summary>
        /// Unique and unambiguous identification of a branch of a financial institution.
        /// </summary>
        [JsonProperty("identification", NullValueHandling = NullValueHandling.Ignore)]
        public string Identification { get; set; }

        /// <summary>
        /// Legal Entity Identifier is a code allocated to a party as described in ISO 17442 "Financial Services - Legal Entity Identifier (LEI)".
        /// </summary>
        [JsonProperty("lei", NullValueHandling = NullValueHandling.Ignore)]
        public string Lei { get; set; }

        /// <summary>
        /// Name by which an agent is known and which is usually used to identify that agent.
        /// </summary>
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        /// <summary>
        /// Information that locates and identifies a specific address, as defined by postal services.
        /// RECOMMENDATION IN ORDER OF PREFERENCE:
        /// * Use only structured address with mandatory Town Name and Country
        /// * When using unstructured address, (Address Line), max 1 occurrence with 105 text is allowed.
        /// * Address Line must not contain Country which must be included in the dedicated Country element in the unstructured structured address.
        /// </summary>
        [JsonProperty("postal_address", NullValueHandling = NullValueHandling.Ignore)]
        public BranchIdentification2PostalAddress PostalAddress { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"BranchIdentification2 : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is BranchIdentification2 other &&
                (this.Identification == null && other.Identification == null ||
                 this.Identification?.Equals(other.Identification) == true) &&
                (this.Lei == null && other.Lei == null ||
                 this.Lei?.Equals(other.Lei) == true) &&
                (this.Name == null && other.Name == null ||
                 this.Name?.Equals(other.Name) == true) &&
                (this.PostalAddress == null && other.PostalAddress == null ||
                 this.PostalAddress?.Equals(other.PostalAddress) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Identification = {this.Identification ?? "null"}");
            toStringOutput.Add($"Lei = {this.Lei ?? "null"}");
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"PostalAddress = {(this.PostalAddress == null ? "null" : this.PostalAddress.ToString())}");
        }
    }
}