// <copyright file="CashAccountTypeCode.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// CashAccountTypeCode.
    /// </summary>
    public class CashAccountTypeCode
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CashAccountTypeCode"/> class.
        /// </summary>
        public CashAccountTypeCode()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CashAccountTypeCode"/> class.
        /// </summary>
        /// <param name="code">code.</param>
        public CashAccountTypeCode(
            string code)
        {
            this.Code = code;
        }

        /// <summary>
        /// Specifies the nature, or use, of the cash account in the format of character string with a maximum length of 4 characters. The list of valid codes is an external code list published separately. External code sets can be downloaded from www.iso20022.org.
        /// </summary>
        [JsonProperty("code")]
        public string Code { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CashAccountTypeCode : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is CashAccountTypeCode other &&
                (this.Code == null && other.Code == null ||
                 this.Code?.Equals(other.Code) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Code = {this.Code ?? "null"}");
        }
    }
}