// <copyright file="CashAccount41.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// CashAccount41.
    /// </summary>
    public class CashAccount41
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CashAccount41"/> class.
        /// </summary>
        public CashAccount41()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CashAccount41"/> class.
        /// </summary>
        /// <param name="accountIdentification">account_identification.</param>
        /// <param name="name">name.</param>
        /// <param name="currency">currency.</param>
        /// <param name="balances">balances.</param>
        /// <param name="alternateIdentification">alternate_identification.</param>
        /// <param name="accountServicer">account_servicer.</param>
        /// <param name="ownerName">owner_name.</param>
        /// <param name="relatedAccount">related_account.</param>
        /// <param name="status">status.</param>
        /// <param name="creditLimit">credit_limit.</param>
        /// <param name="links">links.</param>
        public CashAccount41(
            string accountIdentification,
            string name,
            string currency,
            Models.Balances balances,
            Guid? alternateIdentification = null,
            string accountServicer = null,
            string ownerName = null,
            string relatedAccount = null,
            string status = null,
            Models.CreditLimit creditLimit = null,
            List<Models.Link> links = null)
        {
            this.AccountIdentification = accountIdentification;
            this.AlternateIdentification = alternateIdentification;
            this.AccountServicer = accountServicer;
            this.Name = name;
            this.OwnerName = ownerName;
            this.Currency = currency;
            this.RelatedAccount = relatedAccount;
            this.Balances = balances;
            this.Status = status;
            this.CreditLimit = creditLimit;
            this.Links = links;
        }

        /// <summary>
        /// Identification of the account as defined by the account service provider. It can be in IBAN or proprietary format.
        /// RECOMMENDATION IN ORDER OF PREFERENCE:
        /// IBAN - When available IBAN must be specified for instance endpoint or hyper link to work.
        /// Other - In the absence of IBAN, this must be an unique account identification used for routing of the payment to the account via clearing system. A format which is agreed between the account owner and the account servicer. For example a SWIFT BIC/Branch Code and Account number.
        /// </summary>
        [JsonProperty("account_identification")]
        public string AccountIdentification { get; set; }

        /// <summary>
        /// The ID of the account that the bank account is associated with. The value must be constant throughout the lifecycle of the account. This identification shall be used as a resource identifier where account identification cannot be used as a resource identification. Specified as Universally Unique Identifier (UUID) version 4, as described in IETC RFC 4122 "Universally Unique Identifier (UUID) URN Namespace
        /// Usage: The account_identification is the resource identification. This identification should be used when account_identification cannot be used as an identification due to the internal policy of an organisation. Should that be the case, all other endpoint require account_identification in path parameter must use the same identification return by this endpoint.
        /// </summary>
        [JsonProperty("alternate_identification", NullValueHandling = NullValueHandling.Ignore)]
        public Guid? AlternateIdentification { get; set; }

        /// <summary>
        /// Code allocated to a financial institution by the ISO 9362 Registration Authority as described in ISO 9362 - 2014 - Banking - Banking telecommunication messages - Business identifier code (BIC)
        /// </summary>
        [JsonProperty("account_servicer", NullValueHandling = NullValueHandling.Ignore)]
        public string AccountServicer { get; set; }

        /// <summary>
        /// Specifies a character string with a maximum length of 70characters.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; }

        /// <summary>
        /// Specifies a character string with a maximum length of 70characters.
        /// </summary>
        [JsonProperty("owner_name", NullValueHandling = NullValueHandling.Ignore)]
        public string OwnerName { get; set; }

        /// <summary>
        /// A code allocated to a currency by a Maintenance Agency under an international identification scheme as described in the latest edition of the international standard ISO 4217 'Codes for the representation of currencies and funds
        /// </summary>
        [JsonProperty("currency")]
        public string Currency { get; set; }

        /// <summary>
        /// Identifies the parent account of the account for which the statement has been issued.
        /// Usage: Should be used when more than one identification is required to clearly establish the identity. For example when Proxy Identification is specified in primary identification a secondary identification Proxy Code is required for unambiguous identification. Another example is when Virtual Account or Zero Balance Account is specified in the primary identification, the alternate identification should be the parent account.
        /// </summary>
        [JsonProperty("related_account", NullValueHandling = NullValueHandling.Ignore)]
        public string RelatedAccount { get; set; }

        /// <summary>
        /// Gets or sets Balances.
        /// </summary>
        [JsonProperty("balances")]
        public Models.Balances Balances { get; set; }

        /// <summary>
        /// Specifies a character string with a maximum length of 35 characters.
        /// </summary>
        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or sets CreditLimit.
        /// </summary>
        [JsonProperty("credit_limit", NullValueHandling = NullValueHandling.Ignore)]
        public Models.CreditLimit CreditLimit { get; set; }

        /// <summary>
        /// Gets or sets Links.
        /// </summary>
        [JsonProperty("links", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.Link> Links { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CashAccount41 : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is CashAccount41 other &&
                (this.AccountIdentification == null && other.AccountIdentification == null ||
                 this.AccountIdentification?.Equals(other.AccountIdentification) == true) &&
                (this.AlternateIdentification == null && other.AlternateIdentification == null ||
                 this.AlternateIdentification?.Equals(other.AlternateIdentification) == true) &&
                (this.AccountServicer == null && other.AccountServicer == null ||
                 this.AccountServicer?.Equals(other.AccountServicer) == true) &&
                (this.Name == null && other.Name == null ||
                 this.Name?.Equals(other.Name) == true) &&
                (this.OwnerName == null && other.OwnerName == null ||
                 this.OwnerName?.Equals(other.OwnerName) == true) &&
                (this.Currency == null && other.Currency == null ||
                 this.Currency?.Equals(other.Currency) == true) &&
                (this.RelatedAccount == null && other.RelatedAccount == null ||
                 this.RelatedAccount?.Equals(other.RelatedAccount) == true) &&
                (this.Balances == null && other.Balances == null ||
                 this.Balances?.Equals(other.Balances) == true) &&
                (this.Status == null && other.Status == null ||
                 this.Status?.Equals(other.Status) == true) &&
                (this.CreditLimit == null && other.CreditLimit == null ||
                 this.CreditLimit?.Equals(other.CreditLimit) == true) &&
                (this.Links == null && other.Links == null ||
                 this.Links?.Equals(other.Links) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AccountIdentification = {this.AccountIdentification ?? "null"}");
            toStringOutput.Add($"AlternateIdentification = {(this.AlternateIdentification == null ? "null" : this.AlternateIdentification.ToString())}");
            toStringOutput.Add($"AccountServicer = {this.AccountServicer ?? "null"}");
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"OwnerName = {this.OwnerName ?? "null"}");
            toStringOutput.Add($"Currency = {this.Currency ?? "null"}");
            toStringOutput.Add($"RelatedAccount = {this.RelatedAccount ?? "null"}");
            toStringOutput.Add($"Balances = {(this.Balances == null ? "null" : this.Balances.ToString())}");
            toStringOutput.Add($"Status = {this.Status ?? "null"}");
            toStringOutput.Add($"CreditLimit = {(this.CreditLimit == null ? "null" : this.CreditLimit.ToString())}");
            toStringOutput.Add($"Links = {(this.Links == null ? "null" : $"[{string.Join(", ", this.Links)} ]")}");
        }
    }
}