// <copyright file="CashCurrentBalance1.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// CashCurrentBalance1.
    /// </summary>
    public class CashCurrentBalance1
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CashCurrentBalance1"/> class.
        /// </summary>
        public CashCurrentBalance1()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CashCurrentBalance1"/> class.
        /// </summary>
        /// <param name="balanceAmount">balance_amount.</param>
        /// <param name="dateTime">date_time.</param>
        /// <param name="lastChangeDateTime">last_change_date_time.</param>
        /// <param name="lastCommittedTransactionIdentification">last_committed_transaction_identification.</param>
        /// <param name="creditLine">credit_line.</param>
        public CashCurrentBalance1(
            Models.BalanceAmount balanceAmount,
            string dateTime,
            string lastChangeDateTime = null,
            string lastCommittedTransactionIdentification = null,
            List<Models.CreditLine6> creditLine = null)
        {
            this.BalanceAmount = balanceAmount;
            this.LastChangeDateTime = lastChangeDateTime;
            this.DateTime = dateTime;
            this.LastCommittedTransactionIdentification = lastCommittedTransactionIdentification;
            this.CreditLine = creditLine;
        }

        /// <summary>
        /// Gets or sets BalanceAmount.
        /// </summary>
        [JsonProperty("balance_amount")]
        public Models.BalanceAmount BalanceAmount { get; set; }

        /// <summary>
        /// A particular point in the progression of time defined by a mandatory date and a mandatory time component, expressed in either UTC time format (YYYY-MM-DDThh:mm:ss.sssZ), local time with UTC offset format (YYYY-MM-DDThh:mm:ss.sss+/-hh:mm), or local time format (YYYY-MM-DDThh:mm:ss.sss). These representations are defined in "XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004" which is aligned with ISO 8601.
        /// Note on the time format:
        /// 1) beginning / end of calendar day
        /// 00:00:00 = the beginning of a calendar day
        /// 24:00:00 = the end of a calendar day
        /// 2) fractions of second in time format
        /// Decimal fractions of seconds may be included. In this case, the involved parties shall agree on the maximum number of digits that are allowed.
        /// </summary>
        [JsonProperty("last_change_date_time", NullValueHandling = NullValueHandling.Ignore)]
        public string LastChangeDateTime { get; set; }

        /// <summary>
        /// A particular point in the progression of time defined by a mandatory date and a mandatory time component, expressed in either UTC time format (YYYY-MM-DDThh:mm:ss.sssZ), local time with UTC offset format (YYYY-MM-DDThh:mm:ss.sss+/-hh:mm), or local time format (YYYY-MM-DDThh:mm:ss.sss). These representations are defined in "XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004" which is aligned with ISO 8601.
        /// Note on the time format:
        /// 1) beginning / end of calendar day
        /// 00:00:00 = the beginning of a calendar day
        /// 24:00:00 = the end of a calendar day
        /// 2) fractions of second in time format
        /// Decimal fractions of seconds may be included. In this case, the involved parties shall agree on the maximum number of digits that are allowed.
        /// </summary>
        [JsonProperty("date_time")]
        public string DateTime { get; set; }

        /// <summary>
        /// Specifies a character string with a maximum length of 40 characters.
        /// </summary>
        [JsonProperty("last_committed_transaction_identification", NullValueHandling = NullValueHandling.Ignore)]
        public string LastCommittedTransactionIdentification { get; set; }

        /// <summary>
        /// Provides details on the credit line linked to the account.
        /// </summary>
        [JsonProperty("credit_line", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.CreditLine6> CreditLine { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CashCurrentBalance1 : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is CashCurrentBalance1 other &&
                (this.BalanceAmount == null && other.BalanceAmount == null ||
                 this.BalanceAmount?.Equals(other.BalanceAmount) == true) &&
                (this.LastChangeDateTime == null && other.LastChangeDateTime == null ||
                 this.LastChangeDateTime?.Equals(other.LastChangeDateTime) == true) &&
                (this.DateTime == null && other.DateTime == null ||
                 this.DateTime?.Equals(other.DateTime) == true) &&
                (this.LastCommittedTransactionIdentification == null && other.LastCommittedTransactionIdentification == null ||
                 this.LastCommittedTransactionIdentification?.Equals(other.LastCommittedTransactionIdentification) == true) &&
                (this.CreditLine == null && other.CreditLine == null ||
                 this.CreditLine?.Equals(other.CreditLine) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"BalanceAmount = {(this.BalanceAmount == null ? "null" : this.BalanceAmount.ToString())}");
            toStringOutput.Add($"LastChangeDateTime = {this.LastChangeDateTime ?? "null"}");
            toStringOutput.Add($"DateTime = {this.DateTime ?? "null"}");
            toStringOutput.Add($"LastCommittedTransactionIdentification = {this.LastCommittedTransactionIdentification ?? "null"}");
            toStringOutput.Add($"CreditLine = {(this.CreditLine == null ? "null" : $"[{string.Join(", ", this.CreditLine)} ]")}");
        }
    }
}