// <copyright file="CashAvailableBalance1.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// CashAvailableBalance1.
    /// </summary>
    public class CashAvailableBalance1
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CashAvailableBalance1"/> class.
        /// </summary>
        public CashAvailableBalance1()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CashAvailableBalance1"/> class.
        /// </summary>
        /// <param name="balanceAmount">balance_amount.</param>
        /// <param name="availabilityDate">availability_date.</param>
        public CashAvailableBalance1(
            Models.BalanceAmount balanceAmount,
            string availabilityDate)
        {
            this.BalanceAmount = balanceAmount;
            this.AvailabilityDate = availabilityDate;
        }

        /// <summary>
        /// Gets or sets BalanceAmount.
        /// </summary>
        [JsonProperty("balance_amount")]
        public Models.BalanceAmount BalanceAmount { get; set; }

        /// <summary>
        /// A particular point in the progression of time defined by a mandatory date and a mandatory time component, expressed in either UTC time format (YYYY-MM-DDThh:mm:ss.sssZ), local time with UTC offset format (YYYY-MM-DDThh:mm:ss.sss+/-hh:mm), or local time format (YYYY-MM-DDThh:mm:ss.sss). These representations are defined in "XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004" which is aligned with ISO 8601.
        /// Note on the time format:
        /// 1) beginning / end of calendar day
        /// 00:00:00 = the beginning of a calendar day
        /// 24:00:00 = the end of a calendar day
        /// 2) fractions of second in time format
        /// Decimal fractions of seconds may be included. In this case, the involved parties shall agree on the maximum number of digits that are allowed.
        /// </summary>
        [JsonProperty("availability_date")]
        public string AvailabilityDate { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CashAvailableBalance1 : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is CashAvailableBalance1 other &&
                (this.BalanceAmount == null && other.BalanceAmount == null ||
                 this.BalanceAmount?.Equals(other.BalanceAmount) == true) &&
                (this.AvailabilityDate == null && other.AvailabilityDate == null ||
                 this.AvailabilityDate?.Equals(other.AvailabilityDate) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"BalanceAmount = {(this.BalanceAmount == null ? "null" : this.BalanceAmount.ToString())}");
            toStringOutput.Add($"AvailabilityDate = {this.AvailabilityDate ?? "null"}");
        }
    }
}