// <copyright file="ChargesRecord.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// ChargesRecord.
    /// </summary>
    public class ChargesRecord
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ChargesRecord"/> class.
        /// </summary>
        public ChargesRecord()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChargesRecord"/> class.
        /// </summary>
        /// <param name="amount">amount.</param>
        /// <param name="creditDebitIndicator">credit_debit_indicator.</param>
        /// <param name="chargeIncludedIndicator">charge_included_indicator.</param>
        /// <param name="type">type.</param>
        /// <param name="rate">rate.</param>
        /// <param name="bearer">bearer.</param>
        /// <param name="agent">agent.</param>
        /// <param name="tax">tax.</param>
        public ChargesRecord(
            Models.Amount amount,
            Models.CreditDebitCodeEnum? creditDebitIndicator = null,
            bool? chargeIncludedIndicator = null,
            Models.Type type = null,
            string rate = null,
            Models.ChargeBearerTypeCodeEnum? bearer = null,
            Models.Agent agent = null,
            Models.Tax tax = null)
        {
            this.Amount = amount;
            this.CreditDebitIndicator = creditDebitIndicator;
            this.ChargeIncludedIndicator = chargeIncludedIndicator;
            this.Type = type;
            this.Rate = rate;
            this.Bearer = bearer;
            this.Agent = agent;
            this.Tax = tax;
        }

        /// <summary>
        /// Gets or sets Amount.
        /// </summary>
        [JsonProperty("amount")]
        public Models.Amount Amount { get; set; }

        /// <summary>
        /// Gets or sets CreditDebitIndicator.
        /// </summary>
        [JsonProperty("credit_debit_indicator", NullValueHandling = NullValueHandling.Ignore)]
        public Models.CreditDebitCodeEnum? CreditDebitIndicator { get; set; }

        /// <summary>
        /// Indicates whether the charge should be included in the amount or is added as pre-advice.
        /// </summary>
        [JsonProperty("charge_included_indicator", NullValueHandling = NullValueHandling.Ignore)]
        public bool? ChargeIncludedIndicator { get; set; }

        /// <summary>
        /// Gets or sets Type.
        /// </summary>
        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Type Type { get; set; }

        /// <summary>
        /// Rate expressed as a percentage, that is, in hundredths, for example, 0.7 is 7/10 of a percent, and 7.0 is 7%.
        /// </summary>
        [JsonProperty("rate", NullValueHandling = NullValueHandling.Ignore)]
        public string Rate { get; set; }

        /// <summary>
        /// Gets or sets Bearer.
        /// </summary>
        [JsonProperty("bearer", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ChargeBearerTypeCodeEnum? Bearer { get; set; }

        /// <summary>
        /// Gets or sets Agent.
        /// </summary>
        [JsonProperty("agent", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Agent Agent { get; set; }

        /// <summary>
        /// Gets or sets Tax.
        /// </summary>
        [JsonProperty("tax", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Tax Tax { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ChargesRecord : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ChargesRecord other &&
                (this.Amount == null && other.Amount == null ||
                 this.Amount?.Equals(other.Amount) == true) &&
                (this.CreditDebitIndicator == null && other.CreditDebitIndicator == null ||
                 this.CreditDebitIndicator?.Equals(other.CreditDebitIndicator) == true) &&
                (this.ChargeIncludedIndicator == null && other.ChargeIncludedIndicator == null ||
                 this.ChargeIncludedIndicator?.Equals(other.ChargeIncludedIndicator) == true) &&
                (this.Type == null && other.Type == null ||
                 this.Type?.Equals(other.Type) == true) &&
                (this.Rate == null && other.Rate == null ||
                 this.Rate?.Equals(other.Rate) == true) &&
                (this.Bearer == null && other.Bearer == null ||
                 this.Bearer?.Equals(other.Bearer) == true) &&
                (this.Agent == null && other.Agent == null ||
                 this.Agent?.Equals(other.Agent) == true) &&
                (this.Tax == null && other.Tax == null ||
                 this.Tax?.Equals(other.Tax) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Amount = {(this.Amount == null ? "null" : this.Amount.ToString())}");
            toStringOutput.Add($"CreditDebitIndicator = {(this.CreditDebitIndicator == null ? "null" : this.CreditDebitIndicator.ToString())}");
            toStringOutput.Add($"ChargeIncludedIndicator = {(this.ChargeIncludedIndicator == null ? "null" : this.ChargeIncludedIndicator.ToString())}");
            toStringOutput.Add($"Type = {(this.Type == null ? "null" : this.Type.ToString())}");
            toStringOutput.Add($"Rate = {this.Rate ?? "null"}");
            toStringOutput.Add($"Bearer = {(this.Bearer == null ? "null" : this.Bearer.ToString())}");
            toStringOutput.Add($"Agent = {(this.Agent == null ? "null" : this.Agent.ToString())}");
            toStringOutput.Add($"Tax = {(this.Tax == null ? "null" : this.Tax.ToString())}");
        }
    }
}