// <copyright file="ChargeBearerTypeCodeEnum.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// ChargeBearerTypeCodeEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum ChargeBearerTypeCodeEnum
    {
        /// <summary>
        /// DEBT.
        /// </summary>
        [EnumMember(Value = "DEBT")]
        DEBT,

        /// <summary>
        /// CRED.
        /// </summary>
        [EnumMember(Value = "CRED")]
        CRED,

        /// <summary>
        /// SHAR.
        /// </summary>
        [EnumMember(Value = "SHAR")]
        SHAR,

        /// <summary>
        /// SLEV.
        /// </summary>
        [EnumMember(Value = "SLEV")]
        SLEV
    }
}