// <copyright file="Charges.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// Charges.
    /// </summary>
    public class Charges
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Charges"/> class.
        /// </summary>
        public Charges()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Charges"/> class.
        /// </summary>
        /// <param name="totalChargesAndTaxAmount">total_charges_and_tax_amount.</param>
        /// <param name="record">record.</param>
        public Charges(
            Models.TotalChargesAndTaxAmount totalChargesAndTaxAmount = null,
            List<Models.ChargesRecord> record = null)
        {
            this.TotalChargesAndTaxAmount = totalChargesAndTaxAmount;
            this.Record = record;
        }

        /// <summary>
        /// Gets or sets TotalChargesAndTaxAmount.
        /// </summary>
        [JsonProperty("total_charges_and_tax_amount", NullValueHandling = NullValueHandling.Ignore)]
        public Models.TotalChargesAndTaxAmount TotalChargesAndTaxAmount { get; set; }

        /// <summary>
        /// Provides details of the individual charges record.
        /// </summary>
        [JsonProperty("record", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.ChargesRecord> Record { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Charges : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is Charges other &&
                (this.TotalChargesAndTaxAmount == null && other.TotalChargesAndTaxAmount == null ||
                 this.TotalChargesAndTaxAmount?.Equals(other.TotalChargesAndTaxAmount) == true) &&
                (this.Record == null && other.Record == null ||
                 this.Record?.Equals(other.Record) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"TotalChargesAndTaxAmount = {(this.TotalChargesAndTaxAmount == null ? "null" : this.TotalChargesAndTaxAmount.ToString())}");
            toStringOutput.Add($"Record = {(this.Record == null ? "null" : $"[{string.Join(", ", this.Record)} ]")}");
        }
    }
}