// <copyright file="ClearingSystemIdentificationCode.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// ClearingSystemIdentificationCode.
    /// </summary>
    public class ClearingSystemIdentificationCode
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ClearingSystemIdentificationCode"/> class.
        /// </summary>
        public ClearingSystemIdentificationCode()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClearingSystemIdentificationCode"/> class.
        /// </summary>
        /// <param name="code">code.</param>
        public ClearingSystemIdentificationCode(
            string code)
        {
            this.Code = code;
        }

        /// <summary>
        /// Specifies the clearing system identification code, as published in an external clearing system identification code list. External code sets can be downloaded from www.iso20022.org.
        /// </summary>
        [JsonProperty("code")]
        public string Code { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ClearingSystemIdentificationCode : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ClearingSystemIdentificationCode other &&
                (this.Code == null && other.Code == null ||
                 this.Code?.Equals(other.Code) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Code = {this.Code ?? "null"}");
        }
    }
}