// <copyright file="ClearingSystemMemberIdentification2.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// ClearingSystemMemberIdentification2.
    /// </summary>
    public class ClearingSystemMemberIdentification2
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ClearingSystemMemberIdentification2"/> class.
        /// </summary>
        public ClearingSystemMemberIdentification2()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClearingSystemMemberIdentification2"/> class.
        /// </summary>
        /// <param name="memberIdentification">member_identification.</param>
        /// <param name="clearingSystemIdentification">clearing_system_identification.</param>
        public ClearingSystemMemberIdentification2(
            string memberIdentification,
            object clearingSystemIdentification = null)
        {
            this.ClearingSystemIdentification = clearingSystemIdentification;
            this.MemberIdentification = memberIdentification;
        }

        /// <summary>
        /// Gets or sets ClearingSystemIdentification.
        /// </summary>
        [JsonProperty("clearing_system_identification", NullValueHandling = NullValueHandling.Ignore)]
        public object ClearingSystemIdentification { get; set; }

        /// <summary>
        /// Identification of a member of a clearing system.
        /// </summary>
        [JsonProperty("member_identification")]
        public string MemberIdentification { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ClearingSystemMemberIdentification2 : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ClearingSystemMemberIdentification2 other &&
                (this.ClearingSystemIdentification == null && other.ClearingSystemIdentification == null ||
                 this.ClearingSystemIdentification?.Equals(other.ClearingSystemIdentification) == true) &&
                (this.MemberIdentification == null && other.MemberIdentification == null ||
                 this.MemberIdentification?.Equals(other.MemberIdentification) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ClearingSystemIdentification = {(this.ClearingSystemIdentification == null ? "null" : this.ClearingSystemIdentification.ToString())}");
            toStringOutput.Add($"MemberIdentification = {this.MemberIdentification ?? "null"}");
        }
    }
}