// <copyright file="CounterValueAmount.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// CounterValueAmount.
    /// </summary>
    public class CounterValueAmount
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CounterValueAmount"/> class.
        /// </summary>
        public CounterValueAmount()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CounterValueAmount"/> class.
        /// </summary>
        /// <param name="amount">amount.</param>
        /// <param name="currencyExchange">currency_exchange.</param>
        public CounterValueAmount(
            Models.Amount1 amount,
            Models.CurrencyExchange2 currencyExchange = null)
        {
            this.Amount = amount;
            this.CurrencyExchange = currencyExchange;
        }

        /// <summary>
        /// Gets or sets Amount.
        /// </summary>
        [JsonProperty("amount")]
        public Models.Amount1 Amount { get; set; }

        /// <summary>
        /// Gets or sets CurrencyExchange.
        /// </summary>
        [JsonProperty("currency_exchange", NullValueHandling = NullValueHandling.Ignore)]
        public Models.CurrencyExchange2 CurrencyExchange { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CounterValueAmount : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is CounterValueAmount other &&
                (this.Amount == null && other.Amount == null ||
                 this.Amount?.Equals(other.Amount) == true) &&
                (this.CurrencyExchange == null && other.CurrencyExchange == null ||
                 this.CurrencyExchange?.Equals(other.CurrencyExchange) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Amount = {(this.Amount == null ? "null" : this.Amount.ToString())}");
            toStringOutput.Add($"CurrencyExchange = {(this.CurrencyExchange == null ? "null" : this.CurrencyExchange.ToString())}");
        }
    }
}