// <copyright file="CreditLine.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// CreditLine.
    /// </summary>
    public class CreditLine
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreditLine"/> class.
        /// </summary>
        public CreditLine()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CreditLine"/> class.
        /// </summary>
        /// <param name="included">included.</param>
        /// <param name="type">type.</param>
        /// <param name="amount">amount.</param>
        public CreditLine(
            bool included,
            string type = null,
            Models.Amount1 amount = null)
        {
            this.Included = included;
            this.Type = type;
            this.Amount = amount;
        }

        /// <summary>
        /// Indicates whether or not the credit line is included in the balance.
        /// </summary>
        [JsonProperty("included")]
        public bool Included { get; set; }

        /// <summary>
        /// Specifies the external credit line type code in the format of character string with a maximum length of 4 characters. The list of valid codes is an external code set published separately. External code sets can be downloaded from www.iso20022.org.
        /// </summary>
        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or sets Amount.
        /// </summary>
        [JsonProperty("amount", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Amount1 Amount { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CreditLine : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is CreditLine other &&
                (this.Included.Equals(other.Included)) &&
                (this.Type == null && other.Type == null ||
                 this.Type?.Equals(other.Type) == true) &&
                (this.Amount == null && other.Amount == null ||
                 this.Amount?.Equals(other.Amount) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Included = {this.Included}");
            toStringOutput.Add($"Type = {this.Type ?? "null"}");
            toStringOutput.Add($"Amount = {(this.Amount == null ? "null" : this.Amount.ToString())}");
        }
    }
}