// <copyright file="CreditDebitCodeEnum.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// CreditDebitCodeEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum CreditDebitCodeEnum
    {
        /// <summary>
        /// CRDT.
        /// </summary>
        [EnumMember(Value = "CRDT")]
        CRDT,

        /// <summary>
        /// DBIT.
        /// </summary>
        [EnumMember(Value = "DBIT")]
        DBIT
    }
}