// <copyright file="CreditorReferenceCodeEnum.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// CreditorReferenceCodeEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum CreditorReferenceCodeEnum
    {
        /// <summary>
        /// DISP.
        /// </summary>
        [EnumMember(Value = "DISP")]
        DISP,

        /// <summary>
        /// FXDR.
        /// </summary>
        [EnumMember(Value = "FXDR")]
        FXDR,

        /// <summary>
        /// PUOR.
        /// </summary>
        [EnumMember(Value = "PUOR")]
        PUOR,

        /// <summary>
        /// RPIN.
        /// </summary>
        [EnumMember(Value = "RPIN")]
        RPIN,

        /// <summary>
        /// RADM.
        /// </summary>
        [EnumMember(Value = "RADM")]
        RADM,

        /// <summary>
        /// SCOR.
        /// </summary>
        [EnumMember(Value = "SCOR")]
        SCOR
    }
}