// <copyright file="CurrencyAmount.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// CurrencyAmount.
    /// </summary>
    public class CurrencyAmount
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CurrencyAmount"/> class.
        /// </summary>
        public CurrencyAmount()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CurrencyAmount"/> class.
        /// </summary>
        /// <param name="currencyCode">currency_code.</param>
        /// <param name="amount">amount.</param>
        public CurrencyAmount(
            string currencyCode,
            string amount)
        {
            this.CurrencyCode = currencyCode;
            this.Amount = amount;
        }

        /// <summary>
        /// ISO three character currency code.
        /// The Currency Code must be registered, or have already been registered. Valid active or historic currency codes are registered with the ISO 4217 Maintenance Agency, consist of three (3) contiguous letters, and may be or not be withdrawn on the day the message containing the Currency is exchanged.
        /// </summary>
        [JsonProperty("currency_code")]
        public string CurrencyCode { get; set; }

        /// <summary>
        /// The amount with fractional digit. The number of fractional digits (or minor unit of currency) must comply with ISO 4217.
        /// fractionDigits - 5
        /// totalDigits - 18
        /// *`Note:` The decimal separator is a dot.
        /// </summary>
        [JsonProperty("amount")]
        public string Amount { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CurrencyAmount : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is CurrencyAmount other &&
                (this.CurrencyCode == null && other.CurrencyCode == null ||
                 this.CurrencyCode?.Equals(other.CurrencyCode) == true) &&
                (this.Amount == null && other.Amount == null ||
                 this.Amount?.Equals(other.Amount) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"CurrencyCode = {this.CurrencyCode ?? "null"}");
            toStringOutput.Add($"Amount = {this.Amount ?? "null"}");
        }
    }
}