// <copyright file="CurrencyExchange2.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// CurrencyExchange2.
    /// </summary>
    public class CurrencyExchange2
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CurrencyExchange2"/> class.
        /// </summary>
        public CurrencyExchange2()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CurrencyExchange2"/> class.
        /// </summary>
        /// <param name="sourceCurrency">source_currency.</param>
        /// <param name="exchangeRate">exchange_rate.</param>
        /// <param name="targetCurrency">target_currency.</param>
        /// <param name="unitCurrency">unit_currency.</param>
        /// <param name="contractIdentification">contract_identification.</param>
        /// <param name="quotationDate">quotation_date.</param>
        public CurrencyExchange2(
            string sourceCurrency,
            string exchangeRate,
            string targetCurrency = null,
            string unitCurrency = null,
            string contractIdentification = null,
            string quotationDate = null)
        {
            this.SourceCurrency = sourceCurrency;
            this.TargetCurrency = targetCurrency;
            this.UnitCurrency = unitCurrency;
            this.ExchangeRate = exchangeRate;
            this.ContractIdentification = contractIdentification;
            this.QuotationDate = quotationDate;
        }

        /// <summary>
        /// Code allocated to a currency, by a maintenance agency, under an international identification scheme as described in the latest edition of the international standard ISO 4217 "Codes for the representation of currencies and funds". Valid currency codes are registered with the ISO 4217 Maintenance Agency, and consist of three contiguous letters.
        /// </summary>
        [JsonProperty("source_currency")]
        public string SourceCurrency { get; set; }

        /// <summary>
        /// Code allocated to a currency, by a maintenance agency, under an international identification scheme as described in the latest edition of the international standard ISO 4217 "Codes for the representation of currencies and funds". Valid currency codes are registered with the ISO 4217 Maintenance Agency, and consist of three contiguous letters.
        /// </summary>
        [JsonProperty("target_currency", NullValueHandling = NullValueHandling.Ignore)]
        public string TargetCurrency { get; set; }

        /// <summary>
        /// Code allocated to a currency, by a maintenance agency, under an international identification scheme as described in the latest edition of the international standard ISO 4217 "Codes for the representation of currencies and funds". Valid currency codes are registered with the ISO 4217 Maintenance Agency, and consist of three contiguous letters.
        /// </summary>
        [JsonProperty("unit_currency", NullValueHandling = NullValueHandling.Ignore)]
        public string UnitCurrency { get; set; }

        /// <summary>
        /// Rate expressed as a decimal, for example, 0.7 is 7/10 and 70%.
        /// </summary>
        [JsonProperty("exchange_rate")]
        public string ExchangeRate { get; set; }

        /// <summary>
        /// Unique identification to unambiguously identify the foreign exchange contract.
        /// </summary>
        [JsonProperty("contract_identification", NullValueHandling = NullValueHandling.Ignore)]
        public string ContractIdentification { get; set; }

        /// <summary>
        /// A particular point in the progression of time defined by a mandatory date and a mandatory time component, expressed in either UTC time format (YYYY-MM-DDThh:mm:ss.sssZ), local time with UTC offset format (YYYY-MM-DDThh:mm:ss.sss+/-hh:mm), or local time format (YYYY-MM-DDThh:mm:ss.sss). These representations are defined in "XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004" which is aligned with ISO 8601.
        /// Note on the time format:
        /// 1) beginning / end of calendar day
        /// 00:00:00 = the beginning of a calendar day
        /// 24:00:00 = the end of a calendar day
        /// 2) fractions of second in time format
        /// Decimal fractions of seconds may be included. In this case, the involved parties shall agree on the maximum number of digits that are allowed.
        /// </summary>
        [JsonProperty("quotation_date", NullValueHandling = NullValueHandling.Ignore)]
        public string QuotationDate { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CurrencyExchange2 : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is CurrencyExchange2 other &&
                (this.SourceCurrency == null && other.SourceCurrency == null ||
                 this.SourceCurrency?.Equals(other.SourceCurrency) == true) &&
                (this.TargetCurrency == null && other.TargetCurrency == null ||
                 this.TargetCurrency?.Equals(other.TargetCurrency) == true) &&
                (this.UnitCurrency == null && other.UnitCurrency == null ||
                 this.UnitCurrency?.Equals(other.UnitCurrency) == true) &&
                (this.ExchangeRate == null && other.ExchangeRate == null ||
                 this.ExchangeRate?.Equals(other.ExchangeRate) == true) &&
                (this.ContractIdentification == null && other.ContractIdentification == null ||
                 this.ContractIdentification?.Equals(other.ContractIdentification) == true) &&
                (this.QuotationDate == null && other.QuotationDate == null ||
                 this.QuotationDate?.Equals(other.QuotationDate) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"SourceCurrency = {this.SourceCurrency ?? "null"}");
            toStringOutput.Add($"TargetCurrency = {this.TargetCurrency ?? "null"}");
            toStringOutput.Add($"UnitCurrency = {this.UnitCurrency ?? "null"}");
            toStringOutput.Add($"ExchangeRate = {this.ExchangeRate ?? "null"}");
            toStringOutput.Add($"ContractIdentification = {this.ContractIdentification ?? "null"}");
            toStringOutput.Add($"QuotationDate = {this.QuotationDate ?? "null"}");
        }
    }
}