// <copyright file="Document.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// Document.
    /// </summary>
    public class Document
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Document"/> class.
        /// </summary>
        public Document()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Document"/> class.
        /// </summary>
        /// <param name="type">type.</param>
        /// <param name="number">number.</param>
        /// <param name="relatedDate">related_date.</param>
        /// <param name="lineDetails">line_details.</param>
        public Document(
            Models.Type1 type = null,
            string number = null,
            string relatedDate = null,
            List<Models.DocumentItem> lineDetails = null)
        {
            this.Type = type;
            this.Number = number;
            this.RelatedDate = relatedDate;
            this.LineDetails = lineDetails;
        }

        /// <summary>
        /// Gets or sets Type.
        /// </summary>
        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Type1 Type { get; set; }

        /// <summary>
        /// Unique and unambiguous identification of the referred document.
        /// </summary>
        [JsonProperty("number", NullValueHandling = NullValueHandling.Ignore)]
        public string Number { get; set; }

        /// <summary>
        /// A particular point in the progression of time in a calendar year expressed in the YYYY-MM-DD format. This representation is defined in "XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004" which is aligned with ISO 8601.
        /// </summary>
        [JsonProperty("related_date", NullValueHandling = NullValueHandling.Ignore)]
        public string RelatedDate { get; set; }

        /// <summary>
        /// Set of elements used to provide the content of the referred document line.
        /// </summary>
        [JsonProperty("line_details", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.DocumentItem> LineDetails { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Document : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is Document other &&
                (this.Type == null && other.Type == null ||
                 this.Type?.Equals(other.Type) == true) &&
                (this.Number == null && other.Number == null ||
                 this.Number?.Equals(other.Number) == true) &&
                (this.RelatedDate == null && other.RelatedDate == null ||
                 this.RelatedDate?.Equals(other.RelatedDate) == true) &&
                (this.LineDetails == null && other.LineDetails == null ||
                 this.LineDetails?.Equals(other.LineDetails) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Type = {(this.Type == null ? "null" : this.Type.ToString())}");
            toStringOutput.Add($"Number = {this.Number ?? "null"}");
            toStringOutput.Add($"RelatedDate = {this.RelatedDate ?? "null"}");
            toStringOutput.Add($"LineDetails = {(this.LineDetails == null ? "null" : $"[{string.Join(", ", this.LineDetails)} ]")}");
        }
    }
}