// <copyright file="DocumentItem.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// DocumentItem.
    /// </summary>
    public class DocumentItem
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentItem"/> class.
        /// </summary>
        public DocumentItem()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentItem"/> class.
        /// </summary>
        /// <param name="identification">identification.</param>
        /// <param name="description">description.</param>
        /// <param name="amount">amount.</param>
        /// <param name="creditDebitIndicator">credit_debit_indicator.</param>
        /// <param name="adjustmentReason">adjustment_reason.</param>
        public DocumentItem(
            string identification,
            string description = null,
            Models.Amount1 amount = null,
            Models.CreditDebitCodeEnum? creditDebitIndicator = null,
            string adjustmentReason = null)
        {
            this.Identification = identification;
            this.Description = description;
            this.Amount = amount;
            this.CreditDebitIndicator = creditDebitIndicator;
            this.AdjustmentReason = adjustmentReason;
        }

        /// <summary>
        /// Provides identification of the document item line.
        /// </summary>
        [JsonProperty("identification")]
        public string Identification { get; set; }

        /// <summary>
        /// Description associated with the document item line.
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets Amount.
        /// </summary>
        [JsonProperty("amount", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Amount1 Amount { get; set; }

        /// <summary>
        /// Gets or sets CreditDebitIndicator.
        /// </summary>
        [JsonProperty("credit_debit_indicator", NullValueHandling = NullValueHandling.Ignore)]
        public Models.CreditDebitCodeEnum? CreditDebitIndicator { get; set; }

        /// <summary>
        /// Specifies the reason for the adjustment.
        /// </summary>
        [JsonProperty("adjustment_reason", NullValueHandling = NullValueHandling.Ignore)]
        public string AdjustmentReason { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"DocumentItem : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is DocumentItem other &&
                (this.Identification == null && other.Identification == null ||
                 this.Identification?.Equals(other.Identification) == true) &&
                (this.Description == null && other.Description == null ||
                 this.Description?.Equals(other.Description) == true) &&
                (this.Amount == null && other.Amount == null ||
                 this.Amount?.Equals(other.Amount) == true) &&
                (this.CreditDebitIndicator == null && other.CreditDebitIndicator == null ||
                 this.CreditDebitIndicator?.Equals(other.CreditDebitIndicator) == true) &&
                (this.AdjustmentReason == null && other.AdjustmentReason == null ||
                 this.AdjustmentReason?.Equals(other.AdjustmentReason) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Identification = {this.Identification ?? "null"}");
            toStringOutput.Add($"Description = {this.Description ?? "null"}");
            toStringOutput.Add($"Amount = {(this.Amount == null ? "null" : this.Amount.ToString())}");
            toStringOutput.Add($"CreditDebitIndicator = {(this.CreditDebitIndicator == null ? "null" : this.CreditDebitIndicator.ToString())}");
            toStringOutput.Add($"AdjustmentReason = {this.AdjustmentReason ?? "null"}");
        }
    }
}