// <copyright file="DocumentTypeCodeEnum.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// DocumentTypeCodeEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum DocumentTypeCodeEnum
    {
        /// <summary>
        /// MSIN.
        /// </summary>
        [EnumMember(Value = "MSIN")]
        MSIN,

        /// <summary>
        /// CNFA.
        /// </summary>
        [EnumMember(Value = "CNFA")]
        CNFA,

        /// <summary>
        /// DNFA.
        /// </summary>
        [EnumMember(Value = "DNFA")]
        DNFA,

        /// <summary>
        /// CINV.
        /// </summary>
        [EnumMember(Value = "CINV")]
        CINV,

        /// <summary>
        /// CREN.
        /// </summary>
        [EnumMember(Value = "CREN")]
        CREN,

        /// <summary>
        /// DEBN.
        /// </summary>
        [EnumMember(Value = "DEBN")]
        DEBN,

        /// <summary>
        /// HIRI.
        /// </summary>
        [EnumMember(Value = "HIRI")]
        HIRI,

        /// <summary>
        /// SBIN.
        /// </summary>
        [EnumMember(Value = "SBIN")]
        SBIN,

        /// <summary>
        /// CMCN.
        /// </summary>
        [EnumMember(Value = "CMCN")]
        CMCN,

        /// <summary>
        /// SOAC.
        /// </summary>
        [EnumMember(Value = "SOAC")]
        SOAC,

        /// <summary>
        /// DISP.
        /// </summary>
        [EnumMember(Value = "DISP")]
        DISP,

        /// <summary>
        /// BOLD.
        /// </summary>
        [EnumMember(Value = "BOLD")]
        BOLD,

        /// <summary>
        /// VCHR.
        /// </summary>
        [EnumMember(Value = "VCHR")]
        VCHR,

        /// <summary>
        /// AROI.
        /// </summary>
        [EnumMember(Value = "AROI")]
        AROI,

        /// <summary>
        /// TSUT.
        /// </summary>
        [EnumMember(Value = "TSUT")]
        TSUT,

        /// <summary>
        /// PUOR.
        /// </summary>
        [EnumMember(Value = "PUOR")]
        PUOR
    }
}