// <copyright file="FromToAmountRange.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// FromToAmountRange.
    /// </summary>
    public class FromToAmountRange
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FromToAmountRange"/> class.
        /// </summary>
        public FromToAmountRange()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FromToAmountRange"/> class.
        /// </summary>
        /// <param name="fromAmount">from_amount.</param>
        /// <param name="toAmount">to_amount.</param>
        public FromToAmountRange(
            Models.FromAmount fromAmount,
            Models.ToAmount toAmount)
        {
            this.FromAmount = fromAmount;
            this.ToAmount = toAmount;
        }

        /// <summary>
        /// Gets or sets FromAmount.
        /// </summary>
        [JsonProperty("from_amount")]
        public Models.FromAmount FromAmount { get; set; }

        /// <summary>
        /// Gets or sets ToAmount.
        /// </summary>
        [JsonProperty("to_amount")]
        public Models.ToAmount ToAmount { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"FromToAmountRange : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is FromToAmountRange other &&
                (this.FromAmount == null && other.FromAmount == null ||
                 this.FromAmount?.Equals(other.FromAmount) == true) &&
                (this.ToAmount == null && other.ToAmount == null ||
                 this.ToAmount?.Equals(other.ToAmount) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"FromAmount = {(this.FromAmount == null ? "null" : this.FromAmount.ToString())}");
            toStringOutput.Add($"ToAmount = {(this.ToAmount == null ? "null" : this.ToAmount.ToString())}");
        }
    }
}