// <copyright file="ImpliedCurrencyAmountRangeEqual.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// ImpliedCurrencyAmountRangeEqual.
    /// </summary>
    public class ImpliedCurrencyAmountRangeEqual
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ImpliedCurrencyAmountRangeEqual"/> class.
        /// </summary>
        public ImpliedCurrencyAmountRangeEqual()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ImpliedCurrencyAmountRangeEqual"/> class.
        /// </summary>
        /// <param name="equalAmount">equal_amount.</param>
        public ImpliedCurrencyAmountRangeEqual(
            string equalAmount)
        {
            this.EqualAmount = equalAmount;
        }

        /// <summary>
        /// Number of monetary units specified in a currency where the unit of currency is implied by the context and compliant with ISO 4217. The decimal separator is a dot.
        /// Note: a zero amount is considered a positive amount.
        /// </summary>
        [JsonProperty("equal_amount")]
        public string EqualAmount { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ImpliedCurrencyAmountRangeEqual : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ImpliedCurrencyAmountRangeEqual other &&
                (this.EqualAmount == null && other.EqualAmount == null ||
                 this.EqualAmount?.Equals(other.EqualAmount) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"EqualAmount = {this.EqualAmount ?? "null"}");
        }
    }
}