// <copyright file="ImpliedCurrencyAmountRangeTo.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// ImpliedCurrencyAmountRangeTo.
    /// </summary>
    public class ImpliedCurrencyAmountRangeTo
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ImpliedCurrencyAmountRangeTo"/> class.
        /// </summary>
        public ImpliedCurrencyAmountRangeTo()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ImpliedCurrencyAmountRangeTo"/> class.
        /// </summary>
        /// <param name="toAmount">to_amount.</param>
        public ImpliedCurrencyAmountRangeTo(
            Models.ToAmount toAmount)
        {
            this.ToAmount = toAmount;
        }

        /// <summary>
        /// Gets or sets ToAmount.
        /// </summary>
        [JsonProperty("to_amount")]
        public Models.ToAmount ToAmount { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ImpliedCurrencyAmountRangeTo : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ImpliedCurrencyAmountRangeTo other &&
                (this.ToAmount == null && other.ToAmount == null ||
                 this.ToAmount?.Equals(other.ToAmount) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ToAmount = {(this.ToAmount == null ? "null" : this.ToAmount.ToString())}");
        }
    }
}