// <copyright file="ImpliedCurrencyAmountRangeNotEqual.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// ImpliedCurrencyAmountRangeNotEqual.
    /// </summary>
    public class ImpliedCurrencyAmountRangeNotEqual
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ImpliedCurrencyAmountRangeNotEqual"/> class.
        /// </summary>
        public ImpliedCurrencyAmountRangeNotEqual()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ImpliedCurrencyAmountRangeNotEqual"/> class.
        /// </summary>
        /// <param name="notEqualAmount">not_equal_amount.</param>
        public ImpliedCurrencyAmountRangeNotEqual(
            string notEqualAmount)
        {
            this.NotEqualAmount = notEqualAmount;
        }

        /// <summary>
        /// Number of monetary units specified in a currency where the unit of currency is implied by the context and compliant with ISO 4217. The decimal separator is a dot.
        /// Note: a zero amount is considered a positive amount.
        /// </summary>
        [JsonProperty("not_equal_amount")]
        public string NotEqualAmount { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ImpliedCurrencyAmountRangeNotEqual : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ImpliedCurrencyAmountRangeNotEqual other &&
                (this.NotEqualAmount == null && other.NotEqualAmount == null ||
                 this.NotEqualAmount?.Equals(other.NotEqualAmount) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"NotEqualAmount = {this.NotEqualAmount ?? "null"}");
        }
    }
}