// <copyright file="ImpliedCurrencyAmountRangeFromTo.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// ImpliedCurrencyAmountRangeFromTo.
    /// </summary>
    public class ImpliedCurrencyAmountRangeFromTo
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ImpliedCurrencyAmountRangeFromTo"/> class.
        /// </summary>
        public ImpliedCurrencyAmountRangeFromTo()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ImpliedCurrencyAmountRangeFromTo"/> class.
        /// </summary>
        /// <param name="fromToAmount">from_to_amount.</param>
        public ImpliedCurrencyAmountRangeFromTo(
            Models.FromToAmount fromToAmount)
        {
            this.FromToAmount = fromToAmount;
        }

        /// <summary>
        /// Gets or sets FromToAmount.
        /// </summary>
        [JsonProperty("from_to_amount")]
        public Models.FromToAmount FromToAmount { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ImpliedCurrencyAmountRangeFromTo : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ImpliedCurrencyAmountRangeFromTo other &&
                (this.FromToAmount == null && other.FromToAmount == null ||
                 this.FromToAmount?.Equals(other.FromToAmount) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"FromToAmount = {(this.FromToAmount == null ? "null" : this.FromToAmount.ToString())}");
        }
    }
}