// <copyright file="ImpliedCurrencyAmountRangeFrom.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// ImpliedCurrencyAmountRangeFrom.
    /// </summary>
    public class ImpliedCurrencyAmountRangeFrom
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ImpliedCurrencyAmountRangeFrom"/> class.
        /// </summary>
        public ImpliedCurrencyAmountRangeFrom()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ImpliedCurrencyAmountRangeFrom"/> class.
        /// </summary>
        /// <param name="fromAmount">from_amount.</param>
        public ImpliedCurrencyAmountRangeFrom(
            Models.FromAmount fromAmount)
        {
            this.FromAmount = fromAmount;
        }

        /// <summary>
        /// Gets or sets FromAmount.
        /// </summary>
        [JsonProperty("from_amount")]
        public Models.FromAmount FromAmount { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ImpliedCurrencyAmountRangeFrom : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ImpliedCurrencyAmountRangeFrom other &&
                (this.FromAmount == null && other.FromAmount == null ||
                 this.FromAmount?.Equals(other.FromAmount) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"FromAmount = {(this.FromAmount == null ? "null" : this.FromAmount.ToString())}");
        }
    }
}