// <copyright file="InterestTypeCodeEnum.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// InterestTypeCodeEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum InterestTypeCodeEnum
    {
        /// <summary>
        /// INDY.
        /// </summary>
        [EnumMember(Value = "INDY")]
        INDY,

        /// <summary>
        /// OVRN.
        /// </summary>
        [EnumMember(Value = "OVRN")]
        OVRN
    }
}