// <copyright file="IntermediaryAgent1.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// IntermediaryAgent1.
    /// </summary>
    public class IntermediaryAgent1
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IntermediaryAgent1"/> class.
        /// </summary>
        public IntermediaryAgent1()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IntermediaryAgent1"/> class.
        /// </summary>
        /// <param name="financialInstitutionIdentification">financial_institution_identification.</param>
        /// <param name="branchIdentification">branch_identification.</param>
        public IntermediaryAgent1(
            Models.FinancialInstitutionIdentification2 financialInstitutionIdentification,
            Models.BranchIdentification2 branchIdentification = null)
        {
            this.FinancialInstitutionIdentification = financialInstitutionIdentification;
            this.BranchIdentification = branchIdentification;
        }

        /// <summary>
        /// Gets or sets FinancialInstitutionIdentification.
        /// </summary>
        [JsonProperty("financial_institution_identification")]
        public Models.FinancialInstitutionIdentification2 FinancialInstitutionIdentification { get; set; }

        /// <summary>
        /// Gets or sets BranchIdentification.
        /// </summary>
        [JsonProperty("branch_identification", NullValueHandling = NullValueHandling.Ignore)]
        public Models.BranchIdentification2 BranchIdentification { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"IntermediaryAgent1 : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is IntermediaryAgent1 other &&
                (this.FinancialInstitutionIdentification == null && other.FinancialInstitutionIdentification == null ||
                 this.FinancialInstitutionIdentification?.Equals(other.FinancialInstitutionIdentification) == true) &&
                (this.BranchIdentification == null && other.BranchIdentification == null ||
                 this.BranchIdentification?.Equals(other.BranchIdentification) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"FinancialInstitutionIdentification = {(this.FinancialInstitutionIdentification == null ? "null" : this.FinancialInstitutionIdentification.ToString())}");
            toStringOutput.Add($"BranchIdentification = {(this.BranchIdentification == null ? "null" : this.BranchIdentification.ToString())}");
        }
    }
}