// <copyright file="NumberAndSumOfTransactions5.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// NumberAndSumOfTransactions5.
    /// </summary>
    public class NumberAndSumOfTransactions5
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NumberAndSumOfTransactions5"/> class.
        /// </summary>
        public NumberAndSumOfTransactions5()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NumberAndSumOfTransactions5"/> class.
        /// </summary>
        /// <param name="numberOfEntries">number_of_entries.</param>
        /// <param name="totalNetEntry">total_net_entry.</param>
        public NumberAndSumOfTransactions5(
            string numberOfEntries,
            Models.TotalNetEntry totalNetEntry)
        {
            this.NumberOfEntries = numberOfEntries;
            this.TotalNetEntry = totalNetEntry;
        }

        /// <summary>
        /// Specifies a numeric string with a maximum length of 15 digits.
        /// </summary>
        [JsonProperty("number_of_entries")]
        public string NumberOfEntries { get; set; }

        /// <summary>
        /// Gets or sets TotalNetEntry.
        /// </summary>
        [JsonProperty("total_net_entry")]
        public Models.TotalNetEntry TotalNetEntry { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"NumberAndSumOfTransactions5 : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is NumberAndSumOfTransactions5 other &&
                (this.NumberOfEntries == null && other.NumberOfEntries == null ||
                 this.NumberOfEntries?.Equals(other.NumberOfEntries) == true) &&
                (this.TotalNetEntry == null && other.TotalNetEntry == null ||
                 this.TotalNetEntry?.Equals(other.TotalNetEntry) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"NumberOfEntries = {this.NumberOfEntries ?? "null"}");
            toStringOutput.Add($"TotalNetEntry = {(this.TotalNetEntry == null ? "null" : this.TotalNetEntry.ToString())}");
        }
    }
}