// <copyright file="OrganisationPartyIdentification.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// OrganisationPartyIdentification.
    /// </summary>
    public class OrganisationPartyIdentification
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrganisationPartyIdentification"/> class.
        /// </summary>
        public OrganisationPartyIdentification()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OrganisationPartyIdentification"/> class.
        /// </summary>
        /// <param name="organisationIdentification">organisation_identification.</param>
        public OrganisationPartyIdentification(
            Models.OrganisationIdentification1 organisationIdentification)
        {
            this.OrganisationIdentification = organisationIdentification;
        }

        /// <summary>
        /// Gets or sets OrganisationIdentification.
        /// </summary>
        [JsonProperty("organisation_identification")]
        public Models.OrganisationIdentification1 OrganisationIdentification { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"OrganisationPartyIdentification : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is OrganisationPartyIdentification other &&
                (this.OrganisationIdentification == null && other.OrganisationIdentification == null ||
                 this.OrganisationIdentification?.Equals(other.OrganisationIdentification) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"OrganisationIdentification = {(this.OrganisationIdentification == null ? "null" : this.OrganisationIdentification.ToString())}");
        }
    }
}