// <copyright file="PaymentReturnReason.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// PaymentReturnReason.
    /// </summary>
    public class PaymentReturnReason
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentReturnReason"/> class.
        /// </summary>
        public PaymentReturnReason()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentReturnReason"/> class.
        /// </summary>
        /// <param name="originalTransactionIdentification">original_transaction_identification.</param>
        /// <param name="reason">reason.</param>
        /// <param name="additionalInformation">additional_information.</param>
        public PaymentReturnReason(
            string originalTransactionIdentification = null,
            object reason = null,
            string additionalInformation = null)
        {
            this.OriginalTransactionIdentification = originalTransactionIdentification;
            this.Reason = reason;
            this.AdditionalInformation = additionalInformation;
        }

        /// <summary>
        /// Specify the original statement entry reference (transaction_identification) as specified in the previous statement.
        /// </summary>
        [JsonProperty("original_transaction_identification", NullValueHandling = NullValueHandling.Ignore)]
        public string OriginalTransactionIdentification { get; set; }

        /// <summary>
        /// Gets or sets Reason.
        /// </summary>
        [JsonProperty("reason", NullValueHandling = NullValueHandling.Ignore)]
        public object Reason { get; set; }

        /// <summary>
        /// Further details on the return reason.
        /// </summary>
        [JsonProperty("additional_information", NullValueHandling = NullValueHandling.Ignore)]
        public string AdditionalInformation { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"PaymentReturnReason : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is PaymentReturnReason other &&
                (this.OriginalTransactionIdentification == null && other.OriginalTransactionIdentification == null ||
                 this.OriginalTransactionIdentification?.Equals(other.OriginalTransactionIdentification) == true) &&
                (this.Reason == null && other.Reason == null ||
                 this.Reason?.Equals(other.Reason) == true) &&
                (this.AdditionalInformation == null && other.AdditionalInformation == null ||
                 this.AdditionalInformation?.Equals(other.AdditionalInformation) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"OriginalTransactionIdentification = {this.OriginalTransactionIdentification ?? "null"}");
            toStringOutput.Add($"Reason = {(this.Reason == null ? "null" : this.Reason.ToString())}");
            toStringOutput.Add($"AdditionalInformation = {this.AdditionalInformation ?? "null"}");
        }
    }
}