// <copyright file="PersonIdentificationSchemeNameProprietary.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// PersonIdentificationSchemeNameProprietary.
    /// </summary>
    public class PersonIdentificationSchemeNameProprietary
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PersonIdentificationSchemeNameProprietary"/> class.
        /// </summary>
        public PersonIdentificationSchemeNameProprietary()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PersonIdentificationSchemeNameProprietary"/> class.
        /// </summary>
        /// <param name="proprietary">proprietary.</param>
        public PersonIdentificationSchemeNameProprietary(
            string proprietary)
        {
            this.Proprietary = proprietary;
        }

        /// <summary>
        /// Specifies a character string with a maximum length of 35 characters.
        /// </summary>
        [JsonProperty("proprietary")]
        public string Proprietary { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"PersonIdentificationSchemeNameProprietary : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is PersonIdentificationSchemeNameProprietary other &&
                (this.Proprietary == null && other.Proprietary == null ||
                 this.Proprietary?.Equals(other.Proprietary) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Proprietary = {this.Proprietary ?? "null"}");
        }
    }
}