// <copyright file="PostalAddress.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// PostalAddress.
    /// </summary>
    public class PostalAddress
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostalAddress"/> class.
        /// </summary>
        public PostalAddress()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PostalAddress"/> class.
        /// </summary>
        /// <param name="townName">town_name.</param>
        /// <param name="country">country.</param>
        /// <param name="department">department.</param>
        /// <param name="subDepartment">sub_department.</param>
        /// <param name="streetName">street_name.</param>
        /// <param name="buildingNumber">building_number.</param>
        /// <param name="buildingName">building_name.</param>
        /// <param name="floor">floor.</param>
        /// <param name="postBox">post_box.</param>
        /// <param name="room">room.</param>
        /// <param name="postCode">post_code.</param>
        /// <param name="townLocationName">town_location_name.</param>
        /// <param name="districtName">district_name.</param>
        /// <param name="countrySubDivision">country_sub_division.</param>
        public PostalAddress(
            string townName,
            string country,
            string department = null,
            string subDepartment = null,
            string streetName = null,
            string buildingNumber = null,
            string buildingName = null,
            string floor = null,
            string postBox = null,
            string room = null,
            string postCode = null,
            string townLocationName = null,
            string districtName = null,
            string countrySubDivision = null)
        {
            this.Department = department;
            this.SubDepartment = subDepartment;
            this.StreetName = streetName;
            this.BuildingNumber = buildingNumber;
            this.BuildingName = buildingName;
            this.Floor = floor;
            this.PostBox = postBox;
            this.Room = room;
            this.PostCode = postCode;
            this.TownName = townName;
            this.TownLocationName = townLocationName;
            this.DistrictName = districtName;
            this.CountrySubDivision = countrySubDivision;
            this.Country = country;
        }

        /// <summary>
        /// Identification of a division of a large organisation or building.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("department", NullValueHandling = NullValueHandling.Ignore)]
        public string Department { get; set; }

        /// <summary>
        /// Identification of a sub-division of a large organisation or building.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("sub_department", NullValueHandling = NullValueHandling.Ignore)]
        public string SubDepartment { get; set; }

        /// <summary>
        /// Name of a street or thoroughfare.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("street_name", NullValueHandling = NullValueHandling.Ignore)]
        public string StreetName { get; set; }

        /// <summary>
        /// Number that identifies the position of a building on a street.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("building_number", NullValueHandling = NullValueHandling.Ignore)]
        public string BuildingNumber { get; set; }

        /// <summary>
        /// Name of the building or house.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("building_name", NullValueHandling = NullValueHandling.Ignore)]
        public string BuildingName { get; set; }

        /// <summary>
        /// Floor or storey within a building.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("floor", NullValueHandling = NullValueHandling.Ignore)]
        public string Floor { get; set; }

        /// <summary>
        /// Numbered box in a post office, assigned to a person or organisation, where letters are kept until called for.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("post_box", NullValueHandling = NullValueHandling.Ignore)]
        public string PostBox { get; set; }

        /// <summary>
        /// Building room number.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("room", NullValueHandling = NullValueHandling.Ignore)]
        public string Room { get; set; }

        /// <summary>
        /// Identifier consisting of a group of letters and/or numbers that is added to a postal address to assist the sorting of mail.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("post_code", NullValueHandling = NullValueHandling.Ignore)]
        public string PostCode { get; set; }

        /// <summary>
        /// Name of a built-up area, with defined boundaries, and a local government.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("town_name")]
        [JsonRequired]
        public string TownName { get; set; }

        /// <summary>
        /// Specific location name within the town.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("town_location_name", NullValueHandling = NullValueHandling.Ignore)]
        public string TownLocationName { get; set; }

        /// <summary>
        /// Identifies a subdivision within a country sub-division.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("district_name", NullValueHandling = NullValueHandling.Ignore)]
        public string DistrictName { get; set; }

        /// <summary>
        /// Identifies a subdivision of a country such as state, region, county.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("country_sub_division", NullValueHandling = NullValueHandling.Ignore)]
        public string CountrySubDivision { get; set; }

        /// <summary>
        /// Nation with its own government.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("country")]
        [JsonRequired]
        public string Country { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"PostalAddress : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is PostalAddress other &&
                (this.Department == null && other.Department == null ||
                 this.Department?.Equals(other.Department) == true) &&
                (this.SubDepartment == null && other.SubDepartment == null ||
                 this.SubDepartment?.Equals(other.SubDepartment) == true) &&
                (this.StreetName == null && other.StreetName == null ||
                 this.StreetName?.Equals(other.StreetName) == true) &&
                (this.BuildingNumber == null && other.BuildingNumber == null ||
                 this.BuildingNumber?.Equals(other.BuildingNumber) == true) &&
                (this.BuildingName == null && other.BuildingName == null ||
                 this.BuildingName?.Equals(other.BuildingName) == true) &&
                (this.Floor == null && other.Floor == null ||
                 this.Floor?.Equals(other.Floor) == true) &&
                (this.PostBox == null && other.PostBox == null ||
                 this.PostBox?.Equals(other.PostBox) == true) &&
                (this.Room == null && other.Room == null ||
                 this.Room?.Equals(other.Room) == true) &&
                (this.PostCode == null && other.PostCode == null ||
                 this.PostCode?.Equals(other.PostCode) == true) &&
                (this.TownName == null && other.TownName == null ||
                 this.TownName?.Equals(other.TownName) == true) &&
                (this.TownLocationName == null && other.TownLocationName == null ||
                 this.TownLocationName?.Equals(other.TownLocationName) == true) &&
                (this.DistrictName == null && other.DistrictName == null ||
                 this.DistrictName?.Equals(other.DistrictName) == true) &&
                (this.CountrySubDivision == null && other.CountrySubDivision == null ||
                 this.CountrySubDivision?.Equals(other.CountrySubDivision) == true) &&
                (this.Country == null && other.Country == null ||
                 this.Country?.Equals(other.Country) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Department = {this.Department ?? "null"}");
            toStringOutput.Add($"SubDepartment = {this.SubDepartment ?? "null"}");
            toStringOutput.Add($"StreetName = {this.StreetName ?? "null"}");
            toStringOutput.Add($"BuildingNumber = {this.BuildingNumber ?? "null"}");
            toStringOutput.Add($"BuildingName = {this.BuildingName ?? "null"}");
            toStringOutput.Add($"Floor = {this.Floor ?? "null"}");
            toStringOutput.Add($"PostBox = {this.PostBox ?? "null"}");
            toStringOutput.Add($"Room = {this.Room ?? "null"}");
            toStringOutput.Add($"PostCode = {this.PostCode ?? "null"}");
            toStringOutput.Add($"TownName = {this.TownName ?? "null"}");
            toStringOutput.Add($"TownLocationName = {this.TownLocationName ?? "null"}");
            toStringOutput.Add($"DistrictName = {this.DistrictName ?? "null"}");
            toStringOutput.Add($"CountrySubDivision = {this.CountrySubDivision ?? "null"}");
            toStringOutput.Add($"Country = {this.Country ?? "null"}");
        }
    }
}