// <copyright file="PostalAddressUnstructured.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// PostalAddressUnstructured.
    /// </summary>
    public class PostalAddressUnstructured
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostalAddressUnstructured"/> class.
        /// </summary>
        public PostalAddressUnstructured()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PostalAddressUnstructured"/> class.
        /// </summary>
        /// <param name="addressLine">address_line.</param>
        /// <param name="country">country.</param>
        public PostalAddressUnstructured(
            string addressLine,
            string country = null)
        {
            this.AddressLine = addressLine;
            this.Country = country;
        }

        /// <summary>
        /// Information that locates and identifies a specific address, as defined by postal services, presented in free format text.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("address_line")]
        [JsonRequired]
        public string AddressLine { get; set; }

        /// <summary>
        /// Specify the country code.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("country", NullValueHandling = NullValueHandling.Ignore)]
        public string Country { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"PostalAddressUnstructured : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is PostalAddressUnstructured other &&
                (this.AddressLine == null && other.AddressLine == null ||
                 this.AddressLine?.Equals(other.AddressLine) == true) &&
                (this.Country == null && other.Country == null ||
                 this.Country?.Equals(other.Country) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AddressLine = {this.AddressLine ?? "null"}");
            toStringOutput.Add($"Country = {this.Country ?? "null"}");
        }
    }
}