// <copyright file="PrivatePartyIdentification.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// PrivatePartyIdentification.
    /// </summary>
    public class PrivatePartyIdentification
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PrivatePartyIdentification"/> class.
        /// </summary>
        public PrivatePartyIdentification()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PrivatePartyIdentification"/> class.
        /// </summary>
        /// <param name="privateIdentification">private_identification.</param>
        public PrivatePartyIdentification(
            Models.PrivateIdentification privateIdentification)
        {
            this.PrivateIdentification = privateIdentification;
        }

        /// <summary>
        /// Gets or sets PrivateIdentification.
        /// </summary>
        [JsonProperty("private_identification")]
        public Models.PrivateIdentification PrivateIdentification { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"PrivatePartyIdentification : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is PrivatePartyIdentification other &&
                (this.PrivateIdentification == null && other.PrivateIdentification == null ||
                 this.PrivateIdentification?.Equals(other.PrivateIdentification) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"PrivateIdentification = {(this.PrivateIdentification == null ? "null" : this.PrivateIdentification.ToString())}");
        }
    }
}