// <copyright file="PrivateIdentification.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// PrivateIdentification.
    /// </summary>
    public class PrivateIdentification
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PrivateIdentification"/> class.
        /// </summary>
        public PrivateIdentification()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PrivateIdentification"/> class.
        /// </summary>
        /// <param name="dateAndPlaceOfBirth">date_and_place_of_birth.</param>
        /// <param name="other">other.</param>
        public PrivateIdentification(
            Models.DateAndPlaceOfBirth1 dateAndPlaceOfBirth = null,
            List<Models.GenericPersonIdentification> other = null)
        {
            this.DateAndPlaceOfBirth = dateAndPlaceOfBirth;
            this.Other = other;
        }

        /// <summary>
        /// Gets or sets DateAndPlaceOfBirth.
        /// </summary>
        [JsonProperty("date_and_place_of_birth", NullValueHandling = NullValueHandling.Ignore)]
        public Models.DateAndPlaceOfBirth1 DateAndPlaceOfBirth { get; set; }

        /// <summary>
        /// Unique identification of a person, as assigned by an institution, using an identification scheme.
        /// </summary>
        [JsonProperty("other", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.GenericPersonIdentification> Other { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"PrivateIdentification : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is PrivateIdentification other &&
                (this.DateAndPlaceOfBirth == null && other.DateAndPlaceOfBirth == null ||
                 this.DateAndPlaceOfBirth?.Equals(other.DateAndPlaceOfBirth) == true) &&
                (this.Other == null && other.Other == null ||
                 this.Other?.Equals(other.Other) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"DateAndPlaceOfBirth = {(this.DateAndPlaceOfBirth == null ? "null" : this.DateAndPlaceOfBirth.ToString())}");
            toStringOutput.Add($"Other = {(this.Other == null ? "null" : $"[{string.Join(", ", this.Other)} ]")}");
        }
    }
}