// <copyright file="RateTypeOther.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// RateTypeOther.
    /// </summary>
    public class RateTypeOther
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RateTypeOther"/> class.
        /// </summary>
        public RateTypeOther()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RateTypeOther"/> class.
        /// </summary>
        /// <param name="other">other.</param>
        public RateTypeOther(
            string other)
        {
            this.Other = other;
        }

        /// <summary>
        /// Rate type expressed, in another form.
        /// </summary>
        [JsonProperty("other")]
        public string Other { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"RateTypeOther : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is RateTypeOther other &&
                (this.Other == null && other.Other == null ||
                 this.Other?.Equals(other.Other) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Other = {this.Other ?? "null"}");
        }
    }
}