// <copyright file="RateTypePercentage.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// RateTypePercentage.
    /// </summary>
    public class RateTypePercentage
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RateTypePercentage"/> class.
        /// </summary>
        public RateTypePercentage()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RateTypePercentage"/> class.
        /// </summary>
        /// <param name="percentage">percentage.</param>
        public RateTypePercentage(
            string percentage)
        {
            this.Percentage = percentage;
        }

        /// <summary>
        /// Rate expressed as a percentage, that is, in hundredths, for example, 0.7 is 7/10 of a percent, and 7.0 is 7%.
        /// </summary>
        [JsonProperty("percentage")]
        public string Percentage { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"RateTypePercentage : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is RateTypePercentage other &&
                (this.Percentage == null && other.Percentage == null ||
                 this.Percentage?.Equals(other.Percentage) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Percentage = {this.Percentage ?? "null"}");
        }
    }
}