// <copyright file="References.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// References.
    /// </summary>
    public class References
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="References"/> class.
        /// </summary>
        public References()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="References"/> class.
        /// </summary>
        /// <param name="messageIdentification">message_identification.</param>
        /// <param name="accountServicerReference">account_servicer_reference.</param>
        /// <param name="paymentInformationIdentification">payment_information_identification.</param>
        /// <param name="instructionIdentification">instruction_identification.</param>
        /// <param name="endToEndIdentification">end_to_end_identification.</param>
        /// <param name="uetr">uetr.</param>
        /// <param name="transactionIdentification">transaction_identification.</param>
        /// <param name="mandateIdentification">mandate_identification.</param>
        /// <param name="chequeNumber">cheque_number.</param>
        /// <param name="clearingSystemReference">clearing_system_reference.</param>
        public References(
            string messageIdentification = null,
            string accountServicerReference = null,
            string paymentInformationIdentification = null,
            string instructionIdentification = null,
            string endToEndIdentification = null,
            Guid? uetr = null,
            string transactionIdentification = null,
            string mandateIdentification = null,
            string chequeNumber = null,
            string clearingSystemReference = null)
        {
            this.MessageIdentification = messageIdentification;
            this.AccountServicerReference = accountServicerReference;
            this.PaymentInformationIdentification = paymentInformationIdentification;
            this.InstructionIdentification = instructionIdentification;
            this.EndToEndIdentification = endToEndIdentification;
            this.Uetr = uetr;
            this.TransactionIdentification = transactionIdentification;
            this.MandateIdentification = mandateIdentification;
            this.ChequeNumber = chequeNumber;
            this.ClearingSystemReference = clearingSystemReference;
        }

        /// <summary>
        /// Point to point reference, as assigned by the instructing party of the underlying message.
        /// </summary>
        [JsonProperty("message_identification", NullValueHandling = NullValueHandling.Ignore)]
        public string MessageIdentification { get; set; }

        /// <summary>
        /// Unique reference, as assigned by the account servicing institution, to unambiguously identify the instruction.
        /// </summary>
        [JsonProperty("account_servicer_reference", NullValueHandling = NullValueHandling.Ignore)]
        public string AccountServicerReference { get; set; }

        /// <summary>
        /// Unique identification, as assigned by a sending party, to unambiguously identify the payment information group within the message.
        /// </summary>
        [JsonProperty("payment_information_identification", NullValueHandling = NullValueHandling.Ignore)]
        public string PaymentInformationIdentification { get; set; }

        /// <summary>
        /// Unique identification, as assigned by an instructing party for an instructed party, to unambiguously identify the instruction.  Usage: The instruction identification is a point to point reference that can be used between the instructing party and the instructed party to refer to the individual instruction. It can be included in several messages related to the instruction.
        /// </summary>
        [JsonProperty("instruction_identification", NullValueHandling = NullValueHandling.Ignore)]
        public string InstructionIdentification { get; set; }

        /// <summary>
        /// Unique identification, as assigned by the initiating party, to unambiguously identify the transaction. This identification is passed on, unchanged, throughout the entire end-to-end chain.  Usage: The end-to-end identification can be used for reconciliation or to link tasks relating to the transaction. It can be included in several messages related to the transaction.  Usage: In case there are technical limitations to pass on multiple references, the end-to-end identification must be passed on throughout the entire end-to-end chain.
        /// </summary>
        [JsonProperty("end_to_end_identification", NullValueHandling = NullValueHandling.Ignore)]
        public string EndToEndIdentification { get; set; }

        /// <summary>
        /// Universally unique identifier to provide an end-to-end reference of a payment transaction.
        /// </summary>
        [JsonProperty("uetr", NullValueHandling = NullValueHandling.Ignore)]
        public Guid? Uetr { get; set; }

        /// <summary>
        /// Unique identification, as assigned by the first instructing agent, to unambiguously identify the transaction that is passed on, unchanged, throughout the entire interbank chain.  Usage: The transaction identification can be used for reconciliation, tracking or to link tasks relating to the transaction on the interbank level.  Usage: The instructing agent has to make sure that the transaction identification is unique for a pre-agreed period.
        /// </summary>
        [JsonProperty("transaction_identification", NullValueHandling = NullValueHandling.Ignore)]
        public string TransactionIdentification { get; set; }

        /// <summary>
        /// Unique identification, as assigned by the creditor, to unambiguously identify the mandate.
        /// </summary>
        [JsonProperty("mandate_identification", NullValueHandling = NullValueHandling.Ignore)]
        public string MandateIdentification { get; set; }

        /// <summary>
        /// Unique and unambiguous identifier for a cheque as assigned by the agent.
        /// </summary>
        [JsonProperty("cheque_number", NullValueHandling = NullValueHandling.Ignore)]
        public string ChequeNumber { get; set; }

        /// <summary>
        /// Unique reference, as assigned by a clearing system, to unambiguously identify the instruction. Usage: In case there are technical limitations to pass on multiple references, the end-to-end identification must be passed on throughout the entire end-to-end chain.
        /// </summary>
        [JsonProperty("clearing_system_reference", NullValueHandling = NullValueHandling.Ignore)]
        public string ClearingSystemReference { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"References : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is References other &&
                (this.MessageIdentification == null && other.MessageIdentification == null ||
                 this.MessageIdentification?.Equals(other.MessageIdentification) == true) &&
                (this.AccountServicerReference == null && other.AccountServicerReference == null ||
                 this.AccountServicerReference?.Equals(other.AccountServicerReference) == true) &&
                (this.PaymentInformationIdentification == null && other.PaymentInformationIdentification == null ||
                 this.PaymentInformationIdentification?.Equals(other.PaymentInformationIdentification) == true) &&
                (this.InstructionIdentification == null && other.InstructionIdentification == null ||
                 this.InstructionIdentification?.Equals(other.InstructionIdentification) == true) &&
                (this.EndToEndIdentification == null && other.EndToEndIdentification == null ||
                 this.EndToEndIdentification?.Equals(other.EndToEndIdentification) == true) &&
                (this.Uetr == null && other.Uetr == null ||
                 this.Uetr?.Equals(other.Uetr) == true) &&
                (this.TransactionIdentification == null && other.TransactionIdentification == null ||
                 this.TransactionIdentification?.Equals(other.TransactionIdentification) == true) &&
                (this.MandateIdentification == null && other.MandateIdentification == null ||
                 this.MandateIdentification?.Equals(other.MandateIdentification) == true) &&
                (this.ChequeNumber == null && other.ChequeNumber == null ||
                 this.ChequeNumber?.Equals(other.ChequeNumber) == true) &&
                (this.ClearingSystemReference == null && other.ClearingSystemReference == null ||
                 this.ClearingSystemReference?.Equals(other.ClearingSystemReference) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"MessageIdentification = {this.MessageIdentification ?? "null"}");
            toStringOutput.Add($"AccountServicerReference = {this.AccountServicerReference ?? "null"}");
            toStringOutput.Add($"PaymentInformationIdentification = {this.PaymentInformationIdentification ?? "null"}");
            toStringOutput.Add($"InstructionIdentification = {this.InstructionIdentification ?? "null"}");
            toStringOutput.Add($"EndToEndIdentification = {this.EndToEndIdentification ?? "null"}");
            toStringOutput.Add($"Uetr = {(this.Uetr == null ? "null" : this.Uetr.ToString())}");
            toStringOutput.Add($"TransactionIdentification = {this.TransactionIdentification ?? "null"}");
            toStringOutput.Add($"MandateIdentification = {this.MandateIdentification ?? "null"}");
            toStringOutput.Add($"ChequeNumber = {this.ChequeNumber ?? "null"}");
            toStringOutput.Add($"ClearingSystemReference = {this.ClearingSystemReference ?? "null"}");
        }
    }
}