// <copyright file="ReferredDocumentTypeChoice.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// ReferredDocumentTypeChoice.
    /// </summary>
    public class ReferredDocumentTypeChoice
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReferredDocumentTypeChoice"/> class.
        /// </summary>
        public ReferredDocumentTypeChoice()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReferredDocumentTypeChoice"/> class.
        /// </summary>
        /// <param name="code">code.</param>
        /// <param name="proprietary">proprietary.</param>
        public ReferredDocumentTypeChoice(
            Models.DocumentTypeCodeEnum? code = null,
            string proprietary = null)
        {
            this.Code = code;
            this.Proprietary = proprietary;
        }

        /// <summary>
        /// Gets or sets Code.
        /// </summary>
        [JsonProperty("code", NullValueHandling = NullValueHandling.Ignore)]
        public Models.DocumentTypeCodeEnum? Code { get; set; }

        /// <summary>
        /// Proprietary identification of the type of the remittance document.
        /// </summary>
        [JsonProperty("proprietary", NullValueHandling = NullValueHandling.Ignore)]
        public string Proprietary { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ReferredDocumentTypeChoice : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ReferredDocumentTypeChoice other &&
                (this.Code == null && other.Code == null ||
                 this.Code?.Equals(other.Code) == true) &&
                (this.Proprietary == null && other.Proprietary == null ||
                 this.Proprietary?.Equals(other.Proprietary) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Code = {(this.Code == null ? "null" : this.Code.ToString())}");
            toStringOutput.Add($"Proprietary = {this.Proprietary ?? "null"}");
        }
    }
}