// <copyright file="RelatedAccount.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// RelatedAccount.
    /// </summary>
    public class RelatedAccount
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RelatedAccount"/> class.
        /// </summary>
        public RelatedAccount()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RelatedAccount"/> class.
        /// </summary>
        /// <param name="identification">identification.</param>
        /// <param name="type">type.</param>
        /// <param name="currency">currency.</param>
        /// <param name="name">name.</param>
        /// <param name="alternateIdentification">alternate_identification.</param>
        public RelatedAccount(
            object identification,
            object type = null,
            string currency = null,
            string name = null,
            Models.AlternateIdentification alternateIdentification = null)
        {
            this.Identification = identification;
            this.Type = type;
            this.Currency = currency;
            this.Name = name;
            this.AlternateIdentification = alternateIdentification;
        }

        /// <summary>
        /// Gets or sets Identification.
        /// </summary>
        [JsonProperty("identification")]
        public object Identification { get; set; }

        /// <summary>
        /// Gets or sets Type.
        /// </summary>
        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public object Type { get; set; }

        /// <summary>
        /// A code allocated to a currency by a Maintenance Agency under an international identification scheme, as described in the latest edition of the international standard ISO 4217 "Codes for the representation of currencies and funds".
        /// </summary>
        [JsonProperty("currency", NullValueHandling = NullValueHandling.Ignore)]
        public string Currency { get; set; }

        /// <summary>
        /// Name of the account, as assigned by the account servicing institution, in agreement with the account owner in order to provide an additional means of identification of the account.
        /// Usage: The account name is different from the account owner name. The account name is used in certain user communities to provide a means of identifying the account, in addition to the account owners identity and the account number.
        /// </summary>
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets AlternateIdentification.
        /// </summary>
        [JsonProperty("alternate_identification", NullValueHandling = NullValueHandling.Ignore)]
        public Models.AlternateIdentification AlternateIdentification { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"RelatedAccount : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is RelatedAccount other &&
                (this.Identification == null && other.Identification == null ||
                 this.Identification?.Equals(other.Identification) == true) &&
                (this.Type == null && other.Type == null ||
                 this.Type?.Equals(other.Type) == true) &&
                (this.Currency == null && other.Currency == null ||
                 this.Currency?.Equals(other.Currency) == true) &&
                (this.Name == null && other.Name == null ||
                 this.Name?.Equals(other.Name) == true) &&
                (this.AlternateIdentification == null && other.AlternateIdentification == null ||
                 this.AlternateIdentification?.Equals(other.AlternateIdentification) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Identification = {(this.Identification == null ? "null" : this.Identification.ToString())}");
            toStringOutput.Add($"Type = {(this.Type == null ? "null" : this.Type.ToString())}");
            toStringOutput.Add($"Currency = {this.Currency ?? "null"}");
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"AlternateIdentification = {(this.AlternateIdentification == null ? "null" : this.AlternateIdentification.ToString())}");
        }
    }
}