// <copyright file="RelatedDates.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// RelatedDates.
    /// </summary>
    public class RelatedDates
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RelatedDates"/> class.
        /// </summary>
        public RelatedDates()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RelatedDates"/> class.
        /// </summary>
        /// <param name="acceptanceDateTime">acceptance_date_time.</param>
        /// <param name="tradeActivityContractualSettlementDate">trade_activity_contractual_settlement_date.</param>
        /// <param name="tradeDate">trade_date.</param>
        /// <param name="interbankSettlementDate">interbank_settlement_date.</param>
        /// <param name="startDate">start_date.</param>
        /// <param name="endDate">end_date.</param>
        /// <param name="transactionDateTime">transaction_date_time.</param>
        public RelatedDates(
            string acceptanceDateTime = null,
            string tradeActivityContractualSettlementDate = null,
            string tradeDate = null,
            string interbankSettlementDate = null,
            string startDate = null,
            string endDate = null,
            string transactionDateTime = null)
        {
            this.AcceptanceDateTime = acceptanceDateTime;
            this.TradeActivityContractualSettlementDate = tradeActivityContractualSettlementDate;
            this.TradeDate = tradeDate;
            this.InterbankSettlementDate = interbankSettlementDate;
            this.StartDate = startDate;
            this.EndDate = endDate;
            this.TransactionDateTime = transactionDateTime;
        }

        /// <summary>
        /// A particular point in the progression of time defined by a mandatory date and a mandatory time component, expressed in either UTC time format (YYYY-MM-DDThh:mm:ss.sssZ), local time with UTC offset format (YYYY-MM-DDThh:mm:ss.sss+/-hh:mm), or local time format (YYYY-MM-DDThh:mm:ss.sss). These representations are defined in "XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004" which is aligned with ISO 8601.
        /// Note on the time format:
        /// 1) beginning / end of calendar day
        /// 00:00:00 = the beginning of a calendar day
        /// 24:00:00 = the end of a calendar day
        /// 2) fractions of second in time format
        /// Decimal fractions of seconds may be included. In this case, the involved parties shall agree on the maximum number of digits that are allowed.
        /// </summary>
        [JsonProperty("acceptance_date_time", NullValueHandling = NullValueHandling.Ignore)]
        public string AcceptanceDateTime { get; set; }

        /// <summary>
        /// A particular point in the progression of time in a calendar year expressed in the YYYY-MM-DD format. This representation is defined in "XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004" which is aligned with ISO 8601.
        /// </summary>
        [JsonProperty("trade_activity_contractual_settlement_date", NullValueHandling = NullValueHandling.Ignore)]
        public string TradeActivityContractualSettlementDate { get; set; }

        /// <summary>
        /// A particular point in the progression of time in a calendar year expressed in the YYYY-MM-DD format. This representation is defined in "XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004" which is aligned with ISO 8601.
        /// </summary>
        [JsonProperty("trade_date", NullValueHandling = NullValueHandling.Ignore)]
        public string TradeDate { get; set; }

        /// <summary>
        /// A particular point in the progression of time in a calendar year expressed in the YYYY-MM-DD format. This representation is defined in "XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004" which is aligned with ISO 8601.
        /// </summary>
        [JsonProperty("interbank_settlement_date", NullValueHandling = NullValueHandling.Ignore)]
        public string InterbankSettlementDate { get; set; }

        /// <summary>
        /// A particular point in the progression of time in a calendar year expressed in the YYYY-MM-DD format. This representation is defined in "XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004" which is aligned with ISO 8601.
        /// </summary>
        [JsonProperty("start_date", NullValueHandling = NullValueHandling.Ignore)]
        public string StartDate { get; set; }

        /// <summary>
        /// A particular point in the progression of time in a calendar year expressed in the YYYY-MM-DD format. This representation is defined in "XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004" which is aligned with ISO 8601.
        /// </summary>
        [JsonProperty("end_date", NullValueHandling = NullValueHandling.Ignore)]
        public string EndDate { get; set; }

        /// <summary>
        /// A particular point in the progression of time defined by a mandatory date and a mandatory time component, expressed in either UTC time format (YYYY-MM-DDThh:mm:ss.sssZ), local time with UTC offset format (YYYY-MM-DDThh:mm:ss.sss+/-hh:mm), or local time format (YYYY-MM-DDThh:mm:ss.sss). These representations are defined in "XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004" which is aligned with ISO 8601.
        /// Note on the time format:
        /// 1) beginning / end of calendar day
        /// 00:00:00 = the beginning of a calendar day
        /// 24:00:00 = the end of a calendar day
        /// 2) fractions of second in time format
        /// Decimal fractions of seconds may be included. In this case, the involved parties shall agree on the maximum number of digits that are allowed.
        /// </summary>
        [JsonProperty("transaction_date_time", NullValueHandling = NullValueHandling.Ignore)]
        public string TransactionDateTime { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"RelatedDates : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is RelatedDates other &&
                (this.AcceptanceDateTime == null && other.AcceptanceDateTime == null ||
                 this.AcceptanceDateTime?.Equals(other.AcceptanceDateTime) == true) &&
                (this.TradeActivityContractualSettlementDate == null && other.TradeActivityContractualSettlementDate == null ||
                 this.TradeActivityContractualSettlementDate?.Equals(other.TradeActivityContractualSettlementDate) == true) &&
                (this.TradeDate == null && other.TradeDate == null ||
                 this.TradeDate?.Equals(other.TradeDate) == true) &&
                (this.InterbankSettlementDate == null && other.InterbankSettlementDate == null ||
                 this.InterbankSettlementDate?.Equals(other.InterbankSettlementDate) == true) &&
                (this.StartDate == null && other.StartDate == null ||
                 this.StartDate?.Equals(other.StartDate) == true) &&
                (this.EndDate == null && other.EndDate == null ||
                 this.EndDate?.Equals(other.EndDate) == true) &&
                (this.TransactionDateTime == null && other.TransactionDateTime == null ||
                 this.TransactionDateTime?.Equals(other.TransactionDateTime) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AcceptanceDateTime = {this.AcceptanceDateTime ?? "null"}");
            toStringOutput.Add($"TradeActivityContractualSettlementDate = {this.TradeActivityContractualSettlementDate ?? "null"}");
            toStringOutput.Add($"TradeDate = {this.TradeDate ?? "null"}");
            toStringOutput.Add($"InterbankSettlementDate = {this.InterbankSettlementDate ?? "null"}");
            toStringOutput.Add($"StartDate = {this.StartDate ?? "null"}");
            toStringOutput.Add($"EndDate = {this.EndDate ?? "null"}");
            toStringOutput.Add($"TransactionDateTime = {this.TransactionDateTime ?? "null"}");
        }
    }
}