// <copyright file="RelatedParties.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// RelatedParties.
    /// </summary>
    public class RelatedParties
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RelatedParties"/> class.
        /// </summary>
        public RelatedParties()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RelatedParties"/> class.
        /// </summary>
        /// <param name="initiatingParty">initiating_party.</param>
        /// <param name="debtor">debtor.</param>
        /// <param name="debtorAccount">debtor_account.</param>
        /// <param name="ultimateDebtor">ultimate_debtor.</param>
        /// <param name="creditor">creditor.</param>
        /// <param name="creditorAccount">creditor_account.</param>
        /// <param name="ultimateCreditor">ultimate_creditor.</param>
        public RelatedParties(
            object initiatingParty = null,
            object debtor = null,
            Models.DebtorAccount debtorAccount = null,
            object ultimateDebtor = null,
            object creditor = null,
            Models.CreditorAccount creditorAccount = null,
            object ultimateCreditor = null)
        {
            this.InitiatingParty = initiatingParty;
            this.Debtor = debtor;
            this.DebtorAccount = debtorAccount;
            this.UltimateDebtor = ultimateDebtor;
            this.Creditor = creditor;
            this.CreditorAccount = creditorAccount;
            this.UltimateCreditor = ultimateCreditor;
        }

        /// <summary>
        /// Gets or sets InitiatingParty.
        /// </summary>
        [JsonProperty("initiating_party", NullValueHandling = NullValueHandling.Ignore)]
        public object InitiatingParty { get; set; }

        /// <summary>
        /// Gets or sets Debtor.
        /// </summary>
        [JsonProperty("debtor", NullValueHandling = NullValueHandling.Ignore)]
        public object Debtor { get; set; }

        /// <summary>
        /// Gets or sets DebtorAccount.
        /// </summary>
        [JsonProperty("debtor_account", NullValueHandling = NullValueHandling.Ignore)]
        public Models.DebtorAccount DebtorAccount { get; set; }

        /// <summary>
        /// Gets or sets UltimateDebtor.
        /// </summary>
        [JsonProperty("ultimate_debtor", NullValueHandling = NullValueHandling.Ignore)]
        public object UltimateDebtor { get; set; }

        /// <summary>
        /// Gets or sets Creditor.
        /// </summary>
        [JsonProperty("creditor", NullValueHandling = NullValueHandling.Ignore)]
        public object Creditor { get; set; }

        /// <summary>
        /// Gets or sets CreditorAccount.
        /// </summary>
        [JsonProperty("creditor_account", NullValueHandling = NullValueHandling.Ignore)]
        public Models.CreditorAccount CreditorAccount { get; set; }

        /// <summary>
        /// Gets or sets UltimateCreditor.
        /// </summary>
        [JsonProperty("ultimate_creditor", NullValueHandling = NullValueHandling.Ignore)]
        public object UltimateCreditor { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"RelatedParties : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is RelatedParties other &&
                (this.InitiatingParty == null && other.InitiatingParty == null ||
                 this.InitiatingParty?.Equals(other.InitiatingParty) == true) &&
                (this.Debtor == null && other.Debtor == null ||
                 this.Debtor?.Equals(other.Debtor) == true) &&
                (this.DebtorAccount == null && other.DebtorAccount == null ||
                 this.DebtorAccount?.Equals(other.DebtorAccount) == true) &&
                (this.UltimateDebtor == null && other.UltimateDebtor == null ||
                 this.UltimateDebtor?.Equals(other.UltimateDebtor) == true) &&
                (this.Creditor == null && other.Creditor == null ||
                 this.Creditor?.Equals(other.Creditor) == true) &&
                (this.CreditorAccount == null && other.CreditorAccount == null ||
                 this.CreditorAccount?.Equals(other.CreditorAccount) == true) &&
                (this.UltimateCreditor == null && other.UltimateCreditor == null ||
                 this.UltimateCreditor?.Equals(other.UltimateCreditor) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"InitiatingParty = {(this.InitiatingParty == null ? "null" : this.InitiatingParty.ToString())}");
            toStringOutput.Add($"Debtor = {(this.Debtor == null ? "null" : this.Debtor.ToString())}");
            toStringOutput.Add($"DebtorAccount = {(this.DebtorAccount == null ? "null" : this.DebtorAccount.ToString())}");
            toStringOutput.Add($"UltimateDebtor = {(this.UltimateDebtor == null ? "null" : this.UltimateDebtor.ToString())}");
            toStringOutput.Add($"Creditor = {(this.Creditor == null ? "null" : this.Creditor.ToString())}");
            toStringOutput.Add($"CreditorAccount = {(this.CreditorAccount == null ? "null" : this.CreditorAccount.ToString())}");
            toStringOutput.Add($"UltimateCreditor = {(this.UltimateCreditor == null ? "null" : this.UltimateCreditor.ToString())}");
        }
    }
}