// <copyright file="RemittanceInformation.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// RemittanceInformation.
    /// </summary>
    public class RemittanceInformation
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RemittanceInformation"/> class.
        /// </summary>
        public RemittanceInformation()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RemittanceInformation"/> class.
        /// </summary>
        /// <param name="referredDocumentInformation">referred_document_information.</param>
        /// <param name="amount">amount.</param>
        /// <param name="creditorReferenceCode">creditor_reference_code.</param>
        /// <param name="creditorReference">creditor_reference.</param>
        public RemittanceInformation(
            List<Models.Document> referredDocumentInformation = null,
            Models.Amount1 amount = null,
            Models.CreditorReferenceCodeEnum? creditorReferenceCode = null,
            string creditorReference = null)
        {
            this.ReferredDocumentInformation = referredDocumentInformation;
            this.Amount = amount;
            this.CreditorReferenceCode = creditorReferenceCode;
            this.CreditorReference = creditorReference;
        }

        /// <summary>
        /// Provides the identification and the content of the referred document. For example if they payment is against outstanding invoice, provide the invoice details or to apply a credit note specify the detail.
        /// </summary>
        [JsonProperty("referred_document_information", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.Document> ReferredDocumentInformation { get; set; }

        /// <summary>
        /// Gets or sets Amount.
        /// </summary>
        [JsonProperty("amount", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Amount1 Amount { get; set; }

        /// <summary>
        /// Gets or sets CreditorReferenceCode.
        /// </summary>
        [JsonProperty("creditor_reference_code", NullValueHandling = NullValueHandling.Ignore)]
        public Models.CreditorReferenceCodeEnum? CreditorReferenceCode { get; set; }

        /// <summary>
        /// Unique reference, as assigned by the creditor, to unambiguously refer to the payment transaction.
        /// Usage: If available, the initiating party should provide this reference in the structured remittance information, to enable reconciliation by the creditor upon receipt of the amount of money.
        /// If the business context requires the use of a creditor reference or a payment remit identification, and only one identifier can be passed through the end-to-end chain, the creditor's reference or payment remittance identification should be quoted in the end-to-end transaction identification.
        /// </summary>
        [JsonProperty("creditor_reference", NullValueHandling = NullValueHandling.Ignore)]
        public string CreditorReference { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"RemittanceInformation : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is RemittanceInformation other &&
                (this.ReferredDocumentInformation == null && other.ReferredDocumentInformation == null ||
                 this.ReferredDocumentInformation?.Equals(other.ReferredDocumentInformation) == true) &&
                (this.Amount == null && other.Amount == null ||
                 this.Amount?.Equals(other.Amount) == true) &&
                (this.CreditorReferenceCode == null && other.CreditorReferenceCode == null ||
                 this.CreditorReferenceCode?.Equals(other.CreditorReferenceCode) == true) &&
                (this.CreditorReference == null && other.CreditorReference == null ||
                 this.CreditorReference?.Equals(other.CreditorReference) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ReferredDocumentInformation = {(this.ReferredDocumentInformation == null ? "null" : $"[{string.Join(", ", this.ReferredDocumentInformation)} ]")}");
            toStringOutput.Add($"Amount = {(this.Amount == null ? "null" : this.Amount.ToString())}");
            toStringOutput.Add($"CreditorReferenceCode = {(this.CreditorReferenceCode == null ? "null" : this.CreditorReferenceCode.ToString())}");
            toStringOutput.Add($"CreditorReference = {this.CreditorReference ?? "null"}");
        }
    }
}