// <copyright file="RemittanceInformationStructured.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// RemittanceInformationStructured.
    /// </summary>
    public class RemittanceInformationStructured
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RemittanceInformationStructured"/> class.
        /// </summary>
        public RemittanceInformationStructured()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RemittanceInformationStructured"/> class.
        /// </summary>
        /// <param name="structured">structured.</param>
        public RemittanceInformationStructured(
            List<Models.RemittanceInformation> structured)
        {
            this.Structured = structured;
        }

        /// <summary>
        /// Gets or sets Structured.
        /// </summary>
        [JsonProperty("structured")]
        public List<Models.RemittanceInformation> Structured { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"RemittanceInformationStructured : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is RemittanceInformationStructured other &&
                (this.Structured == null && other.Structured == null ||
                 this.Structured?.Equals(other.Structured) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Structured = {(this.Structured == null ? "null" : $"[{string.Join(", ", this.Structured)} ]")}");
        }
    }
}