// <copyright file="RemittanceInformationUnstructured.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// RemittanceInformationUnstructured.
    /// </summary>
    public class RemittanceInformationUnstructured
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RemittanceInformationUnstructured"/> class.
        /// </summary>
        public RemittanceInformationUnstructured()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RemittanceInformationUnstructured"/> class.
        /// </summary>
        /// <param name="unstructured">unstructured.</param>
        public RemittanceInformationUnstructured(
            string unstructured)
        {
            this.Unstructured = unstructured;
        }

        /// <summary>
        /// Information supplied to enable the matching/reconciliation of an entry with the items that the payment is intended to settle, such as commercial invoices in an accounts' receivable system, in an unstructured form.
        /// </summary>
        [JsonProperty("unstructured")]
        public string Unstructured { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"RemittanceInformationUnstructured : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is RemittanceInformationUnstructured other &&
                (this.Unstructured == null && other.Unstructured == null ||
                 this.Unstructured?.Equals(other.Unstructured) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Unstructured = {this.Unstructured ?? "null"}");
        }
    }
}