// <copyright file="ReturnReasonProprietary.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// ReturnReasonProprietary.
    /// </summary>
    public class ReturnReasonProprietary
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReturnReasonProprietary"/> class.
        /// </summary>
        public ReturnReasonProprietary()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReturnReasonProprietary"/> class.
        /// </summary>
        /// <param name="proprietary">proprietary.</param>
        public ReturnReasonProprietary(
            string proprietary)
        {
            this.Proprietary = proprietary;
        }

        /// <summary>
        /// Reason for the return, in a proprietary form.
        /// </summary>
        [JsonProperty("proprietary")]
        public string Proprietary { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ReturnReasonProprietary : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ReturnReasonProprietary other &&
                (this.Proprietary == null && other.Proprietary == null ||
                 this.Proprietary?.Equals(other.Proprietary) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Proprietary = {this.Proprietary ?? "null"}");
        }
    }
}