// <copyright file="SeverityEnum.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// SeverityEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum SeverityEnum
    {
        /// <summary>
        /// Fatal.
        /// </summary>
        [EnumMember(Value = "Fatal")]
        Fatal,

        /// <summary>
        /// Transient.
        /// </summary>
        [EnumMember(Value = "Transient")]
        Transient,

        /// <summary>
        /// Logic.
        /// </summary>
        [EnumMember(Value = "Logic")]
        Logic
    }
}