// <copyright file="StatementTransactionDetails.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// StatementTransactionDetails.
    /// </summary>
    public class StatementTransactionDetails
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StatementTransactionDetails"/> class.
        /// </summary>
        public StatementTransactionDetails()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StatementTransactionDetails"/> class.
        /// </summary>
        /// <param name="references">references.</param>
        /// <param name="creditDebitIndicator">credit_debit_indicator.</param>
        /// <param name="amount">amount.</param>
        /// <param name="amountDetails">amount_details.</param>
        /// <param name="availability">availability.</param>
        /// <param name="bankTransactionCode">bank_transaction_code.</param>
        /// <param name="charges">charges.</param>
        /// <param name="relatedParties">related_parties.</param>
        /// <param name="relatedAgents">related_agents.</param>
        /// <param name="purpose">purpose.</param>
        /// <param name="remittanceInformation">remittance_information.</param>
        /// <param name="relatedDates">related_dates.</param>
        /// <param name="returnInformation">return_information.</param>
        public StatementTransactionDetails(
            Models.References references,
            Models.CreditDebitCodeEnum creditDebitIndicator,
            Models.Amount1 amount = null,
            Models.AmountDetails amountDetails = null,
            List<Models.CashAvailability> availability = null,
            Models.BankTransactionCode1 bankTransactionCode = null,
            Models.Charges1 charges = null,
            Models.RelatedParties relatedParties = null,
            Models.RelatedAgents relatedAgents = null,
            string purpose = null,
            object remittanceInformation = null,
            Models.RelatedDates relatedDates = null,
            Models.ReturnInformation returnInformation = null)
        {
            this.References = references;
            this.Amount = amount;
            this.CreditDebitIndicator = creditDebitIndicator;
            this.AmountDetails = amountDetails;
            this.Availability = availability;
            this.BankTransactionCode = bankTransactionCode;
            this.Charges = charges;
            this.RelatedParties = relatedParties;
            this.RelatedAgents = relatedAgents;
            this.Purpose = purpose;
            this.RemittanceInformation = remittanceInformation;
            this.RelatedDates = relatedDates;
            this.ReturnInformation = returnInformation;
        }

        /// <summary>
        /// Gets or sets References.
        /// </summary>
        [JsonProperty("references")]
        public Models.References References { get; set; }

        /// <summary>
        /// Gets or sets Amount.
        /// </summary>
        [JsonProperty("amount", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Amount1 Amount { get; set; }

        /// <summary>
        /// Gets or sets CreditDebitIndicator.
        /// </summary>
        [JsonProperty("credit_debit_indicator")]
        public Models.CreditDebitCodeEnum CreditDebitIndicator { get; set; }

        /// <summary>
        /// Gets or sets AmountDetails.
        /// </summary>
        [JsonProperty("amount_details", NullValueHandling = NullValueHandling.Ignore)]
        public Models.AmountDetails AmountDetails { get; set; }

        /// <summary>
        /// Set of elements used to indicate when the booked amount of money will become available, that is can be accessed and starts generating interest.
        /// Usage - This type of information is used in the US and is linked to particular instruments such as cheques. Example - When a cheque is deposited, it will be booked on the deposit day, but the amount of money will only be accessible as of the indicated availability day (according to national banking regulations).
        /// </summary>
        [JsonProperty("availability", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.CashAvailability> Availability { get; set; }

        /// <summary>
        /// Gets or sets BankTransactionCode.
        /// </summary>
        [JsonProperty("bank_transaction_code", NullValueHandling = NullValueHandling.Ignore)]
        public Models.BankTransactionCode1 BankTransactionCode { get; set; }

        /// <summary>
        /// Gets or sets Charges.
        /// </summary>
        [JsonProperty("charges", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Charges1 Charges { get; set; }

        /// <summary>
        /// Gets or sets RelatedParties.
        /// </summary>
        [JsonProperty("related_parties", NullValueHandling = NullValueHandling.Ignore)]
        public Models.RelatedParties RelatedParties { get; set; }

        /// <summary>
        /// Gets or sets RelatedAgents.
        /// </summary>
        [JsonProperty("related_agents", NullValueHandling = NullValueHandling.Ignore)]
        public Models.RelatedAgents RelatedAgents { get; set; }

        /// <summary>
        /// Specifies the external purpose code in the format of character string with a maximum length of 4 characters. The list of valid codes is an external code list published separately. External code sets can be downloaded from www.iso20022.org.
        /// </summary>
        [JsonProperty("purpose", NullValueHandling = NullValueHandling.Ignore)]
        public string Purpose { get; set; }

        /// <summary>
        /// Gets or sets RemittanceInformation.
        /// </summary>
        [JsonProperty("remittance_information", NullValueHandling = NullValueHandling.Ignore)]
        public object RemittanceInformation { get; set; }

        /// <summary>
        /// Gets or sets RelatedDates.
        /// </summary>
        [JsonProperty("related_dates", NullValueHandling = NullValueHandling.Ignore)]
        public Models.RelatedDates RelatedDates { get; set; }

        /// <summary>
        /// Gets or sets ReturnInformation.
        /// </summary>
        [JsonProperty("return_information", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ReturnInformation ReturnInformation { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"StatementTransactionDetails : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is StatementTransactionDetails other &&
                (this.References == null && other.References == null ||
                 this.References?.Equals(other.References) == true) &&
                (this.Amount == null && other.Amount == null ||
                 this.Amount?.Equals(other.Amount) == true) &&
                (this.CreditDebitIndicator.Equals(other.CreditDebitIndicator)) &&
                (this.AmountDetails == null && other.AmountDetails == null ||
                 this.AmountDetails?.Equals(other.AmountDetails) == true) &&
                (this.Availability == null && other.Availability == null ||
                 this.Availability?.Equals(other.Availability) == true) &&
                (this.BankTransactionCode == null && other.BankTransactionCode == null ||
                 this.BankTransactionCode?.Equals(other.BankTransactionCode) == true) &&
                (this.Charges == null && other.Charges == null ||
                 this.Charges?.Equals(other.Charges) == true) &&
                (this.RelatedParties == null && other.RelatedParties == null ||
                 this.RelatedParties?.Equals(other.RelatedParties) == true) &&
                (this.RelatedAgents == null && other.RelatedAgents == null ||
                 this.RelatedAgents?.Equals(other.RelatedAgents) == true) &&
                (this.Purpose == null && other.Purpose == null ||
                 this.Purpose?.Equals(other.Purpose) == true) &&
                (this.RemittanceInformation == null && other.RemittanceInformation == null ||
                 this.RemittanceInformation?.Equals(other.RemittanceInformation) == true) &&
                (this.RelatedDates == null && other.RelatedDates == null ||
                 this.RelatedDates?.Equals(other.RelatedDates) == true) &&
                (this.ReturnInformation == null && other.ReturnInformation == null ||
                 this.ReturnInformation?.Equals(other.ReturnInformation) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"References = {(this.References == null ? "null" : this.References.ToString())}");
            toStringOutput.Add($"Amount = {(this.Amount == null ? "null" : this.Amount.ToString())}");
            toStringOutput.Add($"CreditDebitIndicator = {this.CreditDebitIndicator}");
            toStringOutput.Add($"AmountDetails = {(this.AmountDetails == null ? "null" : this.AmountDetails.ToString())}");
            toStringOutput.Add($"Availability = {(this.Availability == null ? "null" : $"[{string.Join(", ", this.Availability)} ]")}");
            toStringOutput.Add($"BankTransactionCode = {(this.BankTransactionCode == null ? "null" : this.BankTransactionCode.ToString())}");
            toStringOutput.Add($"Charges = {(this.Charges == null ? "null" : this.Charges.ToString())}");
            toStringOutput.Add($"RelatedParties = {(this.RelatedParties == null ? "null" : this.RelatedParties.ToString())}");
            toStringOutput.Add($"RelatedAgents = {(this.RelatedAgents == null ? "null" : this.RelatedAgents.ToString())}");
            toStringOutput.Add($"Purpose = {this.Purpose ?? "null"}");
            toStringOutput.Add($"RemittanceInformation = {(this.RemittanceInformation == null ? "null" : this.RemittanceInformation.ToString())}");
            toStringOutput.Add($"RelatedDates = {(this.RelatedDates == null ? "null" : this.RelatedDates.ToString())}");
            toStringOutput.Add($"ReturnInformation = {(this.ReturnInformation == null ? "null" : this.ReturnInformation.ToString())}");
        }
    }
}