// <copyright file="StatementLine.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using SwiftBankingAPIPortal.Standard.Models.Containers;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// StatementLine.
    /// </summary>
    public class StatementLine
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StatementLine"/> class.
        /// </summary>
        public StatementLine()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StatementLine"/> class.
        /// </summary>
        /// <param name="entryReference">entry_reference.</param>
        /// <param name="amount">amount.</param>
        /// <param name="creditDebitIndicator">credit_debit_indicator.</param>
        /// <param name="bankTransactionCode">bank_transaction_code.</param>
        /// <param name="references">references.</param>
        /// <param name="batch">batch.</param>
        /// <param name="bookingDate">booking_date.</param>
        /// <param name="valueDate">value_date.</param>
        /// <param name="purpose">purpose.</param>
        /// <param name="remittanceInformation">remittance_information.</param>
        public StatementLine(
            string entryReference,
            Models.Amount1 amount,
            Models.CreditDebitCodeEnum creditDebitIndicator,
            Models.BankTransactionCode1 bankTransactionCode,
            Models.References references = null,
            Models.Batch batch = null,
            StatementLineBookingDate bookingDate = null,
            StatementLineValueDate valueDate = null,
            string purpose = null,
            object remittanceInformation = null)
        {
            this.EntryReference = entryReference;
            this.References = references;
            this.Batch = batch;
            this.Amount = amount;
            this.CreditDebitIndicator = creditDebitIndicator;
            this.BookingDate = bookingDate;
            this.ValueDate = valueDate;
            this.BankTransactionCode = bankTransactionCode;
            this.Purpose = purpose;
            this.RemittanceInformation = remittanceInformation;
        }

        /// <summary>
        /// Unique reference for the entry. Technical incremental identification of the transaction.
        /// </summary>
        [JsonProperty("entry_reference")]
        public string EntryReference { get; set; }

        /// <summary>
        /// Gets or sets References.
        /// </summary>
        [JsonProperty("references", NullValueHandling = NullValueHandling.Ignore)]
        public Models.References References { get; set; }

        /// <summary>
        /// Gets or sets Batch.
        /// </summary>
        [JsonProperty("batch", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Batch Batch { get; set; }

        /// <summary>
        /// Gets or sets Amount.
        /// </summary>
        [JsonProperty("amount")]
        public Models.Amount1 Amount { get; set; }

        /// <summary>
        /// Gets or sets CreditDebitIndicator.
        /// </summary>
        [JsonProperty("credit_debit_indicator")]
        public Models.CreditDebitCodeEnum CreditDebitIndicator { get; set; }

        /// <summary>
        /// Date and time when an entry is posted to an account on the account servicer's books.
        /// *`Usage:`Booking date is the expected booking date, unless the status is booked, in which case it is the actual booking date.
        /// </summary>
        [JsonProperty("booking_date", NullValueHandling = NullValueHandling.Ignore)]
        public StatementLineBookingDate BookingDate { get; set; }

        /// <summary>
        /// Date and time at which assets become available to the account owner in case of a credit entry, or cease to be available to the account owner in case of a debit entry.
        /// *`Usage:` If entry status is pending and value date is present, then the value date refers to an expected/requested value date. For entries subject to availability/float and for which availability information is provided, the value date must not be used. In this case the availability component identifies the number of availability days.
        /// </summary>
        [JsonProperty("value_date", NullValueHandling = NullValueHandling.Ignore)]
        public StatementLineValueDate ValueDate { get; set; }

        /// <summary>
        /// Gets or sets BankTransactionCode.
        /// </summary>
        [JsonProperty("bank_transaction_code")]
        public Models.BankTransactionCode1 BankTransactionCode { get; set; }

        /// <summary>
        /// Specifies the external purpose code in the format of character string with a maximum length of 4 characters. The list of valid codes is an external code list published separately. External code sets can be downloaded from www.iso20022.org.
        /// </summary>
        [JsonProperty("purpose", NullValueHandling = NullValueHandling.Ignore)]
        public string Purpose { get; set; }

        /// <summary>
        /// Gets or sets RemittanceInformation.
        /// </summary>
        [JsonProperty("remittance_information", NullValueHandling = NullValueHandling.Ignore)]
        public object RemittanceInformation { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"StatementLine : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is StatementLine other &&
                (this.EntryReference == null && other.EntryReference == null ||
                 this.EntryReference?.Equals(other.EntryReference) == true) &&
                (this.References == null && other.References == null ||
                 this.References?.Equals(other.References) == true) &&
                (this.Batch == null && other.Batch == null ||
                 this.Batch?.Equals(other.Batch) == true) &&
                (this.Amount == null && other.Amount == null ||
                 this.Amount?.Equals(other.Amount) == true) &&
                (this.CreditDebitIndicator.Equals(other.CreditDebitIndicator)) &&
                (this.BookingDate == null && other.BookingDate == null ||
                 this.BookingDate?.Equals(other.BookingDate) == true) &&
                (this.ValueDate == null && other.ValueDate == null ||
                 this.ValueDate?.Equals(other.ValueDate) == true) &&
                (this.BankTransactionCode == null && other.BankTransactionCode == null ||
                 this.BankTransactionCode?.Equals(other.BankTransactionCode) == true) &&
                (this.Purpose == null && other.Purpose == null ||
                 this.Purpose?.Equals(other.Purpose) == true) &&
                (this.RemittanceInformation == null && other.RemittanceInformation == null ||
                 this.RemittanceInformation?.Equals(other.RemittanceInformation) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"EntryReference = {this.EntryReference ?? "null"}");
            toStringOutput.Add($"References = {(this.References == null ? "null" : this.References.ToString())}");
            toStringOutput.Add($"Batch = {(this.Batch == null ? "null" : this.Batch.ToString())}");
            toStringOutput.Add($"Amount = {(this.Amount == null ? "null" : this.Amount.ToString())}");
            toStringOutput.Add($"CreditDebitIndicator = {this.CreditDebitIndicator}");
            toStringOutput.Add($"BookingDate = {(this.BookingDate == null ? "null" : this.BookingDate.ToString())}");
            toStringOutput.Add($"ValueDate = {(this.ValueDate == null ? "null" : this.ValueDate.ToString())}");
            toStringOutput.Add($"BankTransactionCode = {(this.BankTransactionCode == null ? "null" : this.BankTransactionCode.ToString())}");
            toStringOutput.Add($"Purpose = {this.Purpose ?? "null"}");
            toStringOutput.Add($"RemittanceInformation = {(this.RemittanceInformation == null ? "null" : this.RemittanceInformation.ToString())}");
        }
    }
}