// <copyright file="StatementEntryDetails.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// StatementEntryDetails.
    /// </summary>
    public class StatementEntryDetails
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StatementEntryDetails"/> class.
        /// </summary>
        public StatementEntryDetails()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StatementEntryDetails"/> class.
        /// </summary>
        /// <param name="transactionDetails">transaction_details.</param>
        /// <param name="batch">batch.</param>
        public StatementEntryDetails(
            List<Models.StatementTransactionDetails> transactionDetails,
            Models.Batch batch = null)
        {
            this.Batch = batch;
            this.TransactionDetails = transactionDetails;
        }

        /// <summary>
        /// Gets or sets Batch.
        /// </summary>
        [JsonProperty("batch", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Batch Batch { get; set; }

        /// <summary>
        /// Provides information on the underlying transaction(s). This provides a breakdown of the transaction details when the entry is 'batched'. If the entry is not batched and transaction details are to be reported, then transaction details must only occur once.
        /// </summary>
        [JsonProperty("transaction_details")]
        public List<Models.StatementTransactionDetails> TransactionDetails { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"StatementEntryDetails : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is StatementEntryDetails other &&
                (this.Batch == null && other.Batch == null ||
                 this.Batch?.Equals(other.Batch) == true) &&
                (this.TransactionDetails == null && other.TransactionDetails == null ||
                 this.TransactionDetails?.Equals(other.TransactionDetails) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Batch = {(this.Batch == null ? "null" : this.Batch.ToString())}");
            toStringOutput.Add($"TransactionDetails = {(this.TransactionDetails == null ? "null" : $"[{string.Join(", ", this.TransactionDetails)} ]")}");
        }
    }
}