// <copyright file="StatementEntry.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using SwiftBankingAPIPortal.Standard.Models.Containers;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// StatementEntry.
    /// </summary>
    public class StatementEntry
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StatementEntry"/> class.
        /// </summary>
        public StatementEntry()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StatementEntry"/> class.
        /// </summary>
        /// <param name="entryReference">entry_reference.</param>
        /// <param name="amount">amount.</param>
        /// <param name="creditDebitIndicator">credit_debit_indicator.</param>
        /// <param name="status">status.</param>
        /// <param name="valueDate">value_date.</param>
        /// <param name="bankTransactionCode">bank_transaction_code.</param>
        /// <param name="accountServicerReference">account_servicer_reference.</param>
        /// <param name="reversalIndicator">reversal_indicator.</param>
        /// <param name="bookingDate">booking_date.</param>
        /// <param name="availability">availability.</param>
        /// <param name="amountDetails">amount_details.</param>
        /// <param name="charges">charges.</param>
        /// <param name="entryDetails">entry_details.</param>
        public StatementEntry(
            string entryReference,
            Models.Amount1 amount,
            Models.CreditDebitCodeEnum creditDebitIndicator,
            string status,
            StatementEntryValueDate valueDate,
            Models.BankTransactionCode1 bankTransactionCode,
            string accountServicerReference = null,
            bool? reversalIndicator = false,
            StatementEntryBookingDate bookingDate = null,
            List<Models.CashAvailability> availability = null,
            Models.AmountDetails amountDetails = null,
            Models.Charges1 charges = null,
            Models.EntryDetails entryDetails = null)
        {
            this.EntryReference = entryReference;
            this.AccountServicerReference = accountServicerReference;
            this.Amount = amount;
            this.CreditDebitIndicator = creditDebitIndicator;
            this.ReversalIndicator = reversalIndicator;
            this.Status = status;
            this.BookingDate = bookingDate;
            this.ValueDate = valueDate;
            this.Availability = availability;
            this.BankTransactionCode = bankTransactionCode;
            this.AmountDetails = amountDetails;
            this.Charges = charges;
            this.EntryDetails = entryDetails;
        }

        /// <summary>
        /// Unique reference for the entry. The entry is unique per transaction within the statement. Technical incremental identification of the transaction.
        /// </summary>
        [JsonProperty("entry_reference")]
        public string EntryReference { get; set; }

        /// <summary>
        /// Unique reference as assigned by the account servicing institution to unambiguously identify the entry.
        /// </summary>
        [JsonProperty("account_servicer_reference", NullValueHandling = NullValueHandling.Ignore)]
        public string AccountServicerReference { get; set; }

        /// <summary>
        /// Gets or sets Amount.
        /// </summary>
        [JsonProperty("amount")]
        public Models.Amount1 Amount { get; set; }

        /// <summary>
        /// Gets or sets CreditDebitIndicator.
        /// </summary>
        [JsonProperty("credit_debit_indicator")]
        public Models.CreditDebitCodeEnum CreditDebitIndicator { get; set; }

        /// <summary>
        /// Indicates whether or not the entry is the result of a reversal.
        /// *`Usage:` This element should only be present if the entry is the result of a reversal. If the CreditDebitIndicator is CRDT and ReversalIndicator is Yes, the original operation was a debit entry. If the CreditDebitIndicator is DBIT and ReversalIndicator is Yes, the original operation was a credit entry.
        /// </summary>
        [JsonProperty("reversal_indicator", NullValueHandling = NullValueHandling.Ignore)]
        public bool? ReversalIndicator { get; set; }

        /// <summary>
        /// Specifies the status of an entry on the books of the account servicer, as published in an external code set. External code sets can be downloaded from www.iso20022.org.
        /// </summary>
        [JsonProperty("status")]
        public string Status { get; set; }

        /// <summary>
        /// Date and time when an entry is posted to an account on the account servicer''s books.
        /// *`Usage:`Booking date is the expected booking date, unless the status is booked, in which case it is the actual booking date.
        /// </summary>
        [JsonProperty("booking_date", NullValueHandling = NullValueHandling.Ignore)]
        public StatementEntryBookingDate BookingDate { get; set; }

        /// <summary>
        /// Date and time at which assets become available to the account owner in case of a credit entry, or cease to be available to the account owner in case of a debit entry.
        /// *`Usage:` If entry status is pending and value date is present, then the value date refers to an expected/requested value date. For entries subject to availability/float and for which availability information is provided, the value date must not be used. In this case the availability component identifies the number of availability days.
        /// </summary>
        [JsonProperty("value_date")]
        public StatementEntryValueDate ValueDate { get; set; }

        /// <summary>
        /// Set of elements used to indicate when the booked amount of money will become available, that is can be accessed and starts generating interest.
        /// Usage: This type of information is used in the US and is linked to particular instruments such as cheques. Example: When a cheque is deposited, it will be booked on the deposit day, but the amount of money will only be accessible as of the indicated availability day (according to national banking regulations).
        /// </summary>
        [JsonProperty("availability", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.CashAvailability> Availability { get; set; }

        /// <summary>
        /// Gets or sets BankTransactionCode.
        /// </summary>
        [JsonProperty("bank_transaction_code")]
        public Models.BankTransactionCode1 BankTransactionCode { get; set; }

        /// <summary>
        /// Gets or sets AmountDetails.
        /// </summary>
        [JsonProperty("amount_details", NullValueHandling = NullValueHandling.Ignore)]
        public Models.AmountDetails AmountDetails { get; set; }

        /// <summary>
        /// Gets or sets Charges.
        /// </summary>
        [JsonProperty("charges", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Charges1 Charges { get; set; }

        /// <summary>
        /// Gets or sets EntryDetails.
        /// </summary>
        [JsonProperty("entry_details", NullValueHandling = NullValueHandling.Ignore)]
        public Models.EntryDetails EntryDetails { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"StatementEntry : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is StatementEntry other &&
                (this.EntryReference == null && other.EntryReference == null ||
                 this.EntryReference?.Equals(other.EntryReference) == true) &&
                (this.AccountServicerReference == null && other.AccountServicerReference == null ||
                 this.AccountServicerReference?.Equals(other.AccountServicerReference) == true) &&
                (this.Amount == null && other.Amount == null ||
                 this.Amount?.Equals(other.Amount) == true) &&
                (this.CreditDebitIndicator.Equals(other.CreditDebitIndicator)) &&
                (this.ReversalIndicator == null && other.ReversalIndicator == null ||
                 this.ReversalIndicator?.Equals(other.ReversalIndicator) == true) &&
                (this.Status == null && other.Status == null ||
                 this.Status?.Equals(other.Status) == true) &&
                (this.BookingDate == null && other.BookingDate == null ||
                 this.BookingDate?.Equals(other.BookingDate) == true) &&
                (this.ValueDate == null && other.ValueDate == null ||
                 this.ValueDate?.Equals(other.ValueDate) == true) &&
                (this.Availability == null && other.Availability == null ||
                 this.Availability?.Equals(other.Availability) == true) &&
                (this.BankTransactionCode == null && other.BankTransactionCode == null ||
                 this.BankTransactionCode?.Equals(other.BankTransactionCode) == true) &&
                (this.AmountDetails == null && other.AmountDetails == null ||
                 this.AmountDetails?.Equals(other.AmountDetails) == true) &&
                (this.Charges == null && other.Charges == null ||
                 this.Charges?.Equals(other.Charges) == true) &&
                (this.EntryDetails == null && other.EntryDetails == null ||
                 this.EntryDetails?.Equals(other.EntryDetails) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"EntryReference = {this.EntryReference ?? "null"}");
            toStringOutput.Add($"AccountServicerReference = {this.AccountServicerReference ?? "null"}");
            toStringOutput.Add($"Amount = {(this.Amount == null ? "null" : this.Amount.ToString())}");
            toStringOutput.Add($"CreditDebitIndicator = {this.CreditDebitIndicator}");
            toStringOutput.Add($"ReversalIndicator = {(this.ReversalIndicator == null ? "null" : this.ReversalIndicator.ToString())}");
            toStringOutput.Add($"Status = {this.Status ?? "null"}");
            toStringOutput.Add($"BookingDate = {(this.BookingDate == null ? "null" : this.BookingDate.ToString())}");
            toStringOutput.Add($"ValueDate = {(this.ValueDate == null ? "null" : this.ValueDate.ToString())}");
            toStringOutput.Add($"Availability = {(this.Availability == null ? "null" : $"[{string.Join(", ", this.Availability)} ]")}");
            toStringOutput.Add($"BankTransactionCode = {(this.BankTransactionCode == null ? "null" : this.BankTransactionCode.ToString())}");
            toStringOutput.Add($"AmountDetails = {(this.AmountDetails == null ? "null" : this.AmountDetails.ToString())}");
            toStringOutput.Add($"Charges = {(this.Charges == null ? "null" : this.Charges.ToString())}");
            toStringOutput.Add($"EntryDetails = {(this.EntryDetails == null ? "null" : this.EntryDetails.ToString())}");
        }
    }
}