// <copyright file="Statement.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// Statement.
    /// </summary>
    public class Statement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Statement"/> class.
        /// </summary>
        public Statement()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Statement"/> class.
        /// </summary>
        /// <param name="identification">identification.</param>
        /// <param name="statementPeriod">statement_period.</param>
        /// <param name="account">account.</param>
        /// <param name="balance">balance.</param>
        /// <param name="creationDateTime">creation_date_time.</param>
        /// <param name="fromDateTime">from_date_time.</param>
        /// <param name="toDateTime">to_date_time.</param>
        /// <param name="relatedAccount">related_account.</param>
        /// <param name="interest">interest.</param>
        /// <param name="statementEntry">statement_entry.</param>
        /// <param name="links">links.</param>
        public Statement(
            string identification,
            Models.StatementPeriodEnum statementPeriod,
            Models.Account1 account,
            List<Models.Balance> balance,
            string creationDateTime = null,
            string fromDateTime = null,
            string toDateTime = null,
            Models.RelatedAccount relatedAccount = null,
            List<Models.AccountInterest> interest = null,
            List<Models.StatementEntry> statementEntry = null,
            List<Models.Link> links = null)
        {
            this.Identification = identification;
            this.CreationDateTime = creationDateTime;
            this.FromDateTime = fromDateTime;
            this.ToDateTime = toDateTime;
            this.StatementPeriod = statementPeriod;
            this.Account = account;
            this.RelatedAccount = relatedAccount;
            this.Interest = interest;
            this.Balance = balance;
            this.StatementEntry = statementEntry;
            this.Links = links;
        }

        /// <summary>
        /// Unique identification, as assigned by the account servicer, to unambiguously identify the account statement.
        /// </summary>
        [JsonProperty("identification")]
        public string Identification { get; set; }

        /// <summary>
        /// A particular point in the progression of time defined by a mandatory date and a mandatory time component, expressed in either UTC time format (YYYY-MM-DDThh:mm:ss.sssZ), local time with UTC offset format (YYYY-MM-DDThh:mm:ss.sss+/-hh:mm), or local time format (YYYY-MM-DDThh:mm:ss.sss). These representations are defined in "XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004" which is aligned with ISO 8601.
        /// Note on the time format:
        /// 1) beginning / end of calendar day
        /// 00:00:00 = the beginning of a calendar day
        /// 24:00:00 = the end of a calendar day
        /// 2) fractions of second in time format
        /// Decimal fractions of seconds may be included. In this case, the involved parties shall agree on the maximum number of digits that are allowed.
        /// </summary>
        [JsonProperty("creation_date_time", NullValueHandling = NullValueHandling.Ignore)]
        public string CreationDateTime { get; set; }

        /// <summary>
        /// A particular point in the progression of time defined by a mandatory date and a mandatory time component, expressed in either UTC time format (YYYY-MM-DDThh:mm:ss.sssZ), local time with UTC offset format (YYYY-MM-DDThh:mm:ss.sss+/-hh:mm), or local time format (YYYY-MM-DDThh:mm:ss.sss). These representations are defined in "XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004" which is aligned with ISO 8601.
        /// Note on the time format:
        /// 1) beginning / end of calendar day
        /// 00:00:00 = the beginning of a calendar day
        /// 24:00:00 = the end of a calendar day
        /// 2) fractions of second in time format
        /// Decimal fractions of seconds may be included. In this case, the involved parties shall agree on the maximum number of digits that are allowed.
        /// </summary>
        [JsonProperty("from_date_time", NullValueHandling = NullValueHandling.Ignore)]
        public string FromDateTime { get; set; }

        /// <summary>
        /// A particular point in the progression of time defined by a mandatory date and a mandatory time component, expressed in either UTC time format (YYYY-MM-DDThh:mm:ss.sssZ), local time with UTC offset format (YYYY-MM-DDThh:mm:ss.sss+/-hh:mm), or local time format (YYYY-MM-DDThh:mm:ss.sss). These representations are defined in "XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004" which is aligned with ISO 8601.
        /// Note on the time format:
        /// 1) beginning / end of calendar day
        /// 00:00:00 = the beginning of a calendar day
        /// 24:00:00 = the end of a calendar day
        /// 2) fractions of second in time format
        /// Decimal fractions of seconds may be included. In this case, the involved parties shall agree on the maximum number of digits that are allowed.
        /// </summary>
        [JsonProperty("to_date_time", NullValueHandling = NullValueHandling.Ignore)]
        public string ToDateTime { get; set; }

        /// <summary>
        /// Gets or sets StatementPeriod.
        /// </summary>
        [JsonProperty("statement_period")]
        public Models.StatementPeriodEnum StatementPeriod { get; set; }

        /// <summary>
        /// Gets or sets Account.
        /// </summary>
        [JsonProperty("account")]
        public Models.Account1 Account { get; set; }

        /// <summary>
        /// Gets or sets RelatedAccount.
        /// </summary>
        [JsonProperty("related_account", NullValueHandling = NullValueHandling.Ignore)]
        public Models.RelatedAccount RelatedAccount { get; set; }

        /// <summary>
        /// Provides general interest information that applies to the account at a particular moment in time.
        /// </summary>
        [JsonProperty("interest", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.AccountInterest> Interest { get; set; }

        /// <summary>
        /// Set of elements used to define the balance as a numerical representation of the net increases and decreases in an account at a specific point in time.
        /// Usage - Required balance types - OPBD = OpeningBooked with date on which the opening balance was determined CLBD = ClosingBooked. Rest of the balance types must be bilaterally determined.
        /// </summary>
        [JsonProperty("balance")]
        public List<Models.Balance> Balance { get; set; }

        /// <summary>
        /// Specifies an entry in the Statement. For reporting single transaction or batch.
        /// Usage - At least one reference must be provided to identify the entry and its underlying transaction(s).
        /// </summary>
        [JsonProperty("statement_entry", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.StatementEntry> StatementEntry { get; set; }

        /// <summary>
        /// Gets or sets Links.
        /// </summary>
        [JsonProperty("links", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.Link> Links { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Statement : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is Statement other &&
                (this.Identification == null && other.Identification == null ||
                 this.Identification?.Equals(other.Identification) == true) &&
                (this.CreationDateTime == null && other.CreationDateTime == null ||
                 this.CreationDateTime?.Equals(other.CreationDateTime) == true) &&
                (this.FromDateTime == null && other.FromDateTime == null ||
                 this.FromDateTime?.Equals(other.FromDateTime) == true) &&
                (this.ToDateTime == null && other.ToDateTime == null ||
                 this.ToDateTime?.Equals(other.ToDateTime) == true) &&
                (this.StatementPeriod.Equals(other.StatementPeriod)) &&
                (this.Account == null && other.Account == null ||
                 this.Account?.Equals(other.Account) == true) &&
                (this.RelatedAccount == null && other.RelatedAccount == null ||
                 this.RelatedAccount?.Equals(other.RelatedAccount) == true) &&
                (this.Interest == null && other.Interest == null ||
                 this.Interest?.Equals(other.Interest) == true) &&
                (this.Balance == null && other.Balance == null ||
                 this.Balance?.Equals(other.Balance) == true) &&
                (this.StatementEntry == null && other.StatementEntry == null ||
                 this.StatementEntry?.Equals(other.StatementEntry) == true) &&
                (this.Links == null && other.Links == null ||
                 this.Links?.Equals(other.Links) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Identification = {this.Identification ?? "null"}");
            toStringOutput.Add($"CreationDateTime = {this.CreationDateTime ?? "null"}");
            toStringOutput.Add($"FromDateTime = {this.FromDateTime ?? "null"}");
            toStringOutput.Add($"ToDateTime = {this.ToDateTime ?? "null"}");
            toStringOutput.Add($"StatementPeriod = {this.StatementPeriod}");
            toStringOutput.Add($"Account = {(this.Account == null ? "null" : this.Account.ToString())}");
            toStringOutput.Add($"RelatedAccount = {(this.RelatedAccount == null ? "null" : this.RelatedAccount.ToString())}");
            toStringOutput.Add($"Interest = {(this.Interest == null ? "null" : $"[{string.Join(", ", this.Interest)} ]")}");
            toStringOutput.Add($"Balance = {(this.Balance == null ? "null" : $"[{string.Join(", ", this.Balance)} ]")}");
            toStringOutput.Add($"StatementEntry = {(this.StatementEntry == null ? "null" : $"[{string.Join(", ", this.StatementEntry)} ]")}");
            toStringOutput.Add($"Links = {(this.Links == null ? "null" : $"[{string.Join(", ", this.Links)} ]")}");
        }
    }
}