// <copyright file="StatementPeriodEnum.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// StatementPeriodEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum StatementPeriodEnum
    {
        /// <summary>
        /// EODY.
        /// </summary>
        [EnumMember(Value = "EODY")]
        EODY,

        /// <summary>
        /// EOWK.
        /// </summary>
        [EnumMember(Value = "EOWK")]
        EOWK,

        /// <summary>
        /// EOMH.
        /// </summary>
        [EnumMember(Value = "EOMH")]
        EOMH,

        /// <summary>
        /// EOYR.
        /// </summary>
        [EnumMember(Value = "EOYR")]
        EOYR
    }
}