// <copyright file="TaxCharges.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// TaxCharges.
    /// </summary>
    public class TaxCharges
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TaxCharges"/> class.
        /// </summary>
        public TaxCharges()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TaxCharges"/> class.
        /// </summary>
        /// <param name="identification">identification.</param>
        /// <param name="rate">rate.</param>
        /// <param name="amount">amount.</param>
        public TaxCharges(
            string identification = null,
            string rate = null,
            Models.Amount amount = null)
        {
            this.Identification = identification;
            this.Rate = rate;
            this.Amount = amount;
        }

        /// <summary>
        /// Unique reference to unambiguously identify the nature of the tax levied, such as Value Added Tax (VAT).
        /// </summary>
        [JsonProperty("identification", NullValueHandling = NullValueHandling.Ignore)]
        public string Identification { get; set; }

        /// <summary>
        /// Rate expressed as a percentage, that is, in hundredths, for example, 0.7 is 7/10 of a percent, and 7.0 is 7%.
        /// </summary>
        [JsonProperty("rate", NullValueHandling = NullValueHandling.Ignore)]
        public string Rate { get; set; }

        /// <summary>
        /// Gets or sets Amount.
        /// </summary>
        [JsonProperty("amount", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Amount Amount { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"TaxCharges : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is TaxCharges other &&
                (this.Identification == null && other.Identification == null ||
                 this.Identification?.Equals(other.Identification) == true) &&
                (this.Rate == null && other.Rate == null ||
                 this.Rate?.Equals(other.Rate) == true) &&
                (this.Amount == null && other.Amount == null ||
                 this.Amount?.Equals(other.Amount) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Identification = {this.Identification ?? "null"}");
            toStringOutput.Add($"Rate = {this.Rate ?? "null"}");
            toStringOutput.Add($"Amount = {(this.Amount == null ? "null" : this.Amount.ToString())}");
        }
    }
}