// <copyright file="ToAmount.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// ToAmount.
    /// </summary>
    public class ToAmount
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ToAmount"/> class.
        /// </summary>
        public ToAmount()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ToAmount"/> class.
        /// </summary>
        /// <param name="boundaryAmount">boundary_amount.</param>
        /// <param name="included">included.</param>
        public ToAmount(
            string boundaryAmount,
            bool included)
        {
            this.BoundaryAmount = boundaryAmount;
            this.Included = included;
        }

        /// <summary>
        /// Number of monetary units specified in a currency where the unit of currency is implied by the context and compliant with ISO 4217. The decimal separator is a dot.
        /// Note: a zero amount is considered a positive amount.
        /// </summary>
        [JsonProperty("boundary_amount")]
        public string BoundaryAmount { get; set; }

        /// <summary>
        /// Indicates whether the boundary amount is included in the range of amount values.
        /// </summary>
        [JsonProperty("included")]
        public bool Included { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ToAmount : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ToAmount other &&
                (this.BoundaryAmount == null && other.BoundaryAmount == null ||
                 this.BoundaryAmount?.Equals(other.BoundaryAmount) == true) &&
                (this.Included.Equals(other.Included));
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"BoundaryAmount = {this.BoundaryAmount ?? "null"}");
            toStringOutput.Add($"Included = {this.Included}");
        }
    }
}