// <copyright file="TotalCreditEntries.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard.Models
{
    /// <summary>
    /// TotalCreditEntries.
    /// </summary>
    public class TotalCreditEntries
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TotalCreditEntries"/> class.
        /// </summary>
        public TotalCreditEntries()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TotalCreditEntries"/> class.
        /// </summary>
        /// <param name="numberOfEntries">number_of_entries.</param>
        /// <param name="total">total.</param>
        public TotalCreditEntries(
            string numberOfEntries,
            Models.Total total)
        {
            this.NumberOfEntries = numberOfEntries;
            this.Total = total;
        }

        /// <summary>
        /// Specifies a numeric string with a maximum length of 15 digits.
        /// </summary>
        [JsonProperty("number_of_entries")]
        public string NumberOfEntries { get; set; }

        /// <summary>
        /// Gets or sets Total.
        /// </summary>
        [JsonProperty("total")]
        public Models.Total Total { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"TotalCreditEntries : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is TotalCreditEntries other &&
                (this.NumberOfEntries == null && other.NumberOfEntries == null ||
                 this.NumberOfEntries?.Equals(other.NumberOfEntries) == true) &&
                (this.Total == null && other.Total == null ||
                 this.Total?.Equals(other.Total) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"NumberOfEntries = {this.NumberOfEntries ?? "null"}");
            toStringOutput.Add($"Total = {(this.Total == null ? "null" : this.Total.ToString())}");
        }
    }
}