// <copyright file="AccountInformationController.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Utilities;
using SwiftBankingAPIPortal.Standard.Exceptions;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace SwiftBankingAPIPortal.Standard.Controllers
{
    /// <summary>
    /// AccountInformationController.
    /// </summary>
    public class AccountInformationController : BaseController
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountInformationController"/> class.
        /// </summary>
        internal AccountInformationController(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// <![CDATA[
        /// The endpoint will retrieve all accounts with balance information for a specific account owner meeting the query parameters when supplied. The endpoint will return an empty array when no resource is found.
        /// **Specifying Request Filter**.
        /// Parameters are specified in the form name=value. A parameter list is appended to a URI after a "?". Multiple parameters are separated by "&".
        /// `Note that the query parameters are not URL encoded for readability.`.
        /// **Use of logical operator OR (account-identification DE27212110090000000235698765 or DE27212318890001010223463456)**.
        /// https://developer.swift.com/accounts?account-identification=DE27212110090000000235698765,DE27212318890001010223463456&limit=25&offset=0   .
        /// **Use of logical operator AND (account-servicer and account-identification)**.
        /// https://developer.swift.com/accounts?account-servicer=DEUTDEFF&account-identification=DE27212110090000000235698765&currency=EUR&limit=25&offset=0       .
        /// ]]>
        /// </summary>
        /// <param name="xBIC">Required parameter: Specify the BIC of the provider of the service. The identification will be used by the API Gateway to forward the request to service provider..</param>
        /// <param name="xRequestID">Optional parameter: Specify an unique end to end tracking request ID. The element will be populated by the SWIFT API gateway.</param>
        /// <param name="xUserContext">Optional parameter: Provides requester entitlement information to service provider. A JWT containing a claim representing the entitlements of the API consumer as defined at the SWIFT Identity Provider. This header is provided by the SWIFT API Gateway and is not required to be provided by the API consumer..</param>
        /// <param name="accountIdentification">Optional parameter: Unique and unambiguous identification for the account between the account owner and the account servicer. It can be in IBAN or proprietary format.  RECOMMENDATION IN ORDER OF PREFERENCE: IBAN - International Bank Account Number (IBAN) - identifier used internationally by financial institutions to uniquely identify the account of a customer. Further specifications of the format and content of the IBAN can be found in the standard ISO 13616 "Banking and related financial services - International Bank Account Number (IBAN)" version 1997-10-01, or later revisions. When available IBAN must be specified for instance endpoint or hyper link to work.  Other - Identifier used nationally by financial institutions, i.e., in individual countries, generally as part of a National Account Numbering Scheme(s), to uniquely identify the account of a customer. In the absence of IBAN, this must be an unique account identification used for routing of the payment to the account via clearing system. A format which is agreed between the account owner and the account servicer. For example a SWIFT BIC/Branch Code and Account number..</param>
        /// <param name="accountServicer">Optional parameter: Party that manages the account on behalf of the account owner, that is manages the registration and booking of entries on the account, calculates balances on the account and provides information about the account. Valid BICs for financial institutions are registered and published by the ISO 9362 Registration Authority in the ISO directory of BICs, and consist of eight (8) or eleven (11) contiguous characters.  Usage - The parameter provides the ability to a consumer requesting account related to a specific BIC..</param>
        /// <param name="currency">Optional parameter: Specifies the currency of the account. The Currency Code must be registered, or have already been registered with the ISO 4217 Maintenance Agency, consist of three (3) contiguous letters, and may be or not be withdrawn on the day the message containing the Currency is exchanged..</param>
        /// <param name="offset">Optional parameter: Specifies the offset / starting point in the list of all available items, starting from which results will be returned. The numeric offset identifies the page token, allowing users to advance to the next page in the collection. The value 0 (zero) identifies the first page of entry..</param>
        /// <param name="limit">Optional parameter: The maximum number of items to return in a page. If unspecified, the default limit will be returned. If the limit specified is greater than the maximum permitted by the API, the API will return the maximum permitted limit. Each API should define *maximum and *default limit..</param>
        /// <returns>Returns the Models.AccountsResponse response from the API call.</returns>
        public Models.AccountsResponse GetAccounts(
                string xBIC,
                string xRequestID = null,
                string xUserContext = null,
                List<string> accountIdentification = null,
                List<string> accountServicer = null,
                string currency = null,
                int? offset = 0,
                int? limit = null)
            => CoreHelper.RunTask(GetAccountsAsync(xBIC, xRequestID, xUserContext, accountIdentification, accountServicer, currency, offset, limit));

        /// <summary>
        /// <![CDATA[
        /// The endpoint will retrieve all accounts with balance information for a specific account owner meeting the query parameters when supplied. The endpoint will return an empty array when no resource is found.
        /// **Specifying Request Filter**.
        /// Parameters are specified in the form name=value. A parameter list is appended to a URI after a "?". Multiple parameters are separated by "&".
        /// `Note that the query parameters are not URL encoded for readability.`.
        /// **Use of logical operator OR (account-identification DE27212110090000000235698765 or DE27212318890001010223463456)**.
        /// https://developer.swift.com/accounts?account-identification=DE27212110090000000235698765,DE27212318890001010223463456&limit=25&offset=0   .
        /// **Use of logical operator AND (account-servicer and account-identification)**.
        /// https://developer.swift.com/accounts?account-servicer=DEUTDEFF&account-identification=DE27212110090000000235698765&currency=EUR&limit=25&offset=0       .
        /// ]]>
        /// </summary>
        /// <param name="xBIC">Required parameter: Specify the BIC of the provider of the service. The identification will be used by the API Gateway to forward the request to service provider..</param>
        /// <param name="xRequestID">Optional parameter: Specify an unique end to end tracking request ID. The element will be populated by the SWIFT API gateway.</param>
        /// <param name="xUserContext">Optional parameter: Provides requester entitlement information to service provider. A JWT containing a claim representing the entitlements of the API consumer as defined at the SWIFT Identity Provider. This header is provided by the SWIFT API Gateway and is not required to be provided by the API consumer..</param>
        /// <param name="accountIdentification">Optional parameter: Unique and unambiguous identification for the account between the account owner and the account servicer. It can be in IBAN or proprietary format.  RECOMMENDATION IN ORDER OF PREFERENCE: IBAN - International Bank Account Number (IBAN) - identifier used internationally by financial institutions to uniquely identify the account of a customer. Further specifications of the format and content of the IBAN can be found in the standard ISO 13616 "Banking and related financial services - International Bank Account Number (IBAN)" version 1997-10-01, or later revisions. When available IBAN must be specified for instance endpoint or hyper link to work.  Other - Identifier used nationally by financial institutions, i.e., in individual countries, generally as part of a National Account Numbering Scheme(s), to uniquely identify the account of a customer. In the absence of IBAN, this must be an unique account identification used for routing of the payment to the account via clearing system. A format which is agreed between the account owner and the account servicer. For example a SWIFT BIC/Branch Code and Account number..</param>
        /// <param name="accountServicer">Optional parameter: Party that manages the account on behalf of the account owner, that is manages the registration and booking of entries on the account, calculates balances on the account and provides information about the account. Valid BICs for financial institutions are registered and published by the ISO 9362 Registration Authority in the ISO directory of BICs, and consist of eight (8) or eleven (11) contiguous characters.  Usage - The parameter provides the ability to a consumer requesting account related to a specific BIC..</param>
        /// <param name="currency">Optional parameter: Specifies the currency of the account. The Currency Code must be registered, or have already been registered with the ISO 4217 Maintenance Agency, consist of three (3) contiguous letters, and may be or not be withdrawn on the day the message containing the Currency is exchanged..</param>
        /// <param name="offset">Optional parameter: Specifies the offset / starting point in the list of all available items, starting from which results will be returned. The numeric offset identifies the page token, allowing users to advance to the next page in the collection. The value 0 (zero) identifies the first page of entry..</param>
        /// <param name="limit">Optional parameter: The maximum number of items to return in a page. If unspecified, the default limit will be returned. If the limit specified is greater than the maximum permitted by the API, the API will return the maximum permitted limit. Each API should define *maximum and *default limit..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the Models.AccountsResponse response from the API call.</returns>
        public async Task<Models.AccountsResponse> GetAccountsAsync(
                string xBIC,
                string xRequestID = null,
                string xUserContext = null,
                List<string> accountIdentification = null,
                List<string> accountServicer = null,
                string currency = null,
                int? offset = 0,
                int? limit = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.AccountsResponse>()
              .Server(Server.AutoMockingServer)
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/accounts")
                  .WithAuth("oauthBearerToken")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("X-BIC", xBIC))
                      .Header(header => header.Setup("X-Request-ID", xRequestID))
                      .Header(header => header.Setup("X-UserContext", xUserContext))
                      .Query(query => query.Setup("account-identification", accountIdentification))
                      .Query(query => query.Setup("account-servicer", accountServicer))
                      .Query(query => query.Setup("currency", currency))
                      .Query(query => query.Setup("offset", offset ?? 0))
                      .Query(query => query.Setup("limit", limit))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Bad Request", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("401", CreateErrorCase("Unauthorized", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("403", CreateErrorCase("Forbidden", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("406", CreateErrorCase("Not Acceptable", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("415", CreateErrorCase("Unsupported Media Type", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("429", CreateErrorCase("Too Many Requests", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("500", CreateErrorCase("Internal Server Error", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("502", CreateErrorCase("Bad Gateway", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("503", CreateErrorCase("Service Unavailable", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("504", CreateErrorCase("Gateway Timeout", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("0", CreateErrorCase("Internal Server Error", (errorReason, context) => new ErrorMessageException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// The endpoint will retrieve the account with balance information based on a specific account identification.
        /// </summary>
        /// <param name="xBIC">Required parameter: Specify the BIC of the provider of the service. The identification will be used by the API Gateway to forward the request to service provider..</param>
        /// <param name="accountIdentification">Required parameter: An unique and unambiguous identification for the account as assigned by the account servicer. It can be in IBAN or proprietary format.  RECOMMENDATION IN ORDER OF PREFERENCE: IBAN - When available IBAN must be specified for instance endpoint or hyper link to work. Other - In the absence of IBAN, this must be an unique account identification used for routing of the payment to the account via clearing system. A format which is agreed between the account owner and the account servicer. For example a SWIFT BIC/Branch Code and Account number..</param>
        /// <param name="xRequestID">Optional parameter: Specify an unique end to end tracking request ID. The element will be populated by the SWIFT API gateway.</param>
        /// <param name="xUserContext">Optional parameter: Provides requester entitlement information to service provider. A JWT containing a claim representing the entitlements of the API consumer as defined at the SWIFT Identity Provider. This header is provided by the SWIFT API Gateway and is not required to be provided by the API consumer..</param>
        /// <returns>Returns the Models.AccountsResponse2 response from the API call.</returns>
        public Models.AccountsResponse2 GetAccount(
                string xBIC,
                string accountIdentification,
                string xRequestID = null,
                string xUserContext = null)
            => CoreHelper.RunTask(GetAccountAsync(xBIC, accountIdentification, xRequestID, xUserContext));

        /// <summary>
        /// The endpoint will retrieve the account with balance information based on a specific account identification.
        /// </summary>
        /// <param name="xBIC">Required parameter: Specify the BIC of the provider of the service. The identification will be used by the API Gateway to forward the request to service provider..</param>
        /// <param name="accountIdentification">Required parameter: An unique and unambiguous identification for the account as assigned by the account servicer. It can be in IBAN or proprietary format.  RECOMMENDATION IN ORDER OF PREFERENCE: IBAN - When available IBAN must be specified for instance endpoint or hyper link to work. Other - In the absence of IBAN, this must be an unique account identification used for routing of the payment to the account via clearing system. A format which is agreed between the account owner and the account servicer. For example a SWIFT BIC/Branch Code and Account number..</param>
        /// <param name="xRequestID">Optional parameter: Specify an unique end to end tracking request ID. The element will be populated by the SWIFT API gateway.</param>
        /// <param name="xUserContext">Optional parameter: Provides requester entitlement information to service provider. A JWT containing a claim representing the entitlements of the API consumer as defined at the SWIFT Identity Provider. This header is provided by the SWIFT API Gateway and is not required to be provided by the API consumer..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the Models.AccountsResponse2 response from the API call.</returns>
        public async Task<Models.AccountsResponse2> GetAccountAsync(
                string xBIC,
                string accountIdentification,
                string xRequestID = null,
                string xUserContext = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.AccountsResponse2>()
              .Server(Server.AutoMockingServer)
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/accounts/{account-identification}")
                  .WithAuth("oauthBearerToken")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("X-BIC", xBIC))
                      .Template(template => template.Setup("account-identification", accountIdentification))
                      .Header(header => header.Setup("X-Request-ID", xRequestID))
                      .Header(header => header.Setup("X-UserContext", xUserContext))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Bad Request", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("401", CreateErrorCase("Unauthorized", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("403", CreateErrorCase("Forbidden", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("Not Found", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("406", CreateErrorCase("Not Acceptable", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("415", CreateErrorCase("Unsupported Media Type", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("429", CreateErrorCase("Too Many Requests", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("500", CreateErrorCase("Internal Server Error", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("502", CreateErrorCase("Bad Gateway", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("503", CreateErrorCase("Service Unavailable", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("504", CreateErrorCase("Gateway Timeout", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("0", CreateErrorCase("Internal Server Error", (errorReason, context) => new ErrorMessageException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// The transaction summary endpoint provides the total net, debit and credit entries.
        /// </summary>
        /// <param name="xBIC">Required parameter: Specify the BIC of the provider of the service. The identification will be used by the API Gateway to forward the request to service provider..</param>
        /// <param name="accountIdentification">Required parameter: An unique and unambiguous identification for the account as assigned by the account servicer. It can be in IBAN or proprietary format.  RECOMMENDATION IN ORDER OF PREFERENCE: IBAN - When available IBAN must be specified for instance endpoint or hyper link to work. Other - In the absence of IBAN, this must be an unique account identification used for routing of the payment to the account via clearing system. A format which is agreed between the account owner and the account servicer. For example a SWIFT BIC/Branch Code and Account number..</param>
        /// <param name="fromDate">Required parameter: The start date for which summary information is requested. The result will be filtered on creation_date_time. Expressed in the YYYY-MM-DD format. The date cannot be in the future..</param>
        /// <param name="xRequestID">Optional parameter: Specify an unique end to end tracking request ID. The element will be populated by the SWIFT API gateway.</param>
        /// <param name="xUserContext">Optional parameter: Provides requester entitlement information to service provider. A JWT containing a claim representing the entitlements of the API consumer as defined at the SWIFT Identity Provider. This header is provided by the SWIFT API Gateway and is not required to be provided by the API consumer..</param>
        /// <param name="toDate">Optional parameter: The end date for which summary information is requested. The result will be filtered on creation_date_time. Expressed in the YYYY-MM-DD format. The date cannot be in the future..</param>
        /// <returns>Returns the Models.AccountsTransactionSummaryResponse response from the API call.</returns>
        public Models.AccountsTransactionSummaryResponse GetTransactionSummary(
                string xBIC,
                string accountIdentification,
                string fromDate,
                string xRequestID = null,
                string xUserContext = null,
                string toDate = null)
            => CoreHelper.RunTask(GetTransactionSummaryAsync(xBIC, accountIdentification, fromDate, xRequestID, xUserContext, toDate));

        /// <summary>
        /// The transaction summary endpoint provides the total net, debit and credit entries.
        /// </summary>
        /// <param name="xBIC">Required parameter: Specify the BIC of the provider of the service. The identification will be used by the API Gateway to forward the request to service provider..</param>
        /// <param name="accountIdentification">Required parameter: An unique and unambiguous identification for the account as assigned by the account servicer. It can be in IBAN or proprietary format.  RECOMMENDATION IN ORDER OF PREFERENCE: IBAN - When available IBAN must be specified for instance endpoint or hyper link to work. Other - In the absence of IBAN, this must be an unique account identification used for routing of the payment to the account via clearing system. A format which is agreed between the account owner and the account servicer. For example a SWIFT BIC/Branch Code and Account number..</param>
        /// <param name="fromDate">Required parameter: The start date for which summary information is requested. The result will be filtered on creation_date_time. Expressed in the YYYY-MM-DD format. The date cannot be in the future..</param>
        /// <param name="xRequestID">Optional parameter: Specify an unique end to end tracking request ID. The element will be populated by the SWIFT API gateway.</param>
        /// <param name="xUserContext">Optional parameter: Provides requester entitlement information to service provider. A JWT containing a claim representing the entitlements of the API consumer as defined at the SWIFT Identity Provider. This header is provided by the SWIFT API Gateway and is not required to be provided by the API consumer..</param>
        /// <param name="toDate">Optional parameter: The end date for which summary information is requested. The result will be filtered on creation_date_time. Expressed in the YYYY-MM-DD format. The date cannot be in the future..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the Models.AccountsTransactionSummaryResponse response from the API call.</returns>
        public async Task<Models.AccountsTransactionSummaryResponse> GetTransactionSummaryAsync(
                string xBIC,
                string accountIdentification,
                string fromDate,
                string xRequestID = null,
                string xUserContext = null,
                string toDate = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.AccountsTransactionSummaryResponse>()
              .Server(Server.AutoMockingServer)
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/accounts/{account-identification}/transaction-summary")
                  .WithAuth("oauthBearerToken")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("X-BIC", xBIC))
                      .Template(template => template.Setup("account-identification", accountIdentification))
                      .Query(query => query.Setup("from-date", fromDate))
                      .Header(header => header.Setup("X-Request-ID", xRequestID))
                      .Header(header => header.Setup("X-UserContext", xUserContext))
                      .Query(query => query.Setup("to-date", toDate))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Bad Request", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("401", CreateErrorCase("Unauthorized", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("403", CreateErrorCase("Forbidden", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("Not Found", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("406", CreateErrorCase("Not Acceptable", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("415", CreateErrorCase("Unsupported Media Type", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("429", CreateErrorCase("Too Many Requests", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("500", CreateErrorCase("Internal Server Error", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("502", CreateErrorCase("Bad Gateway", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("503", CreateErrorCase("Service Unavailable", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("504", CreateErrorCase("Gateway Timeout", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("0", CreateErrorCase("Internal Server Error", (errorReason, context) => new ErrorMessageException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}