// <copyright file="AuthorizationController.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Types;
using APIMatic.Core.Utilities;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace SwiftBankingAPIPortal.Standard.Controllers
{
    /// <summary>
    /// AuthorizationController.
    /// </summary>
    public class AuthorizationController : BaseController
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthorizationController"/> class.
        /// </summary>
        internal AuthorizationController(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// Obtain an OAuth2 token using JWT bearer assertion and Basic Auth.
        /// </summary>
        /// <param name="grantType">Required parameter: .</param>
        /// <param name="assertion">Required parameter: The JWT bearer assertion (auto-generated in Pre-request script).</param>
        /// <param name="scope">Required parameter: .</param>
        public void GetToken(
                string grantType,
                string assertion,
                string scope)
            => CoreHelper.RunVoidTask(GetTokenAsync(grantType, assertion, scope));

        /// <summary>
        /// Obtain an OAuth2 token using JWT bearer assertion and Basic Auth.
        /// </summary>
        /// <param name="grantType">Required parameter: .</param>
        /// <param name="assertion">Required parameter: The JWT bearer assertion (auto-generated in Pre-request script).</param>
        /// <param name="scope">Required parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the void response from the API call.</returns>
        public async Task GetTokenAsync(
                string grantType,
                string assertion,
                string scope,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<VoidType>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/token")
                  .WithAuth("basicAuth")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))
                      .Form(form => form.Setup("grant_type", grantType))
                      .Form(form => form.Setup("assertion", assertion))
                      .Form(form => form.Setup("scope", scope))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}