// <copyright file="ReportingController.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Utilities;
using SwiftBankingAPIPortal.Standard.Exceptions;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace SwiftBankingAPIPortal.Standard.Controllers
{
    /// <summary>
    /// ReportingController.
    /// </summary>
    public class ReportingController : BaseController
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReportingController"/> class.
        /// </summary>
        internal ReportingController(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// The API endpoint is used by the consumer of the API to get entries reported to the account. This will include all debit and/or credit entries booked to the account for the specified period to enable intraday reconciliation. Includes pending and booked items.
        /// Response:.
        /// * The endpoint will return HTTP response code 404 if the requested account does not exists. .
        /// * The endpoint will return an empty array if the requested account exists but no entries found or no entries found by the query criteria. For example "statement_line": [].
        /// </summary>
        /// <param name="xBIC">Required parameter: Specify the BIC of the provider of the service. The identification will be used by the API Gateway to forward the request to service provider..</param>
        /// <param name="accountIdentification">Required parameter: An unique and unambiguous identification for the account as assigned by the account servicer. It can be in IBAN or proprietary format.  RECOMMENDATION IN ORDER OF PREFERENCE: IBAN - When available IBAN must be specified for instance endpoint or hyper link to work. Other - In the absence of IBAN, this must be an unique account identification used for routing of the payment to the account via clearing system. A format which is agreed between the account owner and the account servicer. For example a SWIFT BIC/Branch Code and Account number..</param>
        /// <param name="xRequestID">Optional parameter: Specify an unique end to end tracking request ID. The element will be populated by the SWIFT API gateway.</param>
        /// <param name="xUserContext">Optional parameter: Provides requester entitlement information to service provider. A JWT containing a claim representing the entitlements of the API consumer as defined at the SWIFT Identity Provider. This header is provided by the SWIFT API Gateway and is not required to be provided by the API consumer..</param>
        /// <param name="offset">Optional parameter: Specifies the offset / starting point in the list of all available items, starting from which results will be returned. The numeric offset identifies the page token, allowing users to advance to the next page in the collection. The value 0 (zero) identifies the first page of entry..</param>
        /// <param name="limit">Optional parameter: The maximum number of items to return in a page. If unspecified, the default limit will be returned. If the limit specified is greater than the maximum permitted by the API, the API will return the maximum permitted limit. Each API should define *maximum and *default limit..</param>
        /// <param name="creationFromTime">Optional parameter: A particular point in the progression of time in a calendar day expressed in local time format (hh:mm:ss.sss). These representations are aligned with ISO 8601. Note on the time format: * beginning / end of calendar day 00:00:00 = the beginning of a calendar day 24:00:00 = the end of a calendar day * fractions of second in time format Decimal fractions of seconds may be included. In this case, the involved parties shall agree on the maximum number of digits that are allowed. * If the parameter is omitted, all entries from the beginning of the day will be included.  The result will be filtered on creation_date_time of the entry..</param>
        /// <param name="creationToTime">Optional parameter: A particular point in the progression of time in a calendar day expressed in local time format (hh:mm:ss.sss). These representations are aligned with ISO 8601. Note on the time format: * beginning / end of calendar day 00:00:00 = the beginning of a calendar day 24:00:00 = the end of a calendar day * fractions of second in time format Decimal fractions of seconds may be included. In this case, the involved parties shall agree on the maximum number of digits that are allowed. * If the parameter is omitted, all entries from the beginning of the day up to the request time will be included.  The query parameter can use either a specific creation_from_time or time range in the form of creation_from_time and creation_to_time. For up to a requested time, creation_to_time must not be provided. The result will be filtered on creation_date_time..</param>
        /// <param name="creditDebitCode">Optional parameter: Specifies if an operation is an increase or a decrease. *`CRDT_credit`-Operation is an increase. *`DBIT_debit`-Operation is a decrease..</param>
        /// <returns>Returns the Models.AccountsStatementLinesResponse response from the API call.</returns>
        public Models.AccountsStatementLinesResponse GetStatementLines(
                string xBIC,
                string accountIdentification,
                string xRequestID = null,
                string xUserContext = null,
                int? offset = 0,
                int? limit = null,
                string creationFromTime = null,
                string creationToTime = null,
                Models.CreditDebitCodeEnum? creditDebitCode = null)
            => CoreHelper.RunTask(GetStatementLinesAsync(xBIC, accountIdentification, xRequestID, xUserContext, offset, limit, creationFromTime, creationToTime, creditDebitCode));

        /// <summary>
        /// The API endpoint is used by the consumer of the API to get entries reported to the account. This will include all debit and/or credit entries booked to the account for the specified period to enable intraday reconciliation. Includes pending and booked items.
        /// Response:.
        /// * The endpoint will return HTTP response code 404 if the requested account does not exists. .
        /// * The endpoint will return an empty array if the requested account exists but no entries found or no entries found by the query criteria. For example "statement_line": [].
        /// </summary>
        /// <param name="xBIC">Required parameter: Specify the BIC of the provider of the service. The identification will be used by the API Gateway to forward the request to service provider..</param>
        /// <param name="accountIdentification">Required parameter: An unique and unambiguous identification for the account as assigned by the account servicer. It can be in IBAN or proprietary format.  RECOMMENDATION IN ORDER OF PREFERENCE: IBAN - When available IBAN must be specified for instance endpoint or hyper link to work. Other - In the absence of IBAN, this must be an unique account identification used for routing of the payment to the account via clearing system. A format which is agreed between the account owner and the account servicer. For example a SWIFT BIC/Branch Code and Account number..</param>
        /// <param name="xRequestID">Optional parameter: Specify an unique end to end tracking request ID. The element will be populated by the SWIFT API gateway.</param>
        /// <param name="xUserContext">Optional parameter: Provides requester entitlement information to service provider. A JWT containing a claim representing the entitlements of the API consumer as defined at the SWIFT Identity Provider. This header is provided by the SWIFT API Gateway and is not required to be provided by the API consumer..</param>
        /// <param name="offset">Optional parameter: Specifies the offset / starting point in the list of all available items, starting from which results will be returned. The numeric offset identifies the page token, allowing users to advance to the next page in the collection. The value 0 (zero) identifies the first page of entry..</param>
        /// <param name="limit">Optional parameter: The maximum number of items to return in a page. If unspecified, the default limit will be returned. If the limit specified is greater than the maximum permitted by the API, the API will return the maximum permitted limit. Each API should define *maximum and *default limit..</param>
        /// <param name="creationFromTime">Optional parameter: A particular point in the progression of time in a calendar day expressed in local time format (hh:mm:ss.sss). These representations are aligned with ISO 8601. Note on the time format: * beginning / end of calendar day 00:00:00 = the beginning of a calendar day 24:00:00 = the end of a calendar day * fractions of second in time format Decimal fractions of seconds may be included. In this case, the involved parties shall agree on the maximum number of digits that are allowed. * If the parameter is omitted, all entries from the beginning of the day will be included.  The result will be filtered on creation_date_time of the entry..</param>
        /// <param name="creationToTime">Optional parameter: A particular point in the progression of time in a calendar day expressed in local time format (hh:mm:ss.sss). These representations are aligned with ISO 8601. Note on the time format: * beginning / end of calendar day 00:00:00 = the beginning of a calendar day 24:00:00 = the end of a calendar day * fractions of second in time format Decimal fractions of seconds may be included. In this case, the involved parties shall agree on the maximum number of digits that are allowed. * If the parameter is omitted, all entries from the beginning of the day up to the request time will be included.  The query parameter can use either a specific creation_from_time or time range in the form of creation_from_time and creation_to_time. For up to a requested time, creation_to_time must not be provided. The result will be filtered on creation_date_time..</param>
        /// <param name="creditDebitCode">Optional parameter: Specifies if an operation is an increase or a decrease. *`CRDT_credit`-Operation is an increase. *`DBIT_debit`-Operation is a decrease..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the Models.AccountsStatementLinesResponse response from the API call.</returns>
        public async Task<Models.AccountsStatementLinesResponse> GetStatementLinesAsync(
                string xBIC,
                string accountIdentification,
                string xRequestID = null,
                string xUserContext = null,
                int? offset = 0,
                int? limit = null,
                string creationFromTime = null,
                string creationToTime = null,
                Models.CreditDebitCodeEnum? creditDebitCode = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.AccountsStatementLinesResponse>()
              .Server(Server.AutoMockingServer)
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/accounts/{account-identification}/statement-lines")
                  .WithAuth("oauthBearerToken")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("X-BIC", xBIC))
                      .Template(template => template.Setup("account-identification", accountIdentification))
                      .Header(header => header.Setup("X-Request-ID", xRequestID))
                      .Header(header => header.Setup("X-UserContext", xUserContext))
                      .Query(query => query.Setup("offset", offset ?? 0))
                      .Query(query => query.Setup("limit", limit))
                      .Query(query => query.Setup("creation-from-time", creationFromTime))
                      .Query(query => query.Setup("creation-to-time", creationToTime))
                      .Query(query => query.Setup("credit-debit-code", (creditDebitCode.HasValue) ? CoreHelper.JsonSerialize(creditDebitCode.Value).Trim('\"') : null))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Bad Request", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("401", CreateErrorCase("Unauthorized", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("403", CreateErrorCase("Forbidden", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("Not Found", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("406", CreateErrorCase("Not Acceptable", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("415", CreateErrorCase("Unsupported Media Type", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("429", CreateErrorCase("Too Many Requests", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("500", CreateErrorCase("Internal Server Error", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("502", CreateErrorCase("Bad Gateway", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("503", CreateErrorCase("Service Unavailable", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("504", CreateErrorCase("Gateway Timeout", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("0", CreateErrorCase("Internal Server Error", (errorReason, context) => new ErrorMessageException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// The API endpoint is used by the consumer of the API to get the entries booked to the account, and the balance information on the account at a given period in time. Provides underlying details of transactions that have been included in the entry. Corporate can receive information from their bank(s) about the activity happening on a given account for cash management balance reporting. This will include all entries booked to the account for the specified period. It contains information on booked entries only.
        /// Response:.
        /// * The endpoint will return HTTP response code 404 if the requested account does not exists. .
        /// * The endpoint will return an empty array if the requested account exists but no statement found or no statement found by the query criteria. .
        /// </summary>
        /// <param name="xBIC">Required parameter: Specify the BIC of the provider of the service. The identification will be used by the API Gateway to forward the request to service provider..</param>
        /// <param name="accountIdentification">Required parameter: An unique and unambiguous identification for the account as assigned by the account servicer. It can be in IBAN or proprietary format.  RECOMMENDATION IN ORDER OF PREFERENCE: IBAN - When available IBAN must be specified for instance endpoint or hyper link to work. Other - In the absence of IBAN, this must be an unique account identification used for routing of the payment to the account via clearing system. A format which is agreed between the account owner and the account servicer. For example a SWIFT BIC/Branch Code and Account number..</param>
        /// <param name="fromDate">Required parameter: The query parameter can use either a specific creation_from_date or date range in the form of creation_from_date and creation_to_date. The result will be filtered on creation_date_time. Expressed in the YYYY-MM-DD format. The date cannot be in the future.  Usage - The parameter is mandatory and default behaviour is to provide the end of day statement for the current date. When used in conjunction with statement-period (weekly, monthly, yearly), returns the statement where the from date fall within that period..</param>
        /// <param name="xRequestID">Optional parameter: Specify an unique end to end tracking request ID. The element will be populated by the SWIFT API gateway.</param>
        /// <param name="xUserContext">Optional parameter: Provides requester entitlement information to service provider. A JWT containing a claim representing the entitlements of the API consumer as defined at the SWIFT Identity Provider. This header is provided by the SWIFT API Gateway and is not required to be provided by the API consumer..</param>
        /// <param name="offset">Optional parameter: Specifies the offset / starting point in the list of all available items, starting from which results will be returned. The numeric offset identifies the page token, allowing users to advance to the next page in the collection. The value 0 (zero) identifies the first page of entry..</param>
        /// <param name="limit">Optional parameter: The maximum number of items to return in a page. If unspecified, the default limit will be returned. If the limit specified is greater than the maximum permitted by the API, the API will return the maximum permitted limit. Each API should define *maximum and *default limit..</param>
        /// <param name="toDate">Optional parameter: The query parameter can use either a specific creation_from_date or date range in the form of creation_from_date and creation_to_date. For a specific date, creation_to_date must not be provided. The result will be filtered on creation_date_time. Expressed in the YYYY-MM-DD format. The date cannot be in the future.  Usage - When used in conjunction with the statement-period (weekly, monthly, yearly) and from date,  the endpoint returns the statement where the from date to date fall within that period. The parameter must not be used for the statement period EODY. If supplied, the parameter will be ignored..</param>
        /// <returns>Returns the Models.AccountsStatementsResponse response from the API call.</returns>
        public Models.AccountsStatementsResponse GetAccountStatement(
                string xBIC,
                string accountIdentification,
                string fromDate,
                string xRequestID = null,
                string xUserContext = null,
                int? offset = 0,
                int? limit = null,
                string toDate = null)
            => CoreHelper.RunTask(GetAccountStatementAsync(xBIC, accountIdentification, fromDate, xRequestID, xUserContext, offset, limit, toDate));

        /// <summary>
        /// The API endpoint is used by the consumer of the API to get the entries booked to the account, and the balance information on the account at a given period in time. Provides underlying details of transactions that have been included in the entry. Corporate can receive information from their bank(s) about the activity happening on a given account for cash management balance reporting. This will include all entries booked to the account for the specified period. It contains information on booked entries only.
        /// Response:.
        /// * The endpoint will return HTTP response code 404 if the requested account does not exists. .
        /// * The endpoint will return an empty array if the requested account exists but no statement found or no statement found by the query criteria. .
        /// </summary>
        /// <param name="xBIC">Required parameter: Specify the BIC of the provider of the service. The identification will be used by the API Gateway to forward the request to service provider..</param>
        /// <param name="accountIdentification">Required parameter: An unique and unambiguous identification for the account as assigned by the account servicer. It can be in IBAN or proprietary format.  RECOMMENDATION IN ORDER OF PREFERENCE: IBAN - When available IBAN must be specified for instance endpoint or hyper link to work. Other - In the absence of IBAN, this must be an unique account identification used for routing of the payment to the account via clearing system. A format which is agreed between the account owner and the account servicer. For example a SWIFT BIC/Branch Code and Account number..</param>
        /// <param name="fromDate">Required parameter: The query parameter can use either a specific creation_from_date or date range in the form of creation_from_date and creation_to_date. The result will be filtered on creation_date_time. Expressed in the YYYY-MM-DD format. The date cannot be in the future.  Usage - The parameter is mandatory and default behaviour is to provide the end of day statement for the current date. When used in conjunction with statement-period (weekly, monthly, yearly), returns the statement where the from date fall within that period..</param>
        /// <param name="xRequestID">Optional parameter: Specify an unique end to end tracking request ID. The element will be populated by the SWIFT API gateway.</param>
        /// <param name="xUserContext">Optional parameter: Provides requester entitlement information to service provider. A JWT containing a claim representing the entitlements of the API consumer as defined at the SWIFT Identity Provider. This header is provided by the SWIFT API Gateway and is not required to be provided by the API consumer..</param>
        /// <param name="offset">Optional parameter: Specifies the offset / starting point in the list of all available items, starting from which results will be returned. The numeric offset identifies the page token, allowing users to advance to the next page in the collection. The value 0 (zero) identifies the first page of entry..</param>
        /// <param name="limit">Optional parameter: The maximum number of items to return in a page. If unspecified, the default limit will be returned. If the limit specified is greater than the maximum permitted by the API, the API will return the maximum permitted limit. Each API should define *maximum and *default limit..</param>
        /// <param name="toDate">Optional parameter: The query parameter can use either a specific creation_from_date or date range in the form of creation_from_date and creation_to_date. For a specific date, creation_to_date must not be provided. The result will be filtered on creation_date_time. Expressed in the YYYY-MM-DD format. The date cannot be in the future.  Usage - When used in conjunction with the statement-period (weekly, monthly, yearly) and from date,  the endpoint returns the statement where the from date to date fall within that period. The parameter must not be used for the statement period EODY. If supplied, the parameter will be ignored..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the Models.AccountsStatementsResponse response from the API call.</returns>
        public async Task<Models.AccountsStatementsResponse> GetAccountStatementAsync(
                string xBIC,
                string accountIdentification,
                string fromDate,
                string xRequestID = null,
                string xUserContext = null,
                int? offset = 0,
                int? limit = null,
                string toDate = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.AccountsStatementsResponse>()
              .Server(Server.AutoMockingServer)
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/accounts/{account-identification}/statements")
                  .WithAuth("oauthBearerToken")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("X-BIC", xBIC))
                      .Template(template => template.Setup("account-identification", accountIdentification))
                      .Query(query => query.Setup("from-date", fromDate))
                      .Header(header => header.Setup("X-Request-ID", xRequestID))
                      .Header(header => header.Setup("X-UserContext", xUserContext))
                      .Query(query => query.Setup("offset", offset ?? 0))
                      .Query(query => query.Setup("limit", limit))
                      .Query(query => query.Setup("to-date", toDate))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Bad Request", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("401", CreateErrorCase("Unauthorized", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("403", CreateErrorCase("Forbidden", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("Not Found", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("406", CreateErrorCase("Not Acceptable", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("415", CreateErrorCase("Unsupported Media Type", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("429", CreateErrorCase("Too Many Requests", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("500", CreateErrorCase("Internal Server Error", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("502", CreateErrorCase("Bad Gateway", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("503", CreateErrorCase("Service Unavailable", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("504", CreateErrorCase("Gateway Timeout", (errorReason, context) => new ErrorMessageException(errorReason, context)))
                  .ErrorCase("0", CreateErrorCase("Internal Server Error", (errorReason, context) => new ErrorMessageException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}