// <copyright file="Environment.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace SwiftBankingAPIPortal.Standard
{
    /// <summary>
    /// Available environments.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Environment
    {
        /// <summary>
        /// Token.
        /// </summary>
        [EnumMember(Value = "Token")]
        Token,

        /// <summary>
        /// Production.
        /// </summary>
        [EnumMember(Value = "Production")]
        Production,

        /// <summary>
        /// Pilot.
        /// </summary>
        [EnumMember(Value = "Pilot")]
        Pilot,

        /// <summary>
        /// Sandbox.
        /// </summary>
        [EnumMember(Value = "Sandbox")]
        Sandbox,

        /// <summary>
        /// AutoMock.
        /// </summary>
        [EnumMember(Value = "AutoMock")]
        AutoMock,
    }
}
