// <copyright file="Server.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>

namespace SwiftBankingAPIPortal.Standard
{
    /// <summary>
    /// Available servers.
    /// </summary>
    public enum Server
    {
        /// <summary>
        /// OAuthServer.
        /// </summary>
        OAuthServer,

        /// <summary>
        /// AutoMockingServer.
        /// </summary>
        AutoMockingServer,

        /// <summary>
        /// LiveServer.
        /// </summary>
        LiveServer,

        /// <summary>
        /// PilotServer.
        /// </summary>
        PilotServer,

        /// <summary>
        /// SandboxServer.
        /// </summary>
        SandboxServer,
    }
}
