// <copyright file="SwiftBankingAPIPortalClient.cs" company="APIMatic">
// SwiftBankingAPIPortal.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Authentication;
using APIMatic.Core.Utilities;
using Microsoft.Extensions.Configuration;
using SwiftBankingAPIPortal.Standard.Authentication;
using SwiftBankingAPIPortal.Standard.Controllers;
using SwiftBankingAPIPortal.Standard.Http.Client;
using System;
using System.Collections.Generic;

namespace SwiftBankingAPIPortal.Standard
{
    /// <summary>
    /// The gateway for the SDK. This class acts as a factory for Controller and
    /// holds the configuration of the SDK.
    /// </summary>
    public sealed class SwiftBankingAPIPortalClient : IConfiguration
    {
        // A map of environments and their corresponding servers/baseurls
        private static readonly Dictionary<Environment, Dictionary<Enum, string>> EnvironmentsMap =
            new Dictionary<Environment, Dictionary<Enum, string>>
        {
            {
                Environment.Token, new Dictionary<Enum, string>
                {
                    { Server.OAuthServer, "https://sandbox.swift.com/oauth2/v1" },
                    { Server.AutoMockingServer, "https://virtserver.swaggerhub.com/SWIFT-API/corporate-to_bank_account_balance_information/1.0.9" },
                    { Server.LiveServer, "https://api.swiftnet.sipn.swift.com/swift-cash-management/v1" },
                    { Server.PilotServer, "https://api-test.swiftnet.sipn.swift.com/swift-cash-management-pilot/v1" },
                    { Server.SandboxServer, "https://sandbox.swift.com/swift-cash-management/v1" },
                }
            },
            {
                Environment.Production, new Dictionary<Enum, string>
                {
                    { Server.OAuthServer, "https://sandbox.swift.com/oauth2/v1" },
                    { Server.AutoMockingServer, "https://virtserver.swaggerhub.com/SWIFT-API/corporate-to_bank_account_balance_information/1.0.9" },
                    { Server.LiveServer, "https://api.swiftnet.sipn.swift.com/swift-cash-management/v1" },
                    { Server.PilotServer, "https://api-test.swiftnet.sipn.swift.com/swift-cash-management-pilot/v1" },
                    { Server.SandboxServer, "https://sandbox.swift.com/swift-cash-management/v1" },
                }
            },
            {
                Environment.Pilot, new Dictionary<Enum, string>
                {
                    { Server.OAuthServer, "https://sandbox.swift.com/oauth2/v1" },
                    { Server.AutoMockingServer, "https://virtserver.swaggerhub.com/SWIFT-API/corporate-to_bank_account_balance_information/1.0.9" },
                    { Server.LiveServer, "https://api.swiftnet.sipn.swift.com/swift-cash-management/v1" },
                    { Server.PilotServer, "https://api-test.swiftnet.sipn.swift.com/swift-cash-management-pilot/v1" },
                    { Server.SandboxServer, "https://sandbox.swift.com/swift-cash-management/v1" },
                }
            },
            {
                Environment.Sandbox, new Dictionary<Enum, string>
                {
                    { Server.OAuthServer, "https://sandbox.swift.com/oauth2/v1" },
                    { Server.AutoMockingServer, "https://virtserver.swaggerhub.com/SWIFT-API/corporate-to_bank_account_balance_information/1.0.9" },
                    { Server.LiveServer, "https://api.swiftnet.sipn.swift.com/swift-cash-management/v1" },
                    { Server.PilotServer, "https://api-test.swiftnet.sipn.swift.com/swift-cash-management-pilot/v1" },
                    { Server.SandboxServer, "https://sandbox.swift.com/swift-cash-management/v1" },
                }
            },
            {
                Environment.AutoMock, new Dictionary<Enum, string>
                {
                    { Server.OAuthServer, "https://sandbox.swift.com/oauth2/v1" },
                    { Server.AutoMockingServer, "https://virtserver.swaggerhub.com/SWIFT-API/corporate-to_bank_account_balance_information/1.0.9" },
                    { Server.LiveServer, "https://api.swiftnet.sipn.swift.com/swift-cash-management/v1" },
                    { Server.PilotServer, "https://api-test.swiftnet.sipn.swift.com/swift-cash-management-pilot/v1" },
                    { Server.SandboxServer, "https://sandbox.swift.com/swift-cash-management/v1" },
                }
            },
        };

        private readonly GlobalConfiguration globalConfiguration;
        private const string userAgent = "APIMATIC 3.0";
        private readonly HttpCallback httpCallback;
        private readonly Lazy<AuthorizationController> authorization;
        private readonly Lazy<AccountInformationController> accountInformation;
        private readonly Lazy<ReportingController> reporting;

        private SwiftBankingAPIPortalClient(
            Environment environment,
            BasicAuthModel basicAuthModel,
            OauthBearerTokenModel oauthBearerTokenModel,
            HttpCallback httpCallback,
            IHttpClientConfiguration httpClientConfiguration)
        {
            this.Environment = environment;
            this.httpCallback = httpCallback;
            this.HttpClientConfiguration = httpClientConfiguration;
            BasicAuthModel = basicAuthModel;
            var basicAuthManager = new BasicAuthManager(basicAuthModel);
            OauthBearerTokenModel = oauthBearerTokenModel;
            var oauthBearerTokenManager = new OauthBearerTokenManager(oauthBearerTokenModel);
            globalConfiguration = new GlobalConfiguration.Builder()
                .AuthManagers(new Dictionary<string, AuthManager> {
                    {"basicAuth", basicAuthManager},
                    {"oauthBearerToken", oauthBearerTokenManager},
                })
                .ApiCallback(httpCallback)
                .HttpConfiguration(httpClientConfiguration)
                .ServerUrls(EnvironmentsMap[environment], Server.OAuthServer)
                .UserAgent(userAgent)
                .Build();
            BasicAuthCredentials = basicAuthManager;
            OauthBearerTokenCredentials = oauthBearerTokenManager;

            this.authorization = new Lazy<AuthorizationController>(
                () => new AuthorizationController(globalConfiguration));
            this.accountInformation = new Lazy<AccountInformationController>(
                () => new AccountInformationController(globalConfiguration));
            this.reporting = new Lazy<ReportingController>(
                () => new ReportingController(globalConfiguration));
        }

        /// <summary>
        /// Gets AuthorizationController controller.
        /// </summary>
        public AuthorizationController AuthorizationController => this.authorization.Value;

        /// <summary>
        /// Gets AccountInformationController controller.
        /// </summary>
        public AccountInformationController AccountInformationController => this.accountInformation.Value;

        /// <summary>
        /// Gets ReportingController controller.
        /// </summary>
        public ReportingController ReportingController => this.reporting.Value;

        /// <summary>
        /// Gets the configuration of the Http Client associated with this client.
        /// </summary>
        public IHttpClientConfiguration HttpClientConfiguration { get; }

        /// <summary>
        /// Gets Environment.
        /// Current API environment.
        /// </summary>
        public Environment Environment { get; }

        /// <summary>
        /// Gets http callback.
        /// </summary>
        public HttpCallback HttpCallback => this.httpCallback;

        /// <summary>
        /// Gets the credentials to use with BasicAuth.
        /// </summary>
        public IBasicAuthCredentials BasicAuthCredentials { get; private set; }

        /// <summary>
        /// Gets the credentials model to use with BasicAuth.
        /// </summary>
        public BasicAuthModel BasicAuthModel { get; private set; }

        /// <summary>
        /// Gets the credentials to use with OauthBearerToken.
        /// </summary>
        public IOauthBearerTokenCredentials OauthBearerTokenCredentials { get; private set; }

        /// <summary>
        /// Gets the credentials model to use with OauthBearerToken.
        /// </summary>
        public OauthBearerTokenModel OauthBearerTokenModel { get; private set; }

        /// <summary>
        /// Gets the access token to use with OAuth 2 authentication.
        /// </summary>
        public string AccessToken => this.OauthBearerTokenCredentials.AccessToken;

        /// <summary>
        /// Gets the URL for a particular alias in the current environment and appends
        /// it with template parameters.
        /// </summary>
        /// <param name="alias">Default value:OAUTH SERVER.</param>
        /// <returns>Returns the baseurl.</returns>
        public string GetBaseUri(Server alias = Server.OAuthServer)
        {
            return globalConfiguration.ServerUrl(alias);
        }

        /// <summary>
        /// Creates an object of the SwiftBankingAPIPortalClient using the values provided for the builder.
        /// </summary>
        /// <returns>Builder.</returns>
        public Builder ToBuilder()
        {
            Builder builder = new Builder()
                .Environment(this.Environment)
                .HttpCallback(httpCallback)
                .HttpClientConfig(config => config.Build());

            if (BasicAuthModel != null)
            {
                builder.BasicAuthCredentials(BasicAuthModel.ToBuilder().Build());
            }

            if (OauthBearerTokenModel != null)
            {
                builder.OauthBearerTokenCredentials(OauthBearerTokenModel.ToBuilder().Build());
            }

            return builder;
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            return
                $"Environment = {this.Environment}, " +
                $"HttpClientConfiguration = {this.HttpClientConfiguration}, ";
        }

        /// <summary>
        /// Creates the client using builder.
        /// </summary>
        /// <returns> SwiftBankingAPIPortalClient.</returns>
        internal static SwiftBankingAPIPortalClient CreateFromEnvironment()
        {
            var builder = new Builder();

            string environment = System.Environment.GetEnvironmentVariable("SWIFT_BANKING_API_PORTAL_STANDARD_ENVIRONMENT");
            string username = System.Environment.GetEnvironmentVariable("SWIFT_BANKING_API_PORTAL_STANDARD_USERNAME");
            string password = System.Environment.GetEnvironmentVariable("SWIFT_BANKING_API_PORTAL_STANDARD_PASSWORD");
            string accessToken = System.Environment.GetEnvironmentVariable("SWIFT_BANKING_API_PORTAL_STANDARD_ACCESS_TOKEN");

            if (environment != null)
            {
                builder.Environment(CoreHelper.JsonDeserialize<Environment>($"\"{environment}\""));
            }

            if (username != null && password != null)
            {
                builder.BasicAuthCredentials(new BasicAuthModel
                .Builder(username, password)
                .Build());
            }

            if (accessToken != null)
            {
                builder.OauthBearerTokenCredentials(new OauthBearerTokenModel
                .Builder(accessToken)
                .Build());
            }

            return builder.Build();
        }

        /// <summary>
        /// Creates the client from configuration.
        /// </summary>
        /// <returns> SwiftBankingAPIPortalClient.</returns>
        public static SwiftBankingAPIPortalClient FromConfiguration(IConfigurationSection configuration) =>
            Builder.FromConfiguration(configuration).Build();

        /// <summary>
        /// Builder class.
        /// </summary>
        public class Builder
        {
            private Environment _environment = SwiftBankingAPIPortal.Standard.Environment.Token;
            private BasicAuthModel _basicAuthModel = new BasicAuthModel();
            private OauthBearerTokenModel _oauthBearerTokenModel = new OauthBearerTokenModel();
            private HttpClientConfiguration.Builder _httpClientConfig = new HttpClientConfiguration.Builder();
            private HttpCallback _httpCallback;

            /// <summary>
            /// Sets credentials for BasicAuth.
            /// </summary>
            /// <param name="basicAuthModel">BasicAuthModel.</param>
            /// <returns>Builder.</returns>
            public Builder BasicAuthCredentials(BasicAuthModel basicAuthModel)
            {
                _basicAuthModel = basicAuthModel ??
                    throw new ArgumentNullException(nameof(basicAuthModel));
                return this;
            }

            /// <summary>
            /// Sets credentials for OauthBearerToken.
            /// </summary>
            /// <param name="oauthBearerTokenModel">OauthBearerTokenModel.</param>
            /// <returns>Builder.</returns>
            public Builder OauthBearerTokenCredentials(OauthBearerTokenModel oauthBearerTokenModel)
            {
                _oauthBearerTokenModel = oauthBearerTokenModel ??
                    throw new ArgumentNullException(nameof(oauthBearerTokenModel));
                return this;
            }

            /// <summary>
            /// Sets Environment.
            /// </summary>
            /// <param name="environment"> Environment. </param>
            /// <returns> Builder. </returns>
            public Builder Environment(Environment environment)
            {
                _environment = environment;
                return this;
            }

            /// <summary>
            /// Sets HttpClientConfig.
            /// </summary>
            /// <param name="action"> Action. </param>
            /// <returns>Builder.</returns>
            public Builder HttpClientConfig(Action<HttpClientConfiguration.Builder> action)
            {
                if (action is null)
                {
                    throw new ArgumentNullException(nameof(action));
                }

                action(_httpClientConfig);
                return this;
            }

            private Builder HttpClientConfig(HttpClientConfiguration.Builder httpClientConfigurationBuilder)
            {
                if (httpClientConfigurationBuilder != null)
                {
                    _httpClientConfig = httpClientConfigurationBuilder;
                }

                return this;
            }

            /// <summary>
            /// Sets the HttpCallback for the Builder.
            /// </summary>
            /// <param name="httpCallback"> http callback. </param>
            /// <returns>Builder.</returns>
            public Builder HttpCallback(HttpCallback httpCallback)
            {
                _httpCallback = httpCallback;
                return this;
            }

            /// <summary>
            /// Creates an object of the SwiftBankingAPIPortalClient using the values provided for the builder.
            /// </summary>
            /// <returns>SwiftBankingAPIPortalClient.</returns>
            public SwiftBankingAPIPortalClient Build()
            {
                if (_basicAuthModel.Username == null || _basicAuthModel.Password == null)
                {
                    _basicAuthModel = null;
                }
                if (_oauthBearerTokenModel.AccessToken == null)
                {
                    _oauthBearerTokenModel = null;
                }
                return new SwiftBankingAPIPortalClient(
                    _environment,
                    _basicAuthModel,
                    _oauthBearerTokenModel,
                    _httpCallback,
                    _httpClientConfig.Build());
            }

            /// <summary>
            /// Creates the client builder from configuration.
            /// </summary>
            /// <returns> Builder.</returns>
            public static Builder FromConfiguration(IConfigurationSection config)
            {
                var builder = new Builder();
                var options = config.Get<SwiftBankingAPIPortalClientOptions>();
                if (options == null) return builder;
                if (options.Environment != null)
                    builder.Environment(options.Environment.Value);
                if (options.BasicAuthCredentials != null)
                    builder.BasicAuthCredentials(BasicAuthModel.FromOptions(options.BasicAuthCredentials));
                if (options.OauthBearerTokenCredentials != null)
                    builder.OauthBearerTokenCredentials(OauthBearerTokenModel.FromOptions(options.OauthBearerTokenCredentials));
                if (options.HttpClientConfig != null)
                    builder.HttpClientConfig(Http.Client.HttpClientConfiguration.FromOptions(options.HttpClientConfig));
                return builder;
            }
        }

        public class SwiftBankingAPIPortalClientOptions
        {
            public Environment? Environment { get; set; }
            public BasicAuthModelOptions BasicAuthCredentials { get; set; }
            public OauthBearerTokenModelOptions OauthBearerTokenCredentials { get; set; }
            public HttpClientConfigurationOptions HttpClientConfig { get; set; }
        }
    }
}
