// <copyright file="AccountInformationControllerTest.cs" company="APIMatic">
// SwiftBankingAPIPortal.Tests
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using APIMatic.Core.Utilities;
using NUnit.Framework;
using Newtonsoft.Json.Converters;
using SwiftBankingAPIPortal.Standard;
using SwiftBankingAPIPortal.Standard.Controllers;
using SwiftBankingAPIPortal.Standard.Exceptions;
using SwiftBankingAPIPortal.Standard.Http.Client;
using SwiftBankingAPIPortal.Standard.Http.Response;
using SwiftBankingAPIPortal.Standard.Models.Containers;
using SwiftBankingAPIPortal.Standard.Utilities;

namespace SwiftBankingAPIPortal.Tests
{
    /// <summary>
    /// AccountInformationControllerTest.
    /// </summary>
    [TestFixture]
    public class AccountInformationControllerTest : ControllerTestBase
    {
        /// <summary>
        /// Controller instance (for all tests).
        /// </summary>
        private AccountInformationController controller;

        /// <summary>
        /// Setup test class.
        /// </summary>
        [OneTimeSetUp]
        public void SetUpDerived()
        {
            this.controller = this.Client.AccountInformationController;
        }

        /// <summary>
        /// The endpoint will retrieve all accounts with balance information for a specific account owner meeting the query parameters when supplied. The endpoint will return an empty array when no resource is found.
        ///
        ///**Specifying Request Filter**
        ///
        ///Parameters are specified in the form name=value. A parameter list is appended to a URI after a "?". Multiple parameters are separated by "&".
        ///
        ///`Note that the query parameters are not URL encoded for readability.`
        ///
        ///**Use of logical operator OR (account-identification DE27212110090000000235698765 or DE27212318890001010223463456)**
        ///
        ///https://developer.swift.com/accounts?account-identification=DE27212110090000000235698765,DE27212318890001010223463456&limit=25&offset=0   
        ///
        ///**Use of logical operator AND (account-servicer and account-identification)**
        ///
        ///https://developer.swift.com/accounts?account-servicer=DEUTDEFF&account-identification=DE27212110090000000235698765&currency=EUR&limit=25&offset=0       
        ///.
        /// </summary>
        /// <returns>A <see cref="Task"/> representing the asynchronous unit test.</returns>
        [Test]
        public async Task TestTestGetAccounts()
        {
            // Parameters for the API call
            string xBIC = "DEUTDEFF";
            string xRequestID = null;
            string xUserContext = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiIiwiaWF0IjowfQ.u_kftAUkjiUZO-OhIyj24H7lOUk1wi9GUF-e14JmCtQ";
            List<string> accountIdentification = null;
            List<string> accountServicer = null;
            string currency = "EUR";
            int? offset = 0;
            int? limit = 1000;

            // Perform API call
            Standard.Models.AccountsResponse result = null;
            try
            {
                result = await this.controller.GetAccountsAsync(xBIC, xRequestID, xUserContext, accountIdentification, accountServicer, currency, offset, limit);
            }
            catch (ApiException)
            {
            }

            // Test response code
            Assert.AreEqual(200, HttpCallBack.Response.StatusCode, "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("X-Request-ID", null);
            headers.Add("Content-Type", "application/json");

            Assert.IsTrue(
                    TestHelper.AreHeadersProperSubsetOf (
                    headers,
                    HttpCallBack.Response.Headers),
                    "Headers should match");

            // Test whether the captured response is as we expected
            Assert.IsNotNull(result, "Result should exist");
            Assert.IsTrue(
                    TestHelper.IsProperSubsetOf(
                    "{\"cash_account\":[{\"account_identification\":\"string\",\"alternate_identification\":\"3fa85f64-5717-4562-b3fc-2c963f66afa6\",\"account_servicer\":\"ZBBKOCRW665\",\"name\":\"string\",\"owner_name\":\"string\",\"currency\":\"EUR\",\"related_account\":\"string\",\"balances\":{\"current_balance\":{\"balance_amount\":{\"amount\":{\"currency\":\"EUR\",\"amount\":\"0000000000000000000\"},\"credit_debit_indicator\":\"CRDT\"},\"last_change_date_time\":\"2022-04-12T02:22:27+01:00\",\"date_time\":\"2022-04-12T20:00:46+01:00\",\"last_committed_transaction_identification\":\"string\",\"credit_line\":[{\"included\":true,\"type\":\"string\",\"amount\":{\"currency\":\"EUR\",\"amount\":\"0000000000000000000\"}}]},\"available_balance\":{\"balance_amount\":{\"amount\":{\"currency\":\"EUR\",\"amount\":\"0000000000000000000\"},\"credit_debit_indicator\":\"CRDT\"},\"availability_date\":\"2022-04-12T04:51:22+01:00\"},\"forward_available_balance\":[{\"balance_amount\":{\"amount\":{\"currency\":\"EUR\",\"amount\":\"0000000000000000000\"},\"credit_debit_indicator\":\"CRDT\"},\"availability_date\":\"7200-02-29\"}]},\"status\":\"string\",\"credit_limit\":{\"currency\":\"EUR\",\"amount\":\"0000000000000503180\"},\"links\":[{\"href\":\"string\",\"rel\":\"string\",\"type\":\"string\"}]}],\"links\":[{\"href\":\"string\",\"rel\":\"string\",\"type\":\"string\"}]}",
                    TestHelper.ConvertStreamToString(HttpCallBack.Response.RawBody),
                    false,
                    true,
                    false),
                    "Response body should have matching keys");
        }

        /// <summary>
        /// The endpoint will retrieve the account with balance information based on a specific account identification..
        /// </summary>
        /// <returns>A <see cref="Task"/> representing the asynchronous unit test.</returns>
        [Test]
        public async Task TestTestGetAccount()
        {
            // Parameters for the API call
            string xBIC = "DEUTDEFF";
            string accountIdentification = "DE27212110090000000235698765";
            string xRequestID = null;
            string xUserContext = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiIiwiaWF0IjowfQ.u_kftAUkjiUZO-OhIyj24H7lOUk1wi9GUF-e14JmCtQ";

            // Perform API call
            Standard.Models.AccountsResponse2 result = null;
            try
            {
                result = await this.controller.GetAccountAsync(xBIC, accountIdentification, xRequestID, xUserContext);
            }
            catch (ApiException)
            {
            }

            // Test response code
            Assert.AreEqual(200, HttpCallBack.Response.StatusCode, "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("X-Request-ID", null);
            headers.Add("Content-Type", "application/json");

            Assert.IsTrue(
                    TestHelper.AreHeadersProperSubsetOf (
                    headers,
                    HttpCallBack.Response.Headers),
                    "Headers should match");

            // Test whether the captured response is as we expected
            Assert.IsNotNull(result, "Result should exist");
            Assert.IsTrue(
                    TestHelper.IsProperSubsetOf(
                    "{\"account_identification\":\"string\",\"alternate_identification\":\"3fa85f64-5717-4562-b3fc-2c963f66afa6\",\"account_servicer\":\"6XI9UOK4NWX\",\"name\":\"string\",\"owner_name\":\"string\",\"currency\":\"EUR\",\"related_account\":\"string\",\"balances\":{\"current_balance\":{\"balance_amount\":{\"amount\":{\"currency\":\"EUR\",\"amount\":\"0000000000000000000\"},\"credit_debit_indicator\":\"CRDT\"},\"last_change_date_time\":\"2022-04-12T17:20:23+01:00\",\"date_time\":\"2022-04-12T07:10:35+01:00\",\"last_committed_transaction_identification\":\"string\",\"credit_line\":[{\"included\":true,\"type\":\"string\",\"amount\":{\"currency\":\"EUR\",\"amount\":\"0000000000000000000\"}}]},\"available_balance\":{\"balance_amount\":{\"amount\":{\"currency\":\"EUR\",\"amount\":\"0000000000000000000\"},\"credit_debit_indicator\":\"CRDT\"},\"availability_date\":\"2022-04-12T07:10:35+01:00\"},\"forward_available_balance\":[{\"balance_amount\":{\"amount\":{\"currency\":\"EUR\",\"amount\":\"0000000000000000000\"},\"credit_debit_indicator\":\"CRDT\"},\"availability_date\":\"2022-04-12\"}]},\"status\":\"string\",\"credit_limit\":{\"currency\":\"EUR\",\"amount\":\"0000000000000000000\"},\"links\":[{\"href\":\"string\",\"rel\":\"string\",\"type\":\"string\"}]}",
                    TestHelper.ConvertStreamToString(HttpCallBack.Response.RawBody),
                    false,
                    true,
                    false),
                    "Response body should have matching keys");
        }

        /// <summary>
        /// The transaction summary endpoint provides the total net, debit and credit entries..
        /// </summary>
        /// <returns>A <see cref="Task"/> representing the asynchronous unit test.</returns>
        [Test]
        public async Task TestTestGetTransactionSummary()
        {
            // Parameters for the API call
            string xBIC = "DEUTDEFF";
            string accountIdentification = "DE27212110090000000235698765";
            string fromDate = "2021-09-15";
            string xRequestID = null;
            string xUserContext = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiIiwiaWF0IjowfQ.u_kftAUkjiUZO-OhIyj24H7lOUk1wi9GUF-e14JmCtQ";
            string toDate = "2021-09-15";

            // Perform API call
            Standard.Models.AccountsTransactionSummaryResponse result = null;
            try
            {
                result = await this.controller.GetTransactionSummaryAsync(xBIC, accountIdentification, fromDate, xRequestID, xUserContext, toDate);
            }
            catch (ApiException)
            {
            }

            // Test response code
            Assert.AreEqual(200, HttpCallBack.Response.StatusCode, "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("X-Request-ID", null);
            headers.Add("Content-Type", "application/json");

            Assert.IsTrue(
                    TestHelper.AreHeadersProperSubsetOf (
                    headers,
                    HttpCallBack.Response.Headers),
                    "Headers should match");

            // Test whether the captured response is as we expected
            Assert.IsNotNull(result, "Result should exist");
            Assert.IsTrue(
                    TestHelper.IsProperSubsetOf(
                    "{\"account_identification\":\"string\",\"from_date_time\":\"2022-04-12T21:44:56+01:00\",\"to_date_time\":\"2022-04-12T20:10:42+01:00\",\"total_entries\":{\"number_of_entries\":\"1574\",\"total_net_entry\":{\"amount\":{\"currency\":\"EUR\",\"amount\":\"0000000000000000000\"},\"credit_debit_indicator\":\"CRDT\"}},\"total_credit_entries\":{\"number_of_entries\":\"14717605\",\"total\":{\"currency\":\"EUR\",\"amount\":\"00000000666183886.3\"}},\"total_debit_entries\":{\"number_of_entries\":\"046724\",\"total\":{\"currency\":\"EUR\",\"amount\":\"0000000000000000000\"}}}",
                    TestHelper.ConvertStreamToString(HttpCallBack.Response.RawBody),
                    false,
                    true,
                    false),
                    "Response body should have matching keys");
        }
    }
}