// <copyright file="ControllerTestBase.cs" company="APIMatic">
// SwiftBankingAPIPortal.Tests
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;
using SwiftBankingAPIPortal.Standard;
using SwiftBankingAPIPortal.Standard.Authentication;
using SwiftBankingAPIPortal.Standard.Http.Client;
using SwiftBankingAPIPortal.Standard.Models;
using SwiftBankingAPIPortal.Standard.Models.Containers;

namespace SwiftBankingAPIPortal.Tests
{
    /// <summary>
    /// ControllerTestBase Class.
    /// </summary>
    [TestFixture]
    public class ControllerTestBase
    {
        /// <summary>
        /// Assert precision.
        /// </summary>
        protected const double AssertPrecision = 0.1;

        /// <summary>
        /// Gets HttpCallBackHandler.
        /// </summary>
        internal HttpCallback HttpCallBack { get; private set; } = new HttpCallback();

        /// <summary>
        /// Gets SwiftBankingAPIPortalClient Client.
        /// </summary>
        protected SwiftBankingAPIPortalClient Client { get; private set; }

        /// <summary>
        /// Set up the client.
        /// </summary>
        [OneTimeSetUp]
        public void SetUp()
        {
            SwiftBankingAPIPortalClient config = SwiftBankingAPIPortalClient.CreateFromEnvironment();
            this.Client = config.ToBuilder()
                .HttpCallback(HttpCallBack)
                .Build();
        }
    }
}